<a href="https://colab.research.google.com/github/lzxatdk-tech/NLP_project/blob/main/reliable_multilingual_question_answering.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Environment Setup

## Mount data folder

In [1]:
from google.colab import drive
drive.mount('/content/drive')

import os
folder_path = '/content/drive/MyDrive/Shared_NLP_Project'

os.chdir(folder_path)

Mounted at /content/drive

## Download or load dataset

In [2]:
import os
import pandas as pd
from datasets import load_dataset, load_from_disk

TARGET_DIR = "./tydi_xor_rc"

def get_data():
  if not os.path.exists(TARGET_DIR):
      print(f"Downloading dataset to {TARGET_DIR}...")
      dataset = load_dataset("coastalcph/tydi_xor_rc")
      dataset.save_to_disk(TARGET_DIR)
      print("Download and save complete.")
  else:
      print(f"Found existing dataset at {TARGET_DIR}. Loading from disk...")
      dataset = load_from_disk(TARGET_DIR)
      print("Loading completes.")

  if os.path.exists("train_dataset.csv"):
    df_train = pd.read_csv("train_dataset.csv")
  else:
    df_train = dataset["train"].to_pandas()


  if os.path.exists("val_dataset.csv"):
    df_val = pd.read_csv("val_dataset.csv")
  else:
    df_val = dataset["validation"].to_pandas()

  return df_train, df_val

df_train, df_val = get_data()

Found existing dataset at ./tydi_xor_rc. Loading from disk...
Loading completes.

## Imports

In [3]:
%pip install -q "nltk>=3.9,<4" "spacy>=3.8,<4" "transformers>=5,<6"
!python -m spacy download ko_core_news_sm en_core_web_sm

Collecting ko-core-news-sm==3.8.0
  Downloading ko_core_news_sm-3.8.0-py3-none-any.whl (14.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.7/14.7 MB 35.1 MB/s  0:00:00
Requirement already satisfied: en_core_web_sm in /usr/local/lib/python3.13/dist-packages (3.8.0)
Installing collected packages: ko-core-news-sm
Successfully installed ko-core-news-sm-3.8.0
✔ Download and installation successful
You can now load the package via spacy.load('ko_core_news_sm')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.

In [4]:
!pip install -q datasets accelerate

In [5]:
import random
import re

import math
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import spacy
from datasets import load_dataset
from sklearn.feature_extraction import DictVectorizer
from sklearn.linear_model import SGDClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, f1_score
from transformers import (
    AutoModelForSeq2SeqLM,
    AutoTokenizer,
    AutoModelForQuestionAnswering,
    DefaultDataCollator,
    TrainingArguments,
    Trainer,
)
from torch.utils.data import DataLoader
from tqdm.auto import tqdm
from collections import Counter
import json

random.seed(42)
np.random.seed(42)

## Spacy setup

In [6]:
nlp_ar_spacy = spacy.blank("ar")
nlp_ko_spacy = spacy.load("ko_core_news_sm")
nlp_te_spacy = spacy.blank("te")
nlp_en_spacy = spacy.load("en_core_web_sm")

## Translator

In [7]:
tokenizer = AutoTokenizer.from_pretrained("facebook/nllb-200-distilled-600M")
model = AutoModelForSeq2SeqLM.from_pretrained("facebook/nllb-200-distilled-600M", attn_implementation="sdpa", device_map="auto")

lang_code_trans = {"ar": "arb_Arab", "ko": "kor_Hang", "te": "tel_Telu", "en": "eng_Latn"}

config.json:   0%|          | 0.00/846 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

tokenizer_config.json:   0%|          | 0.00/564 [00:00<?, ?B/s]

sentencepiece.bpe.model: reconstructing file:   0%|          |  0.00B / 4.85MB

sentencepiece.bpe.model: downloading bytes:           |  0.00B

tokenizer.json: reconstructing file:   0%|          |  0.00B / 17.3MB

tokenizer.json: downloading bytes:           |  0.00B

special_tokens_map.json:   0%|          | 0.00/3.55k [00:00<?, ?B/s]

pytorch_model.bin: reconstructing file:   0%|          |  0.00B / 2.46GB

pytorch_model.bin: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/512 [00:00<?, ?it/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 2.46GB

model.safetensors: downloading bytes:           |  0.00B

generation_config.json:   0%|          | 0.00/189 [00:00<?, ?B/s]

In [8]:
def translate(text, source, target):
  tokenizer.src_lang = lang_code_trans[source]
  inputs = tokenizer(text, return_tensors="pt").to(model.device)

  translated_tokens = model.generate(
    **inputs, forced_bos_token_id=tokenizer.convert_tokens_to_ids(lang_code_trans[target]), max_length=128
  )

  return tokenizer.batch_decode(translated_tokens, skip_special_tokens=True)[0]


def translate_row(row):
  text = row["question"]
  source = row["lang"]

  if source not in [TE, AR, KO]:
    return None
  return translate(text,source,"en")


TE = "te"
AR = "ar"
KO = "ko"
EN = "en"

te_example = "ప్రపంచంలో  మొట్టమొదటి దూర విద్య విద్యాలయం ఏ దేశంలో స్థాపించబడింది ?"
ar_example = "متى تدخلت روسيا في  الحرب الأهلية السورية؟"
ko_example = "30년 전쟁의 승자는 누구인가?"

print(te_example, "->", translate(te_example,TE,EN))
print(ar_example, "->", translate(ar_example,AR,EN))
print(ko_example, "->", translate(ko_example,KO,EN))

ప్రపంచంలో  మొట్టమొదటి దూర విద్య విద్యాలయం ఏ దేశంలో స్థాపించబడింది ? -> Which country was the first distance education college in the world established?
متى تدخلت روسيا في  الحرب الأهلية السورية؟ -> When did Russia intervene in the Syrian civil war?
30년 전쟁의 승자는 누구인가? -> Who is the winner of the Thirty Years' War?

## Data processing

In [9]:
# add column of question translated to english and save it to a new csv
if not os.path.exists("train_dataset.csv"):
  df_train["question_translated"] = df_train.apply(translate_row, axis=1)
  df_train.to_csv("train_dataset.csv", index=False)

if not os.path.exists("val_dataset.csv"):
  df_val["question_translated"] = df_train.apply(translate_row, axis=1)
  df_val.to_csv("val_dataset.csv", index=False)

In [10]:
df_train

,question,context,lang,answerable,answer_start,answer,answer_inlang,question_translated
0,উইকিলিকস কত সালে সর্বপ্রথম ইন্টারনেটে প্রথম তথ...,WikiLeaks () is an international non-profit or...,bn,True,182,2006,NaN,NaN
1,দ্বিতীয় বিশ্বযুদ্ধে কোন দেশ পরাজিত হয় ?,The war in Europe concluded with an invasion o...,bn,True,48,Germany,NaN,NaN
2,মার্কিন যুক্তরাষ্ট্রের সংবিধান অনুযায়ী মার্কিন...,Same-sex marriage in the United States expande...,bn,False,-1,no,NaN,NaN
3,আরব-ইসরায়েলি যুদ্ধে আরবের মোট কয়জন সৈন্যের মৃ...,The exact number of Arab casualties is unknown...,bn,True,39,unknown,NaN,NaN
4,বিশ্বে প্রথম পুঁজিবাদী সমাজ কবে গড়ে ওঠে ?,"As Thomas Hall (2000) notes, ""The Sung Empire ...",bn,True,1219,17th century,NaN,NaN
...,...,...,...,...,...,...,...,...
15338,소말리아는 2차 개헌을 언제 했나요?,"In February 2012, Somali government officials ...",ko,True,923,23 June 2012,NaN,When did Somalia make its second inauguration?
15339,세상에서 가장 먼저 시작된 교통수단은 무엇인가?,The first earth tracks were created by humans ...,ko,True,160,animals,NaN,What was the first transportation system in th...
15340,2019년 이집트의 지도자는 누구인가?,"Abdel Fattah Saeed Hussein Khalil El-Sisi ( """"...",ko,True,0,Abdel Fattah Saeed Hussein Khalil El-Sisi,NaN,Who is the leader of Egypt in 2019?
15341,독일에서 가장 인구밀도가 높은 도시는 무엇인가?,Munich (; ; ) is the capital and most populous...,ko,True,205,Berlin,NaN,What is the most densely populated city in Ger...
15342,개혁침례교는 신교와 상관관계가있는가?,"Anabaptism (from Neo-Latin ""anabaptista"", from...",ko,False,-1,no,NaN,Is Reformed Baptism related to the New Order?

In [11]:
df_val

,question,context,lang,answerable,answer_start,answer,answer_inlang,question_translated
0,ఒరెగాన్ రాష్ట్రంలోని అతిపెద్ద నగరం ఏది ?,Portland is the largest city in the U.S. state...,te,True,0,Portland,NaN,What is the largest city in the state of Oregon?
1,కలరా వ్యాధిని మొదటగా ఏ దేశంలో కనుగొన్నారు ?,"The word cholera is from ""kholera"" from χολή ""...",te,True,99,Indian subcontinent,NaN,In which country was cholera first discovered?
2,కలరా వ్యాధిని మొదటగా ఏ దేశంలో కనుగొన్నారు ?,Since it became widespread in the 19th century...,te,True,451,England,NaN,In which country was cholera first discovered?
3,మొదటి ప్రపంచ యుద్ధం ఎప్పుడు మొదలయింది ?,World War I occurred from 1914 to 1918. In ter...,te,True,26,1914,NaN,When did World War I begin?
4,మొదటి ప్రపంచ యుద్ధం ఎప్పుడు మొదలయింది ?,"World War I (often abbreviated as WWI or WW1),...",te,True,155,28 July 1914,NaN,When did World War I begin?
...,...,...,...,...,...,...,...,...
3006,2011 జనగణన ప్రకారం రెయ్యలగడ్ద గ్రామములో పురుషు...,Reyyalagadda is a village belonging to Gangara...,te,True,378,37,37,"According to the 2011 census, how many males a..."
3007,2011 జనాభా లెక్కల ప్రకారం బూతుమిల్లిపాడు గ్రామ...,Boothumillipadu is a village in Gannavaram man...,te,True,308,433,433,"According to the 2011 census, how many people ..."
3008,2011 జనాభా లెక్కల ప్రకారం మల్లవేముల గ్రామ జనాభ...,Mallavemula is a village belonging to Chagalam...,te,False,-1,1131,1131,What is the population of Mallavem village as ...
3009,2011 నాటికి రష్యా దేశ ప్రధాన మంత్రి ఎవరు?,"Andria Urushadze (; born April 25, 1968) is a ...",te,False,-1,Vladimir Putin,వ్లాదిమిర్ పుతిన్,Who is the Prime Minister of Russia as of 2011?
3010,2011 భారత జనగణన గణాంకాల ప్రకారం గుంటూరు పట్టణ ...,"Guntur district is 11,391 sq. km. Spread over ...",te,False,-1,"743,654","743,654","According to the 2011 census of India, what is..."

## Tokenizer

In [12]:
lang_tokenizer = {AR: nlp_ar_spacy, TE: nlp_te_spacy, KO: nlp_ko_spacy, EN: nlp_en_spacy}
L = {AR: "Arabic", KO: "Korean", TE: "Telegu", EN: "English"}

In [13]:
model_tokenizer = AutoTokenizer.from_pretrained("xlm-roberta-base")
model_tokenizer.tokenize("한국어 형태소를 분석합니다.")

config.json:   0%|          | 0.00/615 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/9.10M [00:00<?, ?B/s]

['▁한국어', '▁형태', '소', '를', '▁분석', '합니다', '.']

# Week 36

## Dataset Check - answer equals substring beginning at answer start

In [ ]:
# remove inconsistencies
# check (answer == substring beginning at answer start)

df_train[(df_train["answerable"] == True) &
         (
            (df_train["answer_start"] + df_train["answer"].str.len() > df_train["context"].str.len()) |
            (
                df_train.apply(
                    lambda row: row["context"][
                        row["answer_start"]:
                        row["answer_start"] + len(row["answer"])
                    ] != row["answer"],
                    axis=1
                )
            )
         )
        ].loc[:,["context","answer","answer_start"]]


# no cases with answer context inconsistency in training split

Empty DataFrame
Columns: [context, answer, answer_start]
Index: []

In [ ]:
df_val[(df_val["answerable"] == True) &
         (
            (df_val["answer_start"] + df_val["answer"].str.len() > df_val["context"].str.len()) |
            (
                df_val.apply(
                    lambda row: row["context"][
                        row["answer_start"]:
                        row["answer_start"] + len(row["answer"])
                    ] != row["answer"],
                    axis=1
                )
            )
         )
        ].loc[:,["context","answer","answer_start"]]


# no cases with answer context inconsistency in validation split

Empty DataFrame
Columns: [context, answer, answer_start]
Index: []

In [ ]:
# True -> 1 && False -> 0

df_train = df_train.replace({True: 1, False: 0})
df_val = df_val.replace({True: 1, False: 0})

/tmp/ipykernel_1824/221756984.py:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_train = df_train.replace({True: 1, False: 0})
/tmp/ipykernel_1824/221756984.py:4: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_val = df_val.replace({True: 1, False: 0})

## Dataset statistics

In [ ]:
def show_ans(df_train,df_val,label=""):
    train_ans_size = df_train[df_train["answerable"] == 1].shape[0]
    train_nonans_size = df_train[df_train["answerable"] == 0].shape[0]

    val_ans_size = df_val[df_val["answerable"] == 1].shape[0]
    val_nonans_size = df_val[df_val["answerable"] == 0].shape[0]

    print(label)
    print("\nTrain count:", df_train.shape[0])
    print("Val count:", df_val.shape[0])

    print("\nAnswerable questions:")
    print("\tTrain:", train_ans_size)
    print("\tVal:", val_ans_size)
    print("Non-answerable questions: ", )
    print ("\tTrain:", train_nonans_size)
    print ("\tVal:", val_nonans_size)

    print("\nAnswerability ratios: ")
    print("\t Train: ", train_ans_size/(train_nonans_size+train_ans_size))
    print("\t Val: ", val_ans_size/(val_ans_size+val_nonans_size))

    print("\nMissing values in train")
    for col in df_train.columns:
      if col == "question_translated": continue
      print(f"\t {col}: {df_train[col].isna().sum()}")

    print("\nMissing values in val")
    for col in df_val.columns:
      if col == "question_translated": continue
      print(f"\t {col}: {df_val[col].isna().sum()}")

    print("\nDuplicates in train:", df_train.duplicated(subset=["question","context"], keep=False).sum())
    print("Duplicates in val:", df_val.duplicated(subset=["question","context"], keep=False).sum())

In [ ]:
show_ans(df_train,df_val,label="Overall")

Overall

Train count: 15343
Val count: 3011

Answerable questions:
	Train: 13962
	Val: 2313
Non-answerable questions:
	Train: 1381
	Val: 698

Answerability ratios:
	 Train:  0.9099915270807535
	 Val:  0.7681833277980737

Missing values in train
	 question: 0
	 context: 0
	 lang: 0
	 answerable: 0
	 answer_start: 0
	 answer: 0
	 answer_inlang: 15093

Missing values in val
	 question: 0
	 context: 0
	 lang: 0
	 answerable: 0
	 answer_start: 0
	 answer: 0
	 answer_inlang: 2511

Duplicates in train: 34
Duplicates in val: 0

In [ ]:
# filter for Arabic, Korean and Telegu
df_train_ar = df_train[df_train["lang"] == "ar"]
df_val_ar = df_val[df_val["lang"] == "ar"]

df_train_ko = df_train[df_train["lang"] == "ko"]
df_val_ko = df_val[df_val["lang"] == "ko"]

df_train_te = df_train[df_train["lang"] == "te"]
df_val_te = df_val[df_val["lang"] == "te"]

# check for duplicates pairs (question,context)


# combine ar, ko and te
df_train_mlangs = pd.concat([df_train_ar,df_train_ko,df_train_te])
df_val_mlangs = pd.concat([df_val_ar,df_val_ko,df_val_te])

In [ ]:
show_ans(df_train_ar,df_val_ar, "Arabic")

Arabic

Train count: 2558
Val count: 415

Answerable questions:
	Train: 2303
	Val: 363
Non-answerable questions:
	Train: 255
	Val: 52

Answerability ratios:
	 Train:  0.900312744331509
	 Val:  0.8746987951807229

Missing values in train
	 question: 0
	 context: 0
	 lang: 0
	 answerable: 0
	 answer_start: 0
	 answer: 0
	 answer_inlang: 2558

Missing values in val
	 question: 0
	 context: 0
	 lang: 0
	 answerable: 0
	 answer_start: 0
	 answer: 0
	 answer_inlang: 415

Duplicates in train: 0
Duplicates in val: 0

In [ ]:
show_ans(df_train_ko,df_val_ko, "Korean")

Korean

Train count: 2422
Val count: 356

Answerable questions:
	Train: 2359
	Val: 337
Non-answerable questions:
	Train: 63
	Val: 19

Answerability ratios:
	 Train:  0.9739884393063584
	 Val:  0.9466292134831461

Missing values in train
	 question: 0
	 context: 0
	 lang: 0
	 answerable: 0
	 answer_start: 0
	 answer: 0
	 answer_inlang: 2422

Missing values in val
	 question: 0
	 context: 0
	 lang: 0
	 answerable: 0
	 answer_start: 0
	 answer: 0
	 answer_inlang: 356

Duplicates in train: 20
Duplicates in val: 0

In [ ]:
show_ans(df_train_te,df_val_te, "Telugu")

Telugu

Train count: 1355
Val count: 384

Answerable questions:
	Train: 1310
	Val: 291
Non-answerable questions:
	Train: 45
	Val: 93

Answerability ratios:
	 Train:  0.966789667896679
	 Val:  0.7578125

Missing values in train
	 question: 0
	 context: 0
	 lang: 0
	 answerable: 0
	 answer_start: 0
	 answer: 0
	 answer_inlang: 1305

Missing values in val
	 question: 0
	 context: 0
	 lang: 0
	 answerable: 0
	 answer_start: 0
	 answer: 0
	 answer_inlang: 284

Duplicates in train: 0
Duplicates in val: 0

In [ ]:
show_ans(df_train_mlangs,df_val_mlangs, "Ar + Ko + Te")

Ar + Ko + Te

Train count: 6335
Val count: 1155

Answerable questions:
	Train: 5972
	Val: 991
Non-answerable questions:
	Train: 363
	Val: 164

Answerability ratios:
	 Train:  0.9426992896606157
	 Val:  0.858008658008658

Missing values in train
	 question: 0
	 context: 0
	 lang: 0
	 answerable: 0
	 answer_start: 0
	 answer: 0
	 answer_inlang: 6285

Missing values in val
	 question: 0
	 context: 0
	 lang: 0
	 answerable: 0
	 answer_start: 0
	 answer: 0
	 answer_inlang: 1055

Duplicates in train: 20
Duplicates in val: 0

## Tokenization statistics

In [ ]:

languages = {
    "Arabic":  (nlp_ar_spacy, df_train_ar, df_val_ar),
    "Korean":  (nlp_ko_spacy, df_train_ko, df_val_ko),
    "Telugu":  (nlp_te_spacy, df_train_te, df_val_te),
}

def token_lengths(nlp, series):
    return [len(doc) for doc in nlp.pipe(series.astype(str))]

lengths = {}
for lang, (nlp, df_train, df_val) in languages.items():
    lengths[(lang, "question")] = {}
    lengths[(lang, "context")] = {}
    for split, df in [("Train", df_train), ("Val", df_val)]:
        for field in ["question", "context"]:
            lengths[(lang, field)][split] = token_lengths(nlp, df[field])

lengths[("Overall", "question")] = {}
lengths[("Overall", "context")] = {}
for split in ["Train", "Val"]:
    for field in ["question", "context"]:
        lengths[("Overall", field)][split] = sum(
            (lengths[(lang, field)][split] for lang in languages), []
        )

rows = []
for (lang, field), vals in lengths.items():
    q1_train, med_train, q3_train = np.percentile(vals["Train"], [25, 50, 75])
    q1_val, med_val, q3_val = np.percentile(vals["Val"], [25, 50, 75])
    rows.append({
        "Language": lang,
        "Field": field.capitalize(),
        "Median_Train": med_train,
        "Q1_Train": q1_train,
        "Q3_Train": q3_train,
        "IQR_Train": q3_train - q1_train,
        "Median_Val": med_val,
        "Q1_Val": q1_val,
        "Q3_Val": q3_val,
        "IQR_Val": q3_val- q1_val
    })

summary = pd.DataFrame(rows)
display(summary)

,Language,Field,Median_Train,Q1_Train,Q3_Train,IQR_Train,Median_Val,Q1_Val,Q3_Val,IQR_Val
0,Arabic,Question,7.0,6.0,9.0,3.0,7.0,6.00,9.0,3.00
1,Arabic,Context,100.5,67.0,145.0,78.0,99.0,67.50,142.5,75.00
2,Korean,Question,6.0,5.0,7.0,2.0,6.0,5.00,7.0,2.00
3,Korean,Context,101.0,69.0,143.0,74.0,98.0,60.75,146.0,85.25
4,Telugu,Question,6.0,5.0,8.0,3.0,7.0,6.00,8.0,2.00
5,Telugu,Context,94.0,62.0,133.5,71.5,121.0,89.50,162.0,72.50
6,Overall,Question,6.0,5.0,8.0,3.0,7.0,6.00,8.0,2.00
7,Overall,Context,100.0,67.0,142.0,75.0,107.0,71.50,151.5,80.00

In [ ]:
# most commom tokens for each language

lang_tokenizer = {AR: nlp_ar_spacy, TE: nlp_te_spacy, KO: nlp_ko_spacy, EN: nlp_en_spacy}
L = {AR: "Arabic", KO: "Korean", TE: "Telegu", EN: "English"}

def most_commom_token_lang(df_train_lang,lang):
  tokens = [token.text for doc in lang_tokenizer[lang].pipe(df_train_lang["question"].astype(str)) for token in doc]
  cnt = Counter(tokens)
  most_commom = cnt.most_common(5)
  print("Most commom tokens in", L[lang]+":")
  for i in range(5):
    token,freq = most_commom[i]
    print(f"{i+1}. {token} ({freq}) -> {translate_cached(token,lang,EN)}") # remove # from beginning of token

  print("Total tokens in train:", len(tokens))
  print()


most_commom_token_lang(df_train_ar,AR)
most_commom_token_lang(df_train_ko,KO)
most_commom_token_lang(df_train_te,TE)

Most commom tokens in Arabic:
1. ؟ (2556) -> Seeker?
2. في (593) -> at
3. من (586) -> Of
4. متى (535) -> When
5. ما (442) -> public health kind of influence and impact. This is my first project after my Master in public health
Total tokens in train: 19079

Most commom tokens in Korean:
1. ? (2419) -> User Guide
2. 가장 (527) -> the most
3. 무엇인가 (496) -> LAW OF KARMA WORK?
4. 언제 (336) -> WHEN
5. 몇 (234) -> Few
Total tokens in train: 14323

Most commom tokens in Telegu:
1. ? (1355) -> ?
2. ఎవరు (274) -> Who
3. ఏది (192) -> Which
4. ఎన్ని (165) -> How many
5. ఎప్పుడు (154) -> When
Total tokens in train: 9109

## Answerability metrics

In [ ]:
# evaluation metrics answerability

def answerability_scores(annotated, predicted):
    TP = TN = FP = FN = 0
    for a, p in zip(annotated, predicted):
        if a == 1:
          if p == 1: TP += 1
          else: FN += 1
        else:
          if p == 1: FP += 1
          else: TN += 1

    precision_ans = TP / (TP + FP) if TP + FP else 0.0
    recall_ans = TP / (TP + FN) if TP + FN else 0.0
    f1_ans = (2*precision_ans*recall_ans) / (precision_ans + recall_ans) if precision_ans + recall_ans else 0.0

    precision_unans = TN / (TN + FN) if TN + FN else 0.0
    recall_unans = TN / (TN + FP) if TP + FN else 0.0
    f1_unans = (2*precision_unans*recall_unans) / (precision_unans + recall_unans) if precision_unans + recall_unans else 0.0

    accuracy = (TP+TN) / (TP+TN+FP+FN) if TP+TN+FP+FN else 0.0

    return precision_ans, recall_ans, f1_ans, precision_unans, recall_unans, f1_unans, accuracy

def evaluate_answerability(name, annotated, predicted):
  precision_ans, recall_ans, f1_ans, precision_unans, recall_unans, f1_unans, accuracy = answerability_scores(annotated, predicted)
  result = {
      "model": name,

      "accuracy": accuracy,

      "macro_avg_f1": (f1_ans + f1_unans)/2,

      "precision_answerable": precision_ans,
      "recall_answerable": recall_ans,
      "f1_answerable": f1_ans,

      "precision_unanswerable": precision_unans,
      "recall_unanswerable": recall_unans,
      "f1_unanswerable": f1_unans,
  }
  return result

## Majority-class baseline

In [ ]:
# majority-class baseline
def majority_class_baseline_predict(df_train_lang):
  return df_train_lang["answerable"].mode()[0]

mcb_ar_metrics = evaluate_answerability("majority class baseline Arabic", df_val_ar["answerable"], pd.Series([majority_class_baseline_predict(df_train_mlangs)] * df_val_ar.shape[0]))
mcb_ko_metrics = evaluate_answerability("majority class baseline Korean", df_val_ko["answerable"], pd.Series([majority_class_baseline_predict(df_train_mlangs)] * df_val_ko.shape[0]))
mcb_te_metrics = evaluate_answerability("majority class baseline Telegu", df_val_te["answerable"], pd.Series([majority_class_baseline_predict(df_train_mlangs)] * df_val_te.shape[0]))
mcb_mlangs_metrics = evaluate_answerability("majority class baseline Overall", df_val_mlangs["answerable"], pd.Series([majority_class_baseline_predict(df_train_mlangs)] * df_val_mlangs.shape[0]))

mcb_metrics = [mcb_ar_metrics,mcb_ko_metrics,mcb_te_metrics,mcb_mlangs_metrics]

pd.DataFrame(mcb_metrics)

,model,accuracy,macro_avg_f1,precision_answerable,recall_answerable,f1_answerable,precision_unanswerable,recall_unanswerable,f1_unanswerable
0,majority class baseline Arabic,0.874699,0.466581,0.874699,1.0,0.933162,0.0,0.0,0.0
1,majority class baseline Korean,0.946629,0.486291,0.946629,1.0,0.972583,0.0,0.0,0.0
2,majority class baseline Telegu,0.757812,0.431111,0.757812,1.0,0.862222,0.0,0.0,0.0
3,majority class baseline Overall,0.858009,0.461789,0.858009,1.0,0.923579,0.0,0.0,0.0

## Deterministic rule-based classifier

In [ ]:
# deterministic rule-based classifier

def overlap_rule(question_, context, threshold = 0.20):
  overlap = set(question_) & set(context)
  return len(overlap)/len(set(context)) >= threshold

def number_overlap_rule(question, context):
  question_nums = [int(n) for n in re.findall(r'\d+', question)]
  context_nums = [int(n) for n in re.findall(r'\d+', context)]

  if len(question_nums) == 0:
    return True

  for qn in question_nums:
    for cn in context_nums:
      if abs(qn-cn) <= qn*0.1:
        return True
  return False

question_words = {
    AR: {"من": "who", "متى": "when", "أين": "where", "كم عدد": "how many"},
    KO: {"누구": "who", "언제": "when", "어디": "where", "얼마나": "how many"},
    TE: {"ఎవరు": "who", "ఎప్పుడు": "when", "ఎక్కడ": "where", "ఎన్ని": "how many"}
}

months = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"]
week_days = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]

# see presence of each of these question words in the question train dataset
def check_context(qword,context):
  context_nums = [int(n) for n in re.findall(r'\d+', context)]
  if qword == "when":
    if len(context_nums) > 0 and any(w in context for w in months+week_days):
      return True
    else:
      return False
  elif qword == "how many":
    if len(context_nums) > 0:
      return True
    else:
      return False
  return True

def qw_rule(lang, question, context):
  count_qws = 0
  for qword in question_words[lang].keys():
    if qword in question:
      count_qws += 1
      if not check_context(qword,context):
        return False
  if count_qws > 1:
    return False
  return True

def rule_classifier(question,question_translated,context):
  cnt = (
      (question.count("?") + question.count("؟") == 1)
      + overlap_rule(question_translated,context)
      + number_overlap_rule(question,context)
      + qw_rule(AR,question,context) + qw_rule(KO,question,context) + qw_rule(TE,question,context) # at least two will evaluate to 1
  )
  if cnt >= 6:
    return 1
  return 0

rbc_ar_metrics = evaluate_answerability("rule based classifier Arabic", df_val_ar["answerable"], df_val_ar.apply(lambda row: rule_classifier(row['question'], row['question_translated'], row['context']), axis=1))
rbc_ko_metrics = evaluate_answerability("rule based classifier Korean", df_val_ko["answerable"], df_val_ko.apply(lambda row: rule_classifier(row['question'], row['question_translated'], row['context']), axis=1))
rbc_te_metrics = evaluate_answerability("rule based classifier Telegu", df_val_te["answerable"], df_val_te.apply(lambda row: rule_classifier(row['question'],row['question_translated'], row['context']), axis=1))
rbc_mlangs_metrics = evaluate_answerability("rule based classifier Overall", df_val_mlangs["answerable"], df_val_mlangs.apply(lambda row: rule_classifier(row['question'], row['question_translated'], row['context']), axis=1))

rbc_metrics = [rbc_ar_metrics,rbc_ko_metrics,rbc_te_metrics,rbc_mlangs_metrics]

pd.DataFrame(rbc_metrics)

,model,accuracy,macro_avg_f1,precision_answerable,recall_answerable,f1_answerable,precision_unanswerable,recall_unanswerable,f1_unanswerable
0,rule based classifier for Arabic,0.848193,0.474208,0.873134,0.966942,0.917647,0.076923,0.019231,0.030769
1,rule based classifier for Korean,0.873596,0.466267,0.942424,0.922849,0.932534,0.000000,0.000000,0.000000
2,rule based classifier for Telegu,0.736979,0.424288,0.752660,0.972509,0.848576,0.000000,0.000000,0.000000
3,rule based classifier for Ar+Ko+Te,0.819048,0.454954,0.852888,0.953582,0.900429,0.021277,0.006098,0.009479

# Week 37

In [18]:
df_train = df_train[
    df_train["lang"].isin(["ar", "ko", "te"])
]

df_val = df_val[
    df_val["lang"].isin(["ar", "ko", "te"])
]

## BIO Labels

In [19]:
# lang_tokenizer = {AR: nlp_ar_spacy, TE: nlp_te_spacy, KO: nlp_ko_spacy, EN: nlp_en_spacy}
# L = {AR: "Arabic", KO: "Korean", TE: "Telegu", EN: "English"}

In [20]:
def is_answer_valid(answer, answer_start, context):
  return not (not answer or answer_start is None or answer_start < 0)

def bio_labeller(context, answer, answer_start):
    document = lang_tokenizer[EN](context)

    tokens = [token.text for token in document]
    offsets = [
        (token.idx, token.idx + len(token.text))
        for token in document
    ]

    labels = ["O"] * len(tokens)

    if (
        not isinstance(answer, str)
        or answer == ""
        or answer_start is None
        or pd.isna(answer_start)
        or int(answer_start) < 0
    ):
        return tokens, labels

    answer_start = int(answer_start)
    answer_end = answer_start + len(answer)

    covered_token_indices = [
        index
        for index, (token_start, token_end) in enumerate(offsets)
        if token_start < answer_end and token_end > answer_start
    ]

    labels[covered_token_indices[0]] = "B"

    for index in covered_token_indices[1:]:
        labels[index] = "I"

    return tokens, labels

def bio_labeller_row(row):
  context = row["context"]
  answer = row["answer"]
  answer_start = row["answer_start"]

  tokens, labels = bio_labeller(context, answer, answer_start)

  return labels

def tokenizer_row(row):
  context = row["context"]
  answer = row["answer"]
  answer_start = row["answer_start"]

  tokens, labels = bio_labeller(context, answer, answer_start)

  return tokens

In [21]:
df_train["sequence_labels"] = df_train.apply(
    bio_labeller_row,
    axis=1,
)

df_train["context_tokens"] = df_train.apply(
    tokenizer_row,
    axis=1,
)

df_val["sequence_labels"] = df_val.apply(
    bio_labeller_row,
    axis=1,
)

df_val["context_tokens"] = df_val.apply(
    tokenizer_row,
    axis=1,
)

df_train.head()

/tmp/ipykernel_607/3836319473.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_train["sequence_labels"] = df_train.apply(
/tmp/ipykernel_607/3836319473.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_train["context_tokens"] = df_train.apply(
/tmp/ipykernel_607/3836319473.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_val["sequence_labels"] = df_val.apply(
/tmp/ipykernel_607/3836319473.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_val["context_tokens"] = df_val.apply(

,question,context,lang,answerable,answer_start,answer,answer_inlang,question_translated,sequence_labels,context_tokens
4792,30년 전쟁의 승자는 누구인가?,The conflict between France and Spain continue...,ko,True,21,France,NaN,Who is the winner of the Thirty Years' War?,"[O, O, O, B, O, O, O, O, O, O, O, O, O, O, O, ...","[The, conflict, between, France, and, Spain, c..."
4793,엑스선은 누가 발견하였는가?,"X-rays make up X-radiation, a form of electrom...",ko,True,503,Wilhelm Röntgen,NaN,Who discovered the X-ray?,"[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ...","[X, -, rays, make, up, X, -, radiation, ,, a, ..."
4794,아테네에서 언제 가장 최근의 올림픽이 올렸나요?,"In 2022, Beijing will become the first-ever ci...",ko,True,188,2004,NaN,When was the last time the Olympics were held ...,"[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ...","[In, 2022, ,, Beijing, will, become, the, firs..."
4795,세상에서 가장 오래된 방송사는 무엇인가?,The British Broadcasting Corporation (BBC) is ...,ko,True,4,British Broadcasting Corporation (BBC),NaN,What's the oldest broadcaster in the world?,"[O, B, I, I, I, I, I, O, O, O, O, O, O, O, O, ...","[The, British, Broadcasting, Corporation, (, B..."
4796,팔레스타인 수도는 어딘가요?,"Palestine ( '), officially the State of Palest...",ko,True,205,Jerusalem,NaN,Where is the Palestinian capital?,"[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ...","[Palestine, (, ', ), ,, officially, the, State..."

## Automatic checks

In [15]:
def answers_at_0():
  return df_train[
      df_train["answer_start"] == 0
  ]

def multi_token_answers():
  return df_train[
    df_train["sequence_labels"].apply(
        lambda labels: sum(
            label in {"B", "I"} for label in labels
        ) > 1
    )
]

import unicodedata

def is_punctuation(character):
  return (
      character is not None
      and unicodedata.category(character).startswith("P")
  )

def has_adjacent_punctuation(row):
  context = row["context"]
  answer = row["answer"]
  answer_start = row["answer_start"]

  answer_start = int(answer_start)

  if answer_start < 0:
      return False

  answer_end = answer_start + len(answer)

  character_before = (
      context[answer_start - 1]
      if answer_start > 0
      else None
  )

  character_after = (
      context[answer_end]
      if answer_end < len(context)
      else None
  )

  return (
      is_punctuation(character_before)
      or is_punctuation(character_after)
  )

def answers_adjacent_to_punctuation():
  return df_train[
      df_train.apply(
          has_adjacent_punctuation,
          axis=1,
      )
  ]

def unanswerable_answers():
  return df_train[
      df_train["answerable"] == False
  ]

In [ ]:
def test_answer_at_0():
  rows = answers_at_0().sample(5)

  for row in rows.itertuples():
    sequence_labels = row.sequence_labels

    assert sequence_labels[0] == "B"

  print("All tests on answers at 0 passed.")

def test_multi_token_answers():
  rows = multi_token_answers().sample(5)

  for row in rows.itertuples():
    sequence_labels = row.sequence_labels

    assert sequence_labels.count("B") + sequence_labels.count("I") > 1

  print("All tests on multi-token answers passed.")

def test_answers_adjacent_to_punctuation():
  rows = answers_adjacent_to_punctuation().sample(5)

  for row in rows.itertuples():
    answer = row.answer
    answer_start = row.answer_start
    answer_end = answer_start + len(answer)
    context = row.context

    char_before = None
    char_after = None
    if answer_start > 0:
      char_before = context[answer_start - 1]

    if answer_end < len(context):
      char_after = context[answer_end]

    assert (
        is_punctuation(char_before)
        or is_punctuation(char_after)
    )
  print("All tests on answers adjacent to punctuations passed.")

def test_unanswerable_answers():
  rows = unanswerable_answers().sample(5)

  for row in rows.itertuples():
    answer_start = row.answer_start
    sequence_labels = row.sequence_labels

    assert answer_start == -1
    assert sequence_labels.count("B") + sequence_labels.count("I") == 0

  print("All tests on unanswerable answers passed.")

test_answer_at_0()
test_multi_token_answers()
test_answers_adjacent_to_punctuation()
test_unanswerable_answers()

All tests on answers at 0 passed.
All tests on multi-token answers passed.
All tests on answers adjacent to punctuations passed.
All tests on unanswerable answers passed.

## Question-conditioned sequence labeller

In [22]:
LABELS = ["O", "B", "I"]
LABEL_TO_ID = {"O": 0, "B": 1, "I": 2}

QUESTION_WORDS = {
    "who",
    "whom",
    "whose",
    "what",
    "which",
    "when",
    "where",
    "why",
    "how",
}

def spacy_tokenize(text, lang):
    document = lang_tokenizer[lang].make_doc(text)

    return [
        token.text
        for token in document
        if not token.is_space
    ]
def normalize_token(token):
    if hasattr(token, "text"):
        token = token.text

    return token.strip().casefold()

def token_features(question_tokens, context_tokens, index):
    token = context_tokens[index]
    normalized_token = normalize_token(token)

    question_set = {
        normalize_token(question_token)
        for question_token in question_tokens
        if normalize_token(question_token)
    }

    question_words = question_set & QUESTION_WORDS

    features = {
        "bias": 1.0,
        "token.lower": normalized_token,
        "token.prefix2": normalized_token[:2],
        "token.suffix2": normalized_token[-2:],
        "token.suffix3": normalized_token[-3:],
        "token.isdigit": normalized_token.isdigit(),
        "token.istitle": token.istitle(),
        "token.isupper": token.isupper(),
        "token_in_question": normalized_token in question_set,
        "relative_position": (
            index / max(len(context_tokens) - 1, 1)
        ),
    }

    if index == 0:
        features["BOS"] = True
    else:
        previous = normalize_token(context_tokens[index - 1])

        features["previous.lower"] = previous
        features["previous_in_question"] = (
            previous in question_set
        )

    if index == len(context_tokens) - 1:
        features["EOS"] = True
    else:
        following = normalize_token(context_tokens[index + 1])

        features["next.lower"] = following
        features["next_in_question"] = (
            following in question_set
        )

    for question_word in question_words:
        features[f"question_word={question_word}"] = 1.0

    return features

def featurize_split(data):
    features, labels, lengths = [], [], []

    for row in data.itertuples():
      question = row.question
      context = row.context
      sequence_labels = row.sequence_labels
      tokens = row.context_tokens

      question_doc = lang_tokenizer[EN](translate(question, row.lang, EN))
      question_tokens = [token.text for token in question_doc]
      lengths.append(len(tokens))
      features.extend(token_features(question_tokens, tokens, index) for index in range(len(tokens)))
      labels.extend(sequence_labels)

    return features, labels, lengths

def split_by_lengths(values, lengths):
    sequences = []
    offset = 0
    for length in lengths:
        sequences.append(list(values[offset:offset + length]))
        offset += length
    assert offset == len(values)
    return sequences

In [23]:
from sklearn.feature_extraction import DictVectorizer
from sklearn.linear_model import SGDClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, f1_score
import joblib

if not os.path.exists("./models"):
  vectorizer = DictVectorizer(sparse=True)

  train_features, train_labels, train_lengths = featurize_split(df_train)

  X_train = vectorizer.fit_transform(train_features)

  token_classifier = SGDClassifier(
      loss="log_loss",
      alpha=1e-5,
      class_weight="balanced",
      max_iter=30,
      random_state=42,
  )
  token_classifier.fit(X_train, train_labels)
else:
  saved_model = joblib.load(
      "models/week37_sequence_labeller.joblib"
  )

  vectorizer = saved_model["vectorizer"]
  token_classifier = saved_model["classifier"]

In [24]:
validation_features, validation_labels, validation_lengths = featurize_split(df_val)

X_validation = vectorizer.transform(validation_features)

independent_flat = token_classifier.predict(X_validation)
independent_predictions = split_by_lengths(
    independent_flat, validation_lengths
)

In [25]:
def bio_spans(labels):
    spans = set()
    start = None

    for index, label in enumerate(list(labels) + ["O"]):
      if label == "B":
        if start is not None:
            spans.add((start, index))
        start = index

      elif label == "I":
        if start is None:
            start = index

      elif label == "O" and start is not None:
        spans.add((start, index))
        start = None

    return spans


def span_scores(gold_sequences, predicted_sequences):
    predicted_count = gold_count = matches = 0
    for gold, predicted in zip(gold_sequences, predicted_sequences):
        gold_spans = bio_spans(gold)
        predicted_spans = bio_spans(predicted)
        gold_count += len(gold_spans)
        predicted_count += len(predicted_spans)
        matches += len(gold_spans & predicted_spans)

    precision = matches / predicted_count if predicted_count else 0.0
    recall = matches / gold_count if gold_count else 0.0
    f1 = 2 * precision * recall / (precision + recall) if precision + recall else 0.0
    return precision, recall, f1


def evaluate_sequences(name, gold_sequences, predicted_sequences):
    gold_flat = np.concatenate(gold_sequences)
    predicted_flat = np.concatenate(predicted_sequences)

    # B and I are both positive; O is negative.
    gold_answer_tokens = np.isin(gold_flat, ["B", "I"])
    predicted_answer_tokens = np.isin(
        predicted_flat, ["B", "I"]
    )

    exact_matches = [
        bio_spans(gold) == bio_spans(predicted)
        for gold, predicted in zip(
            gold_sequences,
            predicted_sequences,
        )
    ]

    unanswerable = [
        len(bio_spans(gold)) == 0
        for gold in gold_sequences
    ]

    return {
        "model": name,
        "token_accuracy": accuracy_score(
            gold_flat,
            predicted_flat,
        ),
        "answer_token_f1": f1_score(
            gold_answer_tokens,
            predicted_answer_tokens,
            zero_division=0,
        ),
        "exact_span_match": np.mean(exact_matches),
        "unanswerable_exact_match": np.mean([
            exact
            for exact, is_unanswerable in zip(
                exact_matches,
                unanswerable,
            )
            if is_unanswerable
        ]),
    }

In [ ]:
validation_gold = split_by_lengths(
    validation_labels, validation_lengths
)

always_o_predictions = [
    ["O"] * length
    for length in validation_lengths
]

print(evaluate_sequences(
    "Always O",
    validation_gold,
    always_o_predictions,
))

print(evaluate_sequences(
    "Question-conditioned classifier",
    validation_gold,
    independent_predictions,
))

{'model': 'Always O', 'token_accuracy': 0.9754622281326413, 'answer_token_f1': 0.0, 'exact_span_match': np.float64(0.141991341991342), 'unanswerable_exact_match': np.float64(1.0)}
{'model': 'Question-conditioned classifier', 'token_accuracy': 0.9454978336407704, 'answer_token_f1': 0.18915701763878368, 'exact_span_match': np.float64(0.04242424242424243), 'unanswerable_exact_match': np.float64(0.10975609756097561)}

In [ ]:
confusion = confusion_matrix(
    validation_labels,
    independent_flat,
    labels=LABELS,
)

pd.DataFrame(confusion, index=LABELS, columns=LABELS)

        O     B     I
O  131499  3036  1899
B     523   429    39
I    2035    91   315

# Week 38

## Common setup

### Training and validation questions

In [ ]:
# df_train.drop_duplicates(subset=["question"])
df_train_ko = df_train[df_train["lang"] == "ko"].copy()

# df_val.drop_duplicates(subset=["question"])
df_val_ko = df_val[df_val["lang"] == "ko"].copy()

ko_train_questions = df_train_ko["question"].tolist()

ko_val_questions = df_val_ko["question"].tolist()

### Tokenization

In [ ]:
# nlp_ko_spacy = spacy.load("ko_core_news_sm")

def tokenize(question):
  return model_tokenizer.tokenize(question)

tokenize(ko_train_questions[1])

['▁', '엑스', '선', '은', '▁누가', '▁발견', '하였', '는', '가', '?']

### Vocabulary
Unknown strategy:
1. tokens occurring at least twice remain in the vocabulary;
2. tokens occurring only once become \<UNK>;
3. unseen validation tokens also become \<UNK>.

In [ ]:
BOS = "<BOS>"
EOS = "<EOS>"
UNK = "<UNK>"

df_train_ko["question_tokenized"] = df_train_ko["question"].apply(tokenize)
df_val_ko["question_tokenized"] = df_val_ko["question"].apply(tokenize)

train_questions_tokenized = df_train_ko["question_tokenized"].tolist()

val_questions_tokenized = df_val_ko["question_tokenized"].tolist()

token_counts = Counter(
    token
    for question in train_questions_tokenized
    for token in question
)

vocabulary = {
    token
    for token, count in token_counts.items()
    if count >= 2
}

prediction_vocabulary = set(vocabulary) | {
    UNK,
    EOS,
}

In [ ]:
def replace_unknown_tokens(tokens):
    return [
        token if token in vocabulary else "<UNK>"
        for token in tokens
    ]

train_sequences = [
    replace_unknown_tokens(tokens)
    for tokens in train_questions_tokenized
]

# ADDED
val_sequences = [
    replace_unknown_tokens(tokens)
    for tokens in val_questions_tokenized
]

df_train_ko["question_tokenized"] = df_train_ko["question_tokenized"].apply(replace_unknown_tokens)
df_val_ko["question_tokenized"] = df_val_ko["question_tokenized"].apply(replace_unknown_tokens)

df_train_ko.head()

,question,context,lang,answerable,answer_start,answer,answer_inlang,question_tokenized
4792,30년 전쟁의 승자는 누구인가?,The conflict between France and Spain continue...,ko,True,21,France,None,"[▁30, 년, ▁전쟁, 의, ▁승, 자는, ▁누구, 인가, ?]"
4793,엑스선은 누가 발견하였는가?,"X-rays make up X-radiation, a form of electrom...",ko,True,503,Wilhelm Röntgen,None,"[▁, 엑스, 선, 은, ▁누가, ▁발견, 하였, 는, 가, ?]"
4794,아테네에서 언제 가장 최근의 올림픽이 올렸나요?,"In 2022, Beijing will become the first-ever ci...",ko,True,188,2004,None,"[▁아, 테, 네, 에서, ▁언제, ▁가장, ▁최근, 의, ▁, 올림픽, 이, ▁올..."
4795,세상에서 가장 오래된 방송사는 무엇인가?,The British Broadcasting Corporation (BBC) is ...,ko,True,4,British Broadcasting Corporation (BBC),None,"[▁세상, 에서, ▁가장, ▁오래, 된, ▁방송, 사는, ▁무엇인가, ?]"
4796,팔레스타인 수도는 어딘가요?,"Palestine ( '), officially the State of Palest...",ko,True,205,Jerusalem,None,"[▁팔, 레, 스타, 인, ▁수도, 는, ▁어, 딘, 가요, ?]"

In [ ]:
print("Number of tokens: ", len(token_counts.keys()))
print("Number of tokens with just one occurrence: ",len([cnt for _,cnt in token_counts.items() if cnt < 2]))
print("Size of prediction vocabulary:", len(prediction_vocabulary))

Number of tokens:  2223
Number of tokens with just one occurrence:  697
Size of prediction vocabulary: 1528


### NGram model

In [ ]:
class NGram:
    def __init__(self, _N, _ALPHA=0.1):
        self.N = _N
        self.ALPHA = _ALPHA
        self.gram_counts = Counter()
        self.context_counts = Counter()

    def train(self, train_sequences):
        for tokens in train_sequences:
            padded_tokens = [BOS]*(self.N-1) + [*tokens, EOS]

            for index in range(self.N-1, len(padded_tokens)):
                context = tuple(
                    padded_tokens[index - (self.N-1) + i]
                    for i in range(self.N-1)
                )

                current_token = padded_tokens[index]

                n_gram = tuple(
                    context[i] if i<self.N-1 else current_token for i in range(self.N)
                )

                self.gram_counts[n_gram] += 1
                self.context_counts[context] += 1

    def model_probability(self, context, token, smoothing="add-k"):
        if len(context) != self.N-1:
          return None

        context = tuple(context)
        ngram = context + (token,)

        if smoothing == "laplace":
            return (self.gram_counts[ngram] + 1) / (self.context_counts[context] + len(prediction_vocabulary))
        elif smoothing == "add-k":
            return (self.gram_counts[ngram] + self.ALPHA) / (self.context_counts[context] + self.ALPHA * len(prediction_vocabulary))
        else:
            raise Exception("Unknown smoothing method")

    def question_log_probability(self, question, smoothing="add-k"):
        tokens = tokenize(question)
        tokens = replace_unknown_tokens(tokens)

        padded =  [BOS]*(self.N-1) + [*tokens, EOS]

        log_probability = 0.0
        for i in range(self.N-1, len(padded)):
            probability = self.model_probability(
                [padded[i - (self.N-1) + j] for j in range(self.N-1)],
                padded[i],
                smoothing
            )
            log_probability += math.log(probability)

        # Includes EOS, but not the three BOS tokens
        predicted_token_count = len(tokens) + 1
        return log_probability, predicted_token_count

    def question_perplexity(self, question, smoothing="add-k"):
        log_probability, token_count = self.question_log_probability(
            question,
            smoothing
        )
        return math.exp(-log_probability / token_count)

    def sample(self,max_length=50, smoothing="add-k"):
      context = [BOS]*(self.N-1)
      sentence = []
      random.seed(42)
      sample_vocabulary = [token for token in prediction_vocabulary if token != "<UNK>"]
      for _ in range(max_length):
        probs = []

        for token in sample_vocabulary:
            if token == "<UNK>":
              continue
            p = self.model_probability(context, token, smoothing)
            probs.append(p)

        next_token = random.choices(
            sample_vocabulary,
            weights=probs,
            k=1
        )[0]

        if next_token == EOS:
            break

        sentence.append(next_token)

        if self.N > 1:
          context = context[1:] + [next_token]

      return " ".join(sentence)

    def highest_lowest_perplexity(self, data, model, smoothing="add-k"):
      question_scores = [
          {
              "model": model,
              "question": row.question,
              "question_tokenized": row.question_tokenized,
              "perplexity": self.question_perplexity(row.question, smoothing),
          }
          for row in data.itertuples()
      ]

      question_scores = pd.DataFrame(question_scores)

      lowest = question_scores.nsmallest(5, "perplexity").copy()
      highest = question_scores.nlargest(5, "perplexity").copy()

      for table in (lowest, highest):
          table["translation_en"] = table["question"].apply(
              lambda question: translate(question, KO, EN)
          )

      return (
          lowest, highest, question_scores["perplexity"].mean(),
          question_scores["perplexity"].min(), question_scores["perplexity"].max(),
          question_scores["perplexity"].median()
      )

## Unigram

In [ ]:
unigram_model = NGram(1)
unigram_model.train(train_sequences)

In [ ]:
probability = unigram_model.model_probability(
    [],
    "대한민국의",
    "laplace"
)

print(probability)

2.999760019198464e-05

In [ ]:
unigram_lowest, unigram_highest, unigram_mean_perplexity, unigram_min_perplexity, unigram_max_perplexity, unigram_median_perplexity = unigram_model.highest_lowest_perplexity(df_val_ko, "unigram")
unigram_metrics = {
    "model": "unigram",
    "average_perplexity": unigram_mean_perplexity,
    "median_perplexity": unigram_median_perplexity,
    "min_perplexity": unigram_min_perplexity,
    "max_perplexity": unigram_max_perplexity
}

## Bigram

In [ ]:
bigram_model = NGram(2)
bigram_model.train(train_sequences)

In [ ]:
bigram_lowest, bigram_highest, bigram_mean_perplexity, bigram_min_perplexity, bigram_max_perplexity, bigram_median_perplexity = bigram_model.highest_lowest_perplexity(df_val_ko, "bigram")
bigram_metrics = {
    "model": "bigram",
    "average_perplexity": bigram_mean_perplexity,
    "median_perplexity": bigram_median_perplexity,
    "min_perplexity": bigram_min_perplexity,
    "max_perplexity": bigram_max_perplexity
}

In [ ]:
probability = bigram_model.model_probability(
    [BOS],
    "대한민국의",
)

print(probability)

3.883796799751437e-05

In [ ]:
sample = bigram_model.sample()
print(sample)
print(translate(sample,KO,EN))

▁지 어 났 나 브리 ▁고려 멕 ▁만든 ▁삼 ▁제일 > ▁2016 직 ▁광 시는 ▁대전 ▁외 엘 ▁공격 잉 ▁돌 기로 농 ▁위치 ▁토 ▁역할 하우스 섭 ▁대통령이 이라고 ▁하나 료 됐 ▁스마트폰 법을 ▁최근 테이션 벤처 ▁참 택 류 관 DF ▁팔 중 ▁지구 ▁티 스가 ▁영 심
The first time I saw the newly formed company, the newly formed company, the newly formed company, the newly formed company, the newly formed company, the newly formed company, the newly formed company, the newly formed company, the newly formed company, the newly formed company, the newly formed company, the newly formed company, the newly formed company, the newly formed company, the newly formed company, the newly formed company, the newly formed company, the newly formed company, the newly formed company, the newly formed company, the

## Four-gram

In [ ]:
fourgram_model = NGram(4)
fourgram_model.train(train_sequences)

In [ ]:
fourgram_add_k_lowest, fourgram_add_k_highest, fourgram_add_k_mean_perplexity, fourgram_add_k_min_perplexity, fourgram_add_k_max_perplexity, fourgram_add_k_median_perplexity = fourgram_model.highest_lowest_perplexity(df_val_ko, "4-gram add-k", "add-k")
fourgram_laplace_lowest, fourgram_laplace_highest, fourgram_laplace_mean_perplexity, fourgram_laplace_min_perplexity, fourgram_laplace_max_perplexity, fourgram_laplace_median_perplexity = fourgram_model.highest_lowest_perplexity(df_val_ko, "4-gram laplace", "laplace")
fourgram_add_k_metrics = {
    "model": "fourgram add-k",
    "average_perplexity": fourgram_add_k_mean_perplexity,
    "median_perplexity": fourgram_add_k_median_perplexity,
    "min_perplexity": fourgram_add_k_min_perplexity,
    "max_perplexity": fourgram_add_k_max_perplexity
}
fourgram_laplace_metrics = {
    "model": "fourgram laplace",
    "average_perplexity": fourgram_laplace_mean_perplexity,
    "median_perplexity": fourgram_laplace_median_perplexity,
    "min_perplexity": fourgram_laplace_min_perplexity,
    "max_perplexity": fourgram_laplace_max_perplexity
}

In [ ]:
probability = fourgram_model.model_probability(
    [BOS, BOS, BOS],
    "대한민국의",
)

print(probability)

3.883796799751437e-05

In [ ]:
sample = fourgram_model.sample()
print(sample)
print(translate(sample,KO,EN))

▁지 ▁가 트리 분 - ▁태양 수의 률 되었 ▁형 ▁외 ▁2016 ▁합 ▁브루 낙 측 기업 ▁사진 ▁공격 하기 ▁DNA ▁초 ▁8 ▁학교 ▁곳 ▁인류 ▁판 ▁등장 마리 ▁표 ▁비 콜 혈 ▁스마트폰 ▁다이 ▁애 ▁종료 년도 징 ▁아마 망 갔 ▁지구 핵 텍 가는 ▁의 ▁통 나라 ▁의미
The number of solar cells has been regulated by the geographically excluded 2016 aggregate blue chip corporate photos attack the early eighth school where the human plate appeared mary list v call blood smartphone diary end of year also the year the chin probably went down the earth nuclear tech means the country of the go

## Six-gram

In [ ]:
sixgram_model = NGram(6)
sixgram_model.train(train_sequences)

In [ ]:
sixgram_lowest, sixgram_highest, sixgram_mean_perplexity, sixgram_min_perplexity, sixgram_max_perplexity, sixgram_median_perplexity = sixgram_model.highest_lowest_perplexity(df_val_ko, "6-gram")
sixgram_metrics = {
    "model": "sixgram",
    "average_perplexity": sixgram_mean_perplexity,
    "median_perplexity": sixgram_median_perplexity,
    "min_perplexity": sixgram_min_perplexity,
    "max_perplexity": sixgram_max_perplexity
}

In [ ]:
probability = sixgram_model.model_probability(
    [BOS]*5,
    "대한민국의",
)

print(probability)

3.883796799751437e-05

In [ ]:
sample = sixgram_model.sample()
print(sample)
print(translate(sample,KO,EN))

▁지 ▁가 트리 분 - ▁태양 수의 률 되었 ▁형 ▁외 ▁2016 ▁합 ▁브루 낙 측 기업 ▁사진 ▁공격 하기 ▁DNA ▁초 ▁8 ▁학교 ▁곳 ▁인류 ▁판 ▁등장 마리 ▁표 ▁비 콜 혈 ▁스마트폰 ▁다이 ▁애 ▁종료 년도 징 ▁아마 망 갔 ▁지구 핵 텍 가는 ▁의 ▁통 나라 ▁의미
The number of solar cells has been regulated by the geographically excluded 2016 aggregate blue chip corporate photos attack the early eighth school where the human plate appeared mary list v call blood smartphone diary end of year also the year the chin probably went down the earth nuclear tech means the country of the go

## N-gram Results

In [ ]:
combined_lowest = pd.concat(
    [unigram_lowest, bigram_lowest, fourgram_add_k_lowest, fourgram_laplace_lowest, sixgram_lowest],
    ignore_index=True
)

combined_highest = pd.concat(
    [unigram_highest, bigram_highest, fourgram_add_k_highest, fourgram_laplace_highest, sixgram_highest],
    ignore_index=True
)

In [ ]:
combined_lowest

,model,question,question_tokenized,perplexity,translation_en
0,unigram,최초의 광고 대행 업체는 무엇인가?,"[▁최초, 의, <UNK>, ▁, <UNK>, <UNK>, 는, ▁무엇인가, ?]",43.569209,What was the first advertising agency?
1,unigram,세상에서 가장 넓은 산은 무엇인가?,"[▁세상, 에서, ▁가장, <UNK>, ▁산, 은, ▁무엇인가, ?]",63.432125,What is the widest mountain in the world?
2,unigram,세상에서 가장 큰 대학교는 무엇인가?,"[▁세상, 에서, ▁가장, ▁큰, ▁, 대학교, 는, ▁무엇인가, ?]",67.809011,What is the largest university in the world?
3,unigram,KKK의 지도자는 누구인가?,"[<UNK>, <UNK>, 의, ▁지도, 자는, ▁누구, 인가, ?]",69.120848,Who is the leader of the KKK?
4,unigram,창원시에서 가장 높은 건물은 무엇인가?,"[▁, <UNK>, 시, 에서, ▁가장, ▁높은, ▁건물, 은, ▁무엇인가, ?]",78.489330,What's the tallest building in the city?
5,bigram,세상에서 가장 큰 대학교는 무엇인가?,"[▁세상, 에서, ▁가장, ▁큰, ▁, 대학교, 는, ▁무엇인가, ?]",5.939880,What is the largest university in the world?
6,bigram,KKK의 지도자는 누구인가?,"[<UNK>, <UNK>, 의, ▁지도, 자는, ▁누구, 인가, ?]",6.835423,Who is the leader of the KKK?
7,bigram,세상에서 가장 오래된 대학교는 무엇인가?,"[▁세상, 에서, ▁가장, ▁오래, 된, ▁, 대학교, 는, ▁무엇인가, ?]",6.891953,What is the oldest university in the world?
8,bigram,세상에서 가장 오래된 대학교는 무엇인가?,"[▁세상, 에서, ▁가장, ▁오래, 된, ▁, 대학교, 는, ▁무엇인가, ?]",6.891953,What is the oldest university in the world?
9,bigram,세상에서 가장 오래된 대학교는 무엇인가?,"[▁세상, 에서, ▁가장, ▁오래, 된, ▁, 대학교, 는, ▁무엇인가, ?]",6.891953,What is the oldest university in the world?
10,4-gram add-k,중국에서 가장 인구밀도가 높은 도시는 어디인가?,"[▁중국, 에서, ▁가장, ▁인구, 밀, 도가, ▁높은, ▁도시, 는, ▁어디, 인...",13.029646,What is the most densely populated city in China?
11,4-gram add-k,세상에서 가장 큰 대학교는 무엇인가?,"[▁세상, 에서, ▁가장, ▁큰, ▁, 대학교, 는, ▁무엇인가, ?]",16.724450,What is the largest university in the world?
12,4-gram add-k,중국에서 가장 작은 도시는 어디인가?,"[▁중국, 에서, ▁가장, ▁작은, ▁도시, 는, ▁어디, 인가, ?]",22.905718,Where is the smallest city in China?
13,4-gram add-k,스웨덴에서 가장 인구밀도가 높은 도시는 어디인가?,"[▁스, 웨, 덴, 에서, ▁가장, ▁인구, 밀, 도가, ▁높은, ▁도시, 는, ▁...",26.682906,What is the most densely populated city in Swe...
14,4-gram add-k,인간의 몸에서 가장 큰 뼈는 무엇인가?,"[▁, 인간의, ▁몸, 에서, ▁가장, ▁큰, ▁, 뼈, 는, ▁무엇인가, ?]",28.068641,What is the largest bone in the human body?
15,4-gram laplace,세상에서 가장 큰 대학교는 무엇인가?,"[▁세상, 에서, ▁가장, ▁큰, ▁, 대학교, 는, ▁무엇인가, ?]",84.626409,What is the largest university in the world?
16,4-gram laplace,중국에서 가장 인구밀도가 높은 도시는 어디인가?,"[▁중국, 에서, ▁가장, ▁인구, 밀, 도가, ▁높은, ▁도시, 는, ▁어디, 인...",86.931851,What is the most densely populated city in China?
17,4-gram laplace,중국에서 가장 작은 도시는 어디인가?,"[▁중국, 에서, ▁가장, ▁작은, ▁도시, 는, ▁어디, 인가, ?]",114.835922,Where is the smallest city in China?
18,4-gram laplace,세상에서 가장 오래된 대학교는 무엇인가?,"[▁세상, 에서, ▁가장, ▁오래, 된, ▁, 대학교, 는, ▁무엇인가, ?]",126.881493,What is the oldest university in the world?
19,4-gram laplace,세상에서 가장 오래된 대학교는 무엇인가?,"[▁세상, 에서, ▁가장, ▁오래, 된, ▁, 대학교, 는, ▁무엇인가, ?]",126.881493,What is the oldest university in the world?
20,6-gram,중국에서 가장 인구밀도가 높은 도시는 어디인가?,"[▁중국, 에서, ▁가장, ▁인구, 밀, 도가, ▁높은, ▁도시, 는, ▁어디, 인...",25.681725,What is the most densely populated city in China?
21,6-gram,세상에서 가장 큰 대학교는 무엇인가?,"[▁세상, 에서, ▁가장, ▁큰, ▁, 대학교, 는, ▁무엇인가, ?]",36.083826,What is the largest university in the world?
22,6-gram,세상에서 가장 먼저 시작된 교통수단은 무엇인가?,"[▁세상, 에서, ▁가장, ▁먼저, ▁시작, 된, ▁, 교통, 수, 단, 은, ▁무...",41.343078,What was the first transportation system in th...
23,6-gram,인간의 몸에서 가장 큰 뼈는 무엇인가?,"[▁, 인간의, ▁몸, 에서, ▁가장, ▁큰, ▁, 뼈, 는, ▁무엇인가, ?]",44.878923,What is the largest bone in the human body?
24,6-gram,에피쿠로스는 언제 태어났나요?,"[▁에, 피, 쿠, 로, 스는, ▁언제, ▁태, 어, 났, 나요, ?]",53.710862,When was Epicurus born?

In [ ]:
combined_highest

,model,question,question_tokenized,perplexity,translation_en
0,unigram,더글러스 맥아더 배우자는 누군가요?,"[▁더, 글, 러, 스, ▁맥, 아, 더, ▁배우, 자는, ▁누군가, 요, ?]",928.479072,Who is Douglas MacArthur's wife?
1,unigram,인도네시아에서는 동성결혼이 합법적인가?,"[▁인도, 네, 시아, 에서는, ▁동, 성, 결, 혼, 이, ▁합, 법, 적인, 가...",882.507545,Is same-sex marriage legal in Indonesia?
2,unigram,인도네시아에서는 동성결혼이 합법적인가?,"[▁인도, 네, 시아, 에서는, ▁동, 성, 결, 혼, 이, ▁합, 법, 적인, 가...",882.507545,Is same-sex marriage legal in Indonesia?
3,unigram,말레이시아에서는 핵무기가 합법적인가?,"[▁말, 레이, 시아, 에서는, ▁, 핵, 무, 기가, ▁합, 법, 적인, 가, ?]",795.780166,Is nuclear weapons legal in Malaysia?
4,unigram,신화에는 그리스 신들이 몇 명이나 있을까?,"[▁신, 화, 에는, ▁그리, 스, ▁신, 들이, ▁몇, ▁명, 이나, ▁있을까, ?]",650.994599,How many Greek gods do myths have?
5,bigram,"임시정부는 종전의 정부가 무너진 후, 무정부 상태를 해소하기 위해 임시로 구성된 정...","[▁임, 시, 정부, 는, ▁종, 전, 의, <UNK>, ▁무, 너, 진, ▁후, ...",390.112906,Does the interim government say that it is a t...
6,bigram,불고기는 소의 어느부위를 사용하는가?,"[▁불, 고, 기는, ▁소, 의, ▁어느, 부, 위를, ▁사용하는, 가, ?]",384.058199,What part of the cow does the fisherman use?
7,bigram,더글러스 맥아더 배우자는 누군가요?,"[▁더, 글, 러, 스, ▁맥, 아, 더, ▁배우, 자는, ▁누군가, 요, ?]",330.763269,Who is Douglas MacArthur's wife?
8,bigram,클라미디아 발병원인은 무엇인가?,"[▁클, 라, 미, 디아, ▁발, <UNK>, 인은, ▁무엇인가, ?]",305.688873,What is the Chlamydia launcher?
9,bigram,제1대 휘트워스 준남작 조지프 휘트워스 경의 소속은 어디인가요?,"[▁제, 1, 대, ▁, 휘, 트, 워, 스, <UNK>, 남, 작, ▁조, 지, ...",293.670602,"Where is the first Whitworth deputy earl, Sir ..."
10,4-gram add-k,불고기는 소의 어느부위를 사용하는가?,"[▁불, 고, 기는, ▁소, 의, ▁어느, 부, 위를, ▁사용하는, 가, ?]",1933.488974,What part of the cow does the fisherman use?
11,4-gram add-k,육파철학의 이름들은 무엇인가?,"[▁육, 파, 철, 학, 의, ▁이름, 들은, ▁무엇인가, ?]",1595.619733,What are the names of the philosophy of the fl...
12,4-gram add-k,클라미디아 발병원인은 무엇인가?,"[▁클, 라, 미, 디아, ▁발, <UNK>, 인은, ▁무엇인가, ?]",1595.619733,What is the Chlamydia launcher?
13,4-gram add-k,신화에는 그리스 신들이 몇 명이나 있을까?,"[▁신, 화, 에는, ▁그리, 스, ▁신, 들이, ▁몇, ▁명, 이나, ▁있을까, ?]",1389.530975,How many Greek gods do myths have?
14,4-gram add-k,신화에는 그리스 신들이 몇 명이나 있을까?,"[▁신, 화, 에는, ▁그리, 스, ▁신, 들이, ▁몇, ▁명, 이나, ▁있을까, ?]",1389.530975,How many Greek gods do myths have?
15,4-gram laplace,불고기는 소의 어느부위를 사용하는가?,"[▁불, 고, 기는, ▁소, 의, ▁어느, 부, 위를, ▁사용하는, 가, ?]",1653.850184,What part of the cow does the fisherman use?
16,4-gram laplace,클라미디아 발병원인은 무엇인가?,"[▁클, 라, 미, 디아, ▁발, <UNK>, 인은, ▁무엇인가, ?]",1567.819789,What is the Chlamydia launcher?
17,4-gram laplace,육파철학의 이름들은 무엇인가?,"[▁육, 파, 철, 학, 의, ▁이름, 들은, ▁무엇인가, ?]",1567.819789,What are the names of the philosophy of the fl...
18,4-gram laplace,신화에는 그리스 신들이 몇 명이나 있을까?,"[▁신, 화, 에는, ▁그리, 스, ▁신, 들이, ▁몇, ▁명, 이나, ▁있을까, ?]",1415.856367,How many Greek gods do myths have?
19,4-gram laplace,신화에는 그리스 신들이 몇 명이나 있을까?,"[▁신, 화, 에는, ▁그리, 스, ▁신, 들이, ▁몇, ▁명, 이나, ▁있을까, ?]",1415.856367,How many Greek gods do myths have?
20,6-gram,클라미디아 발병원인은 무엇인가?,"[▁클, 라, 미, 디아, ▁발, <UNK>, 인은, ▁무엇인가, ?]",2026.680873,What is the Chlamydia launcher?
21,6-gram,7년 전쟁이 발발한 이유는 무엇인가?,"[▁7, 년, ▁전쟁, 이, ▁발, 발, 한, ▁이유는, ▁무엇인가, ?]",1975.305517,What caused the Seven Years' War?
22,6-gram,불고기는 소의 어느부위를 사용하는가?,"[▁불, 고, 기는, ▁소, 의, ▁어느, 부, 위를, ▁사용하는, 가, ?]",1933.488974,What part of the cow does the fisherman use?
23,6-gram,걸프전은 몇 년도에 끝났나?,"[▁걸, 프, 전, 은, ▁몇, ▁, 년도, 에, ▁끝, 났, 나, ?]",1917.700503,How many years did the Gulf War end?
24,6-gram,승려는 어느 종교에 종사하고 있는가?,"[▁승, <UNK>, 는, ▁어느, ▁종교, 에, ▁종, 사, 하고, ▁있는, 가, ?]",1898.797932,What religion is the quest for glory?

In [ ]:
pd.DataFrame([unigram_metrics, bigram_metrics, fourgram_add_k_metrics, fourgram_laplace_metrics, sixgram_metrics])

,model,average_perplexity,median_perplexity,min_perplexity,max_perplexity
0,unigram,251.578953,227.856656,43.569209,928.479072
1,bigram,62.486682,40.044834,5.939880,390.112906
2,fourgram add-k,292.565474,175.763041,13.029646,1933.488974
3,fourgram laplace,530.494652,441.619560,84.626409,1653.850184
4,sixgram,611.426693,468.070143,25.681725,2026.680873

## Neural Language Model

In [ ]:
!pip install gensim

Collecting gensim
  Downloading gensim-4.4.0-cp313-cp313-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (8.4 kB)
Requirement already satisfied: numpy>=1.18.5 in /usr/local/lib/python3.13/dist-packages (from gensim) (2.1.3)
Requirement already satisfied: scipy>=1.7.0 in /usr/local/lib/python3.13/dist-packages (from gensim) (1.16.3)
Requirement already satisfied: smart_open>=1.8.1 in /usr/local/lib/python3.13/dist-packages (from gensim) (8.0.1)
Requirement already satisfied: wrapt in /usr/local/lib/python3.13/dist-packages (from smart_open>=1.8.1->gensim) (2.4.1)
Downloading gensim-4.4.0-cp313-cp313-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (27.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.8/27.8 MB 21.3 MB/s eta 0:00:00
Installing collected packages: gensim
Successfully installed gensim-4.4.0

In [ ]:
import torch
import torch.nn as nn
from gensim.models import Word2Vec

### Add BOS and EOS to sequences

In [ ]:
# Add BOS and EOS for rnn training
def add_bos_eos_tokens(tokens):
    return ["<BOS>"] + tokens + ["<EOS>"]

train_sequences_rnn = [
    add_bos_eos_tokens(tokens)
    for tokens in train_sequences
]

val_sequences_rnn = [
    add_bos_eos_tokens(tokens)
    for tokens in val_sequences
]

In [ ]:
train_sequences_rnn[0]

['<BOS>', '▁30', '년', '▁전쟁', '의', '▁승', '자는', '▁누구', '인가', '?', '<EOS>']

### Create Vectors/Vocab

In [ ]:
INPUT_VECTOR_SIZE = 300
WINDOW = 5
MIN_COUNT = 2
w2v_model = Word2Vec(train_sequences_rnn, min_count=MIN_COUNT, vector_size=INPUT_VECTOR_SIZE, window=WINDOW)

In [ ]:
# Same number of keys as prediction vocabulary (+ 1 for BOS added already)
vocab_size = len(w2v_model.wv)
print(vocab_size == len(prediction_vocabulary) + 1)

True

In [ ]:
# vectorized sequences (encoding)
def encode(sequences):
  sequences_encoded = []
  for seq in sequences:
      words = []
      for word in seq:
          words.append(w2v_model.wv[word])
      sequences_encoded.append(words)
  return sequences_encoded

train_sequences_encoded = encode(train_sequences_rnn)

val_sequences_encoded = encode(val_sequences_rnn)

In [ ]:
len(train_sequences_encoded[0][0])

300

In [ ]:
word_to_idx = w2v_model.wv.key_to_index

# Indices of next word that should be predicted
def get_target_indices(sequences):
  target_indices = [
    [word_to_idx[w] for w in seq[1:]]
    for seq in sequences
  ]
  return target_indices

train_target_indices = get_target_indices(train_sequences_rnn)

val_target_indices = get_target_indices(val_sequences_rnn)

### RNN

In [ ]:
class SimpleRNN(nn.Module):
  def __init__(self, input_size, hidden_size, output_size):
    super(SimpleRNN, self).__init__()
    self.hidden_size = hidden_size
    self.input_size = input_size

    # Weight matrices
    self.W_ih = nn.Linear(input_size, hidden_size)
    self.W_hh = nn.Linear(hidden_size, hidden_size)
    self.W_hy = nn.Linear(hidden_size, output_size)

  def forward(self, x, h_prev):
    # x: input of shape (batch_size, input_size)
    # h_prev: previous hidden state of shape (batch_size, hidden_size)

    # Compute new hidden state
    h_t = torch.tanh(self.W_ih(x) + self.W_hh(h_prev))

    # Compute output
    y_t = self.W_hy(h_t)

    return y_t, h_t

  def init_hidden(self, batch_size):
    # Initialize hidden state (vector of zeros)
    return torch.zeros(batch_size, self.hidden_size)

class MultiLayerRNN(nn.Module):
  def __init__(self, input_size, hidden_size, output_size, num_layers):
    super(MultiLayerRNN, self).__init__()
    self.hidden_size = hidden_size
    self.num_layers = num_layers

    # One independent SimpleRNN per layer
    # First one takes input_size others hidden_size as thats their input
    self.layers = nn.ModuleList([
      SimpleRNN(
        input_size=input_size if i == 0 else hidden_size,
        hidden_size=hidden_size,
        output_size=output_size   # only actually used for the TOP layer's output
      )
      for i in range(num_layers)
    ])

  def forward(self, x_t, h_prev_list):
    h_new_list = []
    layer_input = x_t

    for i, layer in enumerate(self.layers):
      y_t, h_t = layer(layer_input, h_prev_list[i])
      h_new_list.append(h_t)
      layer_input = h_t

    return y_t, h_new_list

  def init_hidden(self, batch_size):
    # Initialize hidden states (vector of zeros)
    return [
        torch.zeros(batch_size, self.hidden_size)
        for _ in range(self.num_layers)
    ]

In [ ]:
# Initialize model, loss and optimizer
INPUT_SIZE = INPUT_VECTOR_SIZE
HIDDEN_SIZE = 64
OUTPUT_SIZE = vocab_size
NUM_LAYERS = 2
# BATCH_SIZE: how many independet examples get processed together?
# Higher -> Faster (parallel) + less noise (gradient averaged)
BATCH_SIZE = 1
LEARNING_RATE = 0.001

multi_layer_rnn_model = MultiLayerRNN(
    input_size=INPUT_SIZE,
    hidden_size=HIDDEN_SIZE,
    output_size=OUTPUT_SIZE,
    num_layers=NUM_LAYERS
)

criterion = nn.CrossEntropyLoss() # for softmax and calc of loss/grad
optimizer = torch.optim.Adam(multi_layer_rnn_model.parameters(), lr=0.001)  # adjust weights

In [ ]:
def train_rnn(
    model,
    criterion,
    optimizer,
    target_indices,
    sequences_encoded,
    batch_size,
    num_epochs
):
  for epoch in range(num_epochs):
    epoch_loss = 0.0

    for seq_idx, seq in enumerate(sequences_encoded):
      h_list = model.init_hidden(batch_size)
      optimizer.zero_grad()

      seq_loss = 0.0
      for t in range(len(seq) - 1):
        x_t = torch.tensor(seq[t], dtype=torch.float32).unsqueeze(0)
        target_t = torch.tensor([target_indices[seq_idx][t]])  # index of next word

        y_t, h_list = model(x_t, h_list)

        # softmaxes y_t and then looks up probability of target index (next word)
        # lower probability -> higher loss (only calculates)
        loss = criterion(y_t, target_t)
        seq_loss += loss

      # backprop through this sequence (computes gradients for each matrix, stored in .grad)
      seq_loss.backward()
      # update weights based on the calculated gradients for each Matrix
      optimizer.step()

      epoch_loss += seq_loss.item()

    print(f"Epoch {epoch+1}, Total Loss: {epoch_loss:.4f}")

In [ ]:
NUM_EPOCHS = 10
train_rnn(
  model=multi_layer_rnn_model,
  criterion=criterion,
  optimizer=optimizer,
  target_indices=train_target_indices,
  sequences_encoded=train_sequences_encoded,
  batch_size=BATCH_SIZE,
  num_epochs=NUM_EPOCHS
)

Epoch 1, Total Loss: 156993.8973
Epoch 2, Total Loss: 138515.6843
Epoch 3, Total Loss: 131673.3170
Epoch 4, Total Loss: 126967.6183
Epoch 5, Total Loss: 123393.9316
Epoch 6, Total Loss: 120619.7399
Epoch 7, Total Loss: 118277.4900
Epoch 8, Total Loss: 116323.5139
Epoch 9, Total Loss: 114578.1674
Epoch 10, Total Loss: 112959.6254

### Perplexity

In [ ]:
def calc_perplexity_rnn_token(
    model,
    criterion,
    target_indices,
    questions,
    sequences,
    adjusted_sequences,
    sequences_encoded,
    batch_size
):
    model.eval()
    question_scores = []
    token_scores = []

    with torch.no_grad():
        for seq_idx, seq in enumerate(sequences_encoded):
            seq_loss = 0.0
            h_list = model.init_hidden(batch_size)

            token_seq_scores = []

            # get sequences to same length as encoded_sequences (has no BOS)
            padded_sequence = ["-"] + sequences[seq_idx] + ["-"]

            for t in range(len(seq) - 1):
                x_t = torch.tensor(seq[t], dtype=torch.float32).unsqueeze(0)
                target_t = torch.tensor([target_indices[seq_idx][t]])

                y_t, h_list = model(x_t, h_list)
                loss = criterion(y_t, target_t)
                seq_loss += loss

                token_perplexity = torch.exp(loss)

                token_score = {
                    "token": padded_sequence[t + 1],
                    "adjusted_token": adjusted_sequences[seq_idx][t + 1],
                    "perplexity": token_perplexity.item(),
                }
                token_seq_scores.append(token_score)

            token_scores.append(token_seq_scores)

            seq_avg_loss = seq_loss / (len(seq) - 1)
            seq_perplexity = torch.exp(seq_avg_loss)

            seq_score = {
                "question": questions[seq_idx],
                "perplexity": seq_perplexity.item(),
            }
            question_scores.append(seq_score)

    return question_scores, token_scores

In [ ]:
rnn_perplexity, rnn_token_perplexity = calc_perplexity_rnn_token(
  model=multi_layer_rnn_model,
  criterion=criterion,
  target_indices=val_target_indices,
  questions=ko_val_questions,
  sequences=val_questions_tokenized,
  adjusted_sequences=val_sequences_rnn,
  sequences_encoded=val_sequences_encoded,
  batch_size=BATCH_SIZE
)

In [ ]:
df_rnn_perplexity = pd.DataFrame(rnn_perplexity)
lowest_rnn = df_rnn_perplexity.nsmallest(5, 'perplexity').copy()
highest_rnn = df_rnn_perplexity.nlargest(5, 'perplexity').copy()

for table in (lowest_rnn, highest_rnn):
    table["translation_en"] = table["question"].apply(
        lambda question: translate(question, KO, EN)
    )

### RNN Results

In [ ]:
df_lowest_rnn = lowest_rnn[["question", "translation_en", "perplexity"]].copy()
df_highest_rnn = highest_rnn[["question", "translation_en", "perplexity"]].copy()

In [ ]:
def calc_mean_token_count(idx, token_perplexity):
  df_token_perplexity = pd.DataFrame(token_perplexity[idx])
  sum_count_tokens = 0
  for i, token in enumerate(df_token_perplexity['adjusted_token']):
    if token != '?' and token != '<EOS>':
      sum_count_tokens += token_counts[token]
  return sum_count_tokens / (len(df_token_perplexity['adjusted_token']))

In [ ]:
df_lowest_rnn['mean_token_count'] = [calc_mean_token_count(idx, rnn_token_perplexity) for idx in df_lowest_rnn.index]
df_highest_rnn['mean_token_count'] = [calc_mean_token_count(idx, rnn_token_perplexity) for idx in df_highest_rnn.index]

In [ ]:
print(df_lowest_rnn['mean_token_count'].mean())
print(df_highest_rnn['mean_token_count'].mean())

355.43202797202804
80.65029137529137

In [ ]:
display(df_lowest_rnn)
display(df_highest_rnn)

,question,translation_en,perplexity,mean_token_count
301,중국에서 가장 인구밀도가 높은 도시는 어디인가?,What is the most densely populated city in China?,4.214709,259.769231
239,세상에서 가장 큰 대학교는 무엇인가?,What is the largest university in the world?,4.222419,412.300000
83,세상에서 가장 오래된 대학교는 무엇인가?,What is the oldest university in the world?,5.099924,368.363636
161,세상에서 가장 오래된 대학교는 무엇인가?,What is the oldest university in the world?,5.099924,368.363636
167,세상에서 가장 오래된 대학교는 무엇인가?,What is the oldest university in the world?,5.099924,368.363636

,question,translation_en,perplexity,mean_token_count
198,불고기는 소의 어느부위를 사용하는가?,What part of the cow does the fisherman use?,709.477600,121.583333
232,신화에는 그리스 신들이 몇 명이나 있을까?,How many Greek gods do myths have?,672.643616,48.923077
314,신화에는 그리스 신들이 몇 명이나 있을까?,How many Greek gods do myths have?,672.643616,48.923077
254,기업법을 어겼을때 어느부서에서 관리를 하는가?,What department do you run when you break the ...,615.607910,100.125000
280,"임시정부는 종전의 정부가 무너진 후, 무정부 상태를 해소하기 위해 임시로 구성된 정...",Does the interim government say that it is a t...,452.778778,83.696970

In [ ]:
df_rnn_token_perplexity = pd.DataFrame(rnn_token_perplexity[198])
df_rnn_token_perplexity

    token adjusted_token    perplexity
0      ▁불             ▁불  21734.210938
1       고              고    679.803528
2      기는             기는    661.919800
3      ▁소             ▁소  19096.744141
4       의              의     31.452448
5     ▁어느            ▁어느   3544.187500
6       부              부  11244.847656
7      위를             위를  37134.957031
8   ▁사용하는          ▁사용하는   8052.287109
9       가              가    138.531265
10      ?              ?      1.670436
11      -          <EOS>      1.004065

In [ ]:
calc_mean_token_count(301, rnn_token_perplexity)

259.7692307692308

In [ ]:
rnn_mean_perplexity = df_rnn_perplexity['perplexity'].mean()
rnn_median_perplexity = df_rnn_perplexity['perplexity'].median()
rnn_min_perplexity = df_rnn_perplexity['perplexity'].min()
rnn_max_perplexity = df_rnn_perplexity['perplexity'].max()

print(f"RNN mean perplexity:    {rnn_mean_perplexity}")
print(f"RNN median perplexity:  {rnn_median_perplexity}")

RNN mean perplexity:    85.57710720581954
RNN median perplexity:  47.159542083740234

In [ ]:
rnn_metrics = {
    "model": "Multilayer RNN",
    "average_perplexity": rnn_mean_perplexity,
    "median_perplexity": rnn_median_perplexity,
    "min_perplexity": rnn_min_perplexity,
    "max_perplexity": rnn_max_perplexity
}

## Overall Results

In [ ]:
pd.DataFrame([unigram_metrics, bigram_metrics, fourgram_add_k_metrics, fourgram_laplace_metrics, sixgram_metrics, rnn_metrics])

,model,average_perplexity,median_perplexity,min_perplexity,max_perplexity
0,unigram,251.578953,227.856656,43.569209,928.479072
1,bigram,62.486682,40.044834,5.939880,390.112906
2,fourgram add-k,292.565474,175.763041,13.029646,1933.488974
3,fourgram laplace,530.494652,441.619560,84.626409,1653.850184
4,sixgram,611.426693,468.070143,25.681725,2026.680873
5,Multilayer RNN,85.052405,49.375526,4.254868,750.986328

# Week 39

## Interpretable learned baseline

### Data processing

In [ ]:
df_train = df_train[
    df_train["lang"].isin(["ar", "ko", "te"])
]

df_val = df_val[
    df_val["lang"].isin(["ar", "ko", "te"])
]

In [ ]:
# True -> 1 && False -> 0

df_train = df_train.replace({True: 1, False: 0})
Y_train = df_train["answerable"]
df_val = df_val.replace({True: 1, False: 0})
Y_val = df_val["answerable"]

In [ ]:
df_train["tokenized_context"] = df_train.apply(
    lambda row: [token.text for token in lang_tokenizer[EN](row["context"])],
    axis = 1
)
df_train["tokenized_question_translated"] = df_train.apply(
    lambda row: [token.text for token in lang_tokenizer[EN](row["question_translated"])],
    axis = 1
)
df_train["overlap"] = df_train.apply(
    lambda row: [token for token in row["tokenized_context"]+row["tokenized_question_translated"] if token in list(set(row["tokenized_context"]) & set(row["tokenized_question_translated"]))],
    axis = 1
)

In [ ]:
ldict = {"te": TE, "ko": KO, "ar": AR}

df_val["tokenized_context"] = df_val.apply(
    lambda row: [token.text for token in lang_tokenizer[EN](row["context"])],
    axis = 1
)

df_val["tokenized_question_translated"] = df_val.apply(
    lambda row: [token.text for token in lang_tokenizer[EN](row["question_translated"])]
    ,
    axis = 1
)

df_val["overlap"] = df_val.apply(
    lambda row: [token for token in row["tokenized_context"]+row["tokenized_question_translated"] if token in list(set(row["tokenized_context"]) & set(row["tokenized_question_translated"]))],
    axis = 1
)

In [ ]:
from collections import Counter

from sklearn.feature_extraction import DictVectorizer
from sklearn.preprocessing import normalize

vectorizer = DictVectorizer()

train_X = vectorizer.fit_transform(Counter(x) for x in df_train["overlap"])
train_X = normalize(train_X, norm="l1")
train_Y = df_train["answerable"]

### Model training

In [ ]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression(C=1000, penalty="l1", random_state=1, solver='liblinear')
lr.fit(train_X, train_Y)

LogisticRegression(C=1000, penalty='l1', random_state=1, solver='liblinear')

### Model evaluation

In [ ]:
# evaluation metrics answerability

def answerability_scores(annotated, predicted):
    TP = TN = FP = FN = 0
    for a, p in zip(annotated, predicted):
        if a == 1:
          if p == 1: TP += 1
          else: FN += 1
        else:
          if p == 1: FP += 1
          else: TN += 1

    precision_ans = TP / (TP + FP) if TP + FP else 0.0
    recall_ans = TP / (TP + FN) if TP + FN else 0.0
    f1_ans = (2*precision_ans*recall_ans) / (precision_ans + recall_ans) if precision_ans + recall_ans else 0.0

    precision_unans = TN / (TN + FN) if TN + FN else 0.0
    recall_unans = TN / (TN + FP) if TP + FN else 0.0
    f1_unans = (2*precision_unans*recall_unans) / (precision_unans + recall_unans) if precision_unans + recall_unans else 0.0

    accuracy = (TP+TN) / (TP+TN+FP+FN) if TP+TN+FP+FN else 0.0

    return precision_ans, recall_ans, f1_ans, precision_unans, recall_unans, f1_unans, accuracy

def evaluate_answerability(name, annotated, predicted):
  precision_ans, recall_ans, f1_ans, precision_unans, recall_unans, f1_unans, accuracy = answerability_scores(annotated, predicted)
  result = {
      "model": name,

      "accuracy": accuracy,

      "macro_avg_f1": (f1_ans + f1_unans)/2,

      "precision_answerable": precision_ans,
      "recall_answerable": recall_ans,
      "f1_answerable": f1_ans,

      "precision_unanswerable": precision_unans,
      "recall_unanswerable": recall_unans,
      "f1_unanswerable": f1_unans,
  }
  return result

In [ ]:
df_val["predicted"] = df_val.apply(lambda row: lr.predict(normalize(vectorizer.transform(Counter(row["overlap"])), norm="l1"))[0], axis = 1)
df_val["predicted"]

0       1
1       0
2       1
3       1
4       1
       ..
3006    1
3007    1
3008    1
3009    1
3010    1
Name: predicted, Length: 1155, dtype: int64

In [ ]:
lr_ans_metrics_ar = evaluate_answerability("Logistic Regression (AR)", df_val.loc[df_val["lang"] == "ar", "answerable"], df_val.loc[df_val["lang"] == "ar", "predicted"])
lr_ans_metrics_ko = evaluate_answerability("Logistic Regression (KO)", df_val.loc[df_val["lang"] == "ko", "answerable"], df_val.loc[df_val["lang"] == "ko", "predicted"])
lr_ans_metrics_te = evaluate_answerability("Logistic Regression (TE)", df_val.loc[df_val["lang"] == "te", "answerable"], df_val.loc[df_val["lang"] == "te", "predicted"])
lr_ans_metrics = evaluate_answerability("Logistic Regression (Overall)", df_val["answerable"], df_val["predicted"])
pd.DataFrame([lr_ans_metrics_ar,lr_ans_metrics_ko,lr_ans_metrics_te,lr_ans_metrics])

,model,accuracy,macro_avg_f1,precision_answerable,recall_answerable,f1_answerable,precision_unanswerable,recall_unanswerable,f1_unanswerable
0,Logistic Regression (AR),0.862651,0.610097,0.896373,0.953168,0.923899,0.413793,0.230769,0.296296
1,Logistic Regression (KO),0.926966,0.574632,0.953353,0.970326,0.961765,0.230769,0.157895,0.187500
2,Logistic Regression (TE),0.752604,0.557448,0.781609,0.934708,0.851330,0.472222,0.182796,0.263566
3,Logistic Regression (Overall),0.845887,0.589195,0.877437,0.953582,0.913926,0.410256,0.195122,0.264463

In [ ]:
# false positive
fps = df_val.loc[(df_val["answerable"] == 0) & (df_val["predicted"] == 1), ["question", "context","lang"]]

print("False positive:")

for lang_code, lang_name in [("ar", "Arabic"), ("ko", "Korean"), ("te", "Telugu")]:
    print(f"\n\t{lang_name}:")
    subset = fps[fps["lang"] == lang_code].head(3)
    for q, c in zip(subset["question"], subset["context"]):
        tq = translate(q, lang_code, EN)
        print(f"\t\tquestion: {q}\n\t\tcontext: {c}\n\t\tquestion_translated: {tq}\n")

False positive:

	Arabic:
		question: هل زار ابن بطوطة اليمن؟
		context: After the "hajj" in either 1328 or 1330, he made his way to the port of Jeddah on the Red Sea coast. From there he followed the coast in a series of boats making slow progress against the prevailing south-easterly winds. Once in Yemen he visited Zabīd and later the highland town of Ta'izz, where he met the Rasulid dynasty king "(Malik)" Mujahid Nur al-Din Ali. Ibn Battuta also mentions visiting Sana'a, but whether he actually did so is doubtful. In all likelihood, he went directly from Ta'izz to the important trading port of Aden, arriving around the beginning of 1329 or 1331.
		question_translated: Has the Yemen duck visited?

		question: هل توجد قواعد عسكرية فرنسية في جيبوتي؟
		context: The French naval base of Djibouti, also known as the Naval base of Héron, is located in East Africa in Djibouti.
		question_translated: Are there French military bases in Djibouti?

		question: هل هناك تساوي بين الرجل والمرأة في الهند ؟
		context: Gender inequality in India refers to health, education, economic and political inequalities between men and women in India. Various international gender inequality indices rank India differently on each of these factors, as well as on a composite basis, and these indices are controversial.
		question_translated: Is there equality between men and women in India ?


	Korean:
		question: 시차는 중력과 관련이 있는가?
		context: Gravitational time dilation was first described by Albert Einstein in 1907 as a consequence of special relativity in accelerated frames of reference. In general relativity, it is considered to be a difference in the passage of proper time at different positions as described by a metric tensor of space-time. The existence of gravitational time dilation was first confirmed directly by the Pound–Rebka experiment in 1959.
		question_translated: Is the car related to gravity?

		question: 맹장 없이 살 수 있을까?
		context: In modern humans, the vermiform appendix is a vestige of a redundant organ that in ancestral species had digestive functions, much as it still does in extant species in which intestinal flora hydrolyze cellulose and similar indigestible plant materials. Some herbivorous animals, such as rabbits, have a terminal vermiform appendix and cecum that apparently bear patches of tissue with immune functions and may also be important in maintaining the composition of intestinal flora. It does not however seem to have much digestive function, if any, and is not present in all herbivores, even those with large caeca. As shown in the accompanying pictures however, the human appendix typically is about comparable to that of the rabbit's in size, though the caecum is reduced to a single bulge where the ileum empties into the colon. Some carnivorous animals may have appendices too, but seldom have more than vestigial caeca. In line with the possibility of vestigial organs developing new functions, some research suggests that the appendix may guard against the loss of symbiotic bacteria that aid in digestion, though that is unlikely to be a novel function, given the presence of vermiform appendices in many herbivores. Intestinal bacterial populations entrenched in the appendix may support quick re-establishment of the flora of the large intestine after an illness, poisoning, or after an antibiotic treatment depletes or otherwise causes harmful changes to the bacterial population of the colon. A 2013 study, however, refutes the idea of an inverse relationship between cecum size and appendix size and presence. It is widely present in euarchontoglires (a superorder of mammals that includes rodents and primates) and has also evolved independently in the diprotodont marsupials, monotremes, and is highly diverse in size and shape which could suggest it is not vestigial. Researchers deduce that the appendix has the ability to protect good bacteria in the gut. That way, when the gut is affected by a bout of diarrhea or other illness that cleans out the intestines, the good bacteria in the appendix can repopulate the digestive system and keep the person healthy.
		question_translated: Can we live without predators?

		question: 핵융합은 상용화 가능성이 있는가?
		context: Several experimental nuclear fusion reactors and facilities exist. The largest and most ambitious international nuclear fusion project currently in progress is ITER, a large tokamak under construction in France. ITER is planned to pave the way for commercial fusion power by demonstrating self-sustained nuclear fusion reactions with positive energy gain. Construction of the ITER facility began in 2007, but the project has run into many delays and budget overruns. The facility is now not expected to begin operations until the year 2027—11 years after initially anticipated. A follow on commercial nuclear fusion power station, DEMO, has been proposed. There are also suggestions for a power plant based upon a different fusion approach, that of an inertial fusion power plant.
		question_translated: Is there a commercial possibility of nuclear fusion?


	Telugu:
		question: మలేరియా వ్యాధి కి మందు కనిపెట్టిన శాస్త్రవేత్త ఎవరు?
		context: Malaria is a disease spread by mosquitoes. Malaria is transmitted when the parasite enters the blood of a person. Parasites depend on the humans they live with for their food. "Charles Louis Alphonse Lavren", a French defense physician, was awarded the Nobel Prize in 1907 for discovering how malaria is transmitted. Ronald Ross was awarded the Nobel Prize in 1902 for describing the life cycle of the malaria parasite, how it lives in mosquitoes and humans. Sir Ronald Ross discovered the life cycle of the malaria parasite while researching in the city of Secunderabad. Annually 500 million people in the world are affected by malaria fever and 2.7 million of them die. Plasmodium is a protozoan parasite that causes malaria. Protozoa are unicellular organisms. But their structure is more complex than that of bacteria. A lot of bacteria
		question_translated: Who is the scientist who invented a cure for malaria?

		question: తెలుగు పంచాంగం ప్రకారం నూతన సంవత్సరం ఏ ఇంగ్లీష్ నెలలో ప్రారంభమవుతుంది?
		context: It is also said that Ugadi is celebrated as a sign of initiation. It is a historical account that the Yodhagra is commemorated because the Salivahana Emperor Chaitrashuklapadyam was crowned with his bravery and became the leader of the Salivahana Yuga. In any case, the Telugu year starts from 'Ugadi', the auspicious day that ignites consciousness in the inanimate world and sprouts new seeds in humanity, so it is the first festival of Telugu people. It is customary to start new works on Ugadi day. On that day, they get up early and clean the houses, driveways, etc. Mango arches are tied and decorated at the doorsteps of the house. After bathing the head, wearing new clothes, the daily routine begins with Ugadi Pachdi. Ugadi Pachdi is special for this festival. Blend of Shadruchus – Ugadi Pachdi is a mixture of six flavors namely sweet (sweet), sour (sour), salty (salty), spicy (bitter), bitter (tikta) and vagaru (kashayam).
		question_translated: According to Telugu Panchang, which English month is the start of the New Year?

		question: దక్షిణ ఆఫ్రికా దేశ విస్తీర్ణం ఎంత?
		context: km <br>"border countries:" Cameroon 901 km, Chad 1,556 km, Democratic Republic of the Congo 1,747 km, Republic of the Congo 487 km, Sudan 174 km and South Sudan 1,055 km Coastline: 0 km (landlocked) Maritime claims: none (landlocked) Terrain: vast, flat to rolling, monotonous plateau; scattered hills in northeast and southwest Elevation extremes: <br>"lowest point:" Oubangui River 335 m <br>"highest point:" Mont Ngaoui 1,420 m Natural resources: diamonds, uranium, timber, gold, petroleum, hydropower Land use: <br>"arable land:" 2.89% <br>"permanent crops:" 0.13% <br>"other:" 96.98% (2012 est.) Irrigated land: 1.35 km² (2003) Total renewable water resources: 144.4 km<sup>3</sup> (2011) Freshwater withdrawal (domestic/industrial/agricultural):
		question_translated: What is the area of South Africa?

In [ ]:
# false negative
fns = df_val.loc[(df_val["answerable"] == 1) & (df_val["predicted"] == 0), ["question", "context", "lang"]]

print("False negative:")

for lang_code, lang_name in [("ar", "Arabic"), ("ko", "Korean"), ("te", "Telugu")]:
    print(f"\n\t{lang_name}:")
    subset = fns[fns["lang"] == lang_code].head(3)
    for q, c in zip(subset["question"], subset["context"]):
        tq = translate(q, lang_code, EN)
        print(f"\t\tquestion: {q}\n\t\tcontext: {c}\n\t\tquestion_translated: {tq}\n")

False negative:

	Arabic:
		question: متى  عاش فرويد مختص الطب النفسي؟
		context: Sigmund Freud ( ; ; born Sigismund Schlomo Freud; 6 May 1856 – 23 September 1939) was an Austrian neurologist and the founder of psychoanalysis, a clinical method for treating psychopathology through dialogue between a patient and a psychoanalyst.
		question_translated: When did Freud, a psychiatrist, live?

		question: هل مصرهي دولة  نامية؟
		context: In recent years, new terms have emerged to describe the largest developing countries such as BRIC that stands for Brazil, Russia, India, and China, along with "BRICET" (BRIC + Eastern Europe and Turkey), "BRICS" (BRIC + South Africa), "BRICM" (BRIC + Mexico), MINT (Mexico, Indonesia, Nigeria and Turkey), Next Eleven (Bangladesh, Egypt, Indonesia, Iran, Mexico, Nigeria, Pakistan, the Philippines, South Korea, Turkey, and Vietnam) and CIVETS (Colombia, Indonesia, Vietnam, Egypt, Turkey and South Africa). These countries do not share any common agenda, but some experts believe that they are enjoying an increasing role in the world economy and on political platforms.
		question_translated: Is Egypt a developing country?

		question: في أي عام تم إنتاج فيلم " ستيب مام " ؟
		context: Stepmom is a 1998 comedy-drama film directed by Chris Columbus and starring Julia Roberts, Susan Sarandon, and Ed Harris. Sarandon won the San Diego Film Critics Society Award for Best Actress and Harris won the National Board of Review Award for Best Supporting Actor, sharing the win with his role in "The Truman Show".
		question_translated: What year was " Step Mom " made ?


	Korean:
		question: 가장 많은 늑대가 서식하는 나라는 어디인가?
		context: Romania has a large population of wolves, numbering 2,500 animals. The wolf has been a protected animal in Romania since 1996, although the law is not enforced. The number of wolves in Albania and Macedonia is largely unknown, despite the importance the two countries have in linking wolf populations from Greece to those of Bosnia and Herzegovina and Croatia. Although protected, sometimes wolves are still illegally killed in Greece, and their future is uncertain. Wolf numbers have declined in Bosnia and Herzegovina since 1986, while the species is fully protected in neighbouring Croatia and Slovenia.
		question_translated: Where do you think the wolves live the most?

		question: 성경은 언제 쓰여졌는가?
		context: The oldest extant copy of a complete Bible is an early 4th-century parchment book preserved in the Vatican Library, and it is known as the Codex Vaticanus. The oldest copy of the Tanakh in Hebrew and Aramaic dates from the 10th century CE. The oldest copy of a complete Latin (Vulgate) Bible is the Codex Amiatinus, dating from the 8th century.
		question_translated: When was the Bible written?

		question: 소아마비 바이러스의 증상은?
		context: Poliomyelitis, often called polio or infantile paralysis, is an infectious disease caused by the poliovirus. In about 0.5 percent of cases there is muscle weakness resulting in an inability to move. This can occur over a few hours to a few days. The weakness most often involves the legs but may less commonly involve the muscles of the head, neck and diaphragm. Many people fully recover. In those with muscle weakness about 2 to 5 percent of children and 15 to 30 percent of adults die. Another 25 percent of people have minor symptoms such as fever and a sore throat and up to 5 percent have headache, neck stiffness and pains in the arms and legs. These people are usually back to normal within one or two weeks. In up to 70 percent of infections there are no symptoms. Years after recovery post-polio syndrome may occur, with a slow development of muscle weakness similar to that which the person had during the initial infection. Poliovirus is usually spread from person to person through infected fecal matter entering the mouth. It may also be spread by food or water containing human feces and less commonly from infected saliva. Those who are infected may spread the disease for up to six weeks even if no symptoms are present. The disease may be diagnosed by finding the virus in the feces or detecting antibodies against it in the blood. The disease only occurs naturally in humans. The disease is preventable with the polio vaccine; however, multiple doses are required for it to be effective. The US Centers for Disease Control and Prevention recommends polio vaccination boosters for travelers and those who live in countries where the disease is occurring. Once infected there is no specific treatment. In 2016, there were 37 cases of wild polio and 5 cases of vaccine-derived polio. This is down from 350,000 wild cases in 1988. In 2014 the disease was only spreading between people in Afghanistan, Nigeria, and Pakistan. In 2015 Nigeria had stopped the spread of wild poliovirus but it reoccurred in 2016. Poliomyelitis has existed for thousands of years, with depictions of the disease in ancient art. The disease was first recognized as a distinct condition by the English physician Michael Underwood in 1789 and the virus that causes it was first identified in 1908 by the Austrian immunologist Karl Landsteiner. Major outbreaks started to occur in the late 19th century in Europe and the United States. In the 20th century it became one of the most worrying childhood diseases in these areas. The first polio vaccine was developed in the 1950s by Jonas Salk. In 2013 the World Health Organization hoped that vaccination efforts and early detection of cases would result in global eradication of the disease by 2018.
		question_translated: What are the symptoms of polio?


	Telugu:
		question: కలరా వ్యాధిని మొదటగా ఏ దేశంలో కనుగొన్నారు ?
		context: The word cholera is from "kholera" from χολή "kholē" "bile". Cholera likely has its origins in the Indian subcontinent as evidenced by its prevalence in the region for centuries. Early outbreaks in the Indian subcontinent are believed to have been the result of poor living conditions as well as the presence of pools of still water, both of which provide ideal conditions for cholera to thrive. The disease first spread by trade routes (land and sea) to Russia in 1817, later to the rest of Europe, and from Europe to North America and the rest of the world. Seven cholera pandemics have occurred in the past 200 years, with the seventh pandemic originating in Indonesia in 1961.
		question_translated: In which country was cholera first discovered?

		question: వాటికన్ సిటి లో పేరుగాంచిన చర్చ్ ఏది?
		context: The Papal Basilica of St. Peter in the Vatican (), or simply St. Peter's Basilica (), is an Italian Renaissance church in Vatican City, the papal enclave within the city of Rome.
		question_translated: What is the name of the church in Vatican City?

		question: బ్రిటిష్ పాలనలో సగటున ఎంతమంది భారతీయులు మరణించారు?
		context: The British Indian Army fought in Ethiopia against the Italian Army, in Egypt, Libya, Tunisia and Algeria against both the Italian and German Army, and, after the Italian surrender, against the German Army in Italy. However, the bulk of the Indian Army was committed to fighting the Japanese Army, first during the British defeats in Malaya and the retreat from Burma to the Indian border; later, after resting and refitting for the victorious advance back into Burma, as part of the largest British Empire army ever formed. These campaigns cost the lives of over 87,000 Indian servicemen, while another 34,354 were wounded, and 67,340 became prisoners of war. Their valour was recognised with the award of some 4,000 decorations, and 18 members of the Indian Army were awarded the Victoria Cross or the George Cross. Field Marshal Claude Auchinleck, Commander-in-Chief of the Indian Army from 1942, asserted that the British "couldn't have come through both wars (World War I and II) if they hadn't had the Indian Army." British Prime Minister Winston Churchill also paid tribute to "The unsurpassed bravery of Indian soldiers and officers."
		question_translated: How many Indians died on average under British rule?

## RNN classifier

In [ ]:
import torch
import torch.nn as nn
from torch.nn.utils.rnn import pad_sequence, pack_padded_sequence
from torch.utils.data import DataLoader

In [ ]:
langs = ['ar', 'ko', 'te']

df_train_answerability = df_train[df_train['lang'].isin(langs)].copy()
df_val_answerability = df_val[df_val['lang'].isin(langs)].copy()

df_train_answerability = df_train_answerability[['question', 'context', 'answerable', 'lang']]
df_val_answerability = df_val_answerability[['question', 'context', 'answerable', 'lang']]

### Embedding

In [ ]:
!pip install bpemb sentencepiece
from bpemb import BPEmb

Collecting bpemb
  Downloading bpemb-0.3.6-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: sentencepiece in /usr/local/lib/python3.13/dist-packages (0.2.2)
Collecting gensim (from bpemb)
  Downloading gensim-4.4.0-cp313-cp313-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (8.4 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.13/dist-packages (from bpemb) (2.1.3)
Requirement already satisfied: requests in /usr/local/lib/python3.13/dist-packages (from bpemb) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.13/dist-packages (from bpemb) (4.67.3)
Requirement already satisfied: scipy>=1.7.0 in /usr/local/lib/python3.13/dist-packages (from gensim->bpemb) (1.16.3)
Requirement already satisfied: smart_open>=1.8.1 in /usr/local/lib/python3.13/dist-packages (from gensim->bpemb) (8.0.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests->bpemb) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests->bpemb) (3.19)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests->bpemb) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests->bpemb) (2026.7.22)
Requirement already satisfied: wrapt in /usr/local/lib/python3.13/dist-packages (from smart_open>=1.8.1->gensim->bpemb) (2.4.1)
Downloading bpemb-0.3.6-py3-none-any.whl (20 kB)
Downloading gensim-4.4.0-cp313-cp313-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (27.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.8/27.8 MB 47.9 MB/s eta 0:00:00
Installing collected packages: gensim, bpemb
Successfully installed bpemb-0.3.6 gensim-4.4.0

In [ ]:
VECTOR_SIZE = 100000
INPUT_DIMENSIONS = 300
multilingual_bpemb = BPEmb(lang="multi", vs=VECTOR_SIZE, dim=INPUT_DIMENSIONS)

downloading https://bpemb.h-its.org/multi/multi/multi.wiki.bpe.vs100000.model

100%|██████████| 1965223/1965223 [00:00<00:00, 22391212.44B/s]

downloading https://bpemb.h-its.org/multi/multi/multi.wiki.bpe.vs100000.d300.w2v.bin.tar.gz

100%|██████████| 112202964/112202964 [00:04<00:00, 27907909.64B/s]

In [ ]:
def embed(df_emb, col):
  embs = []
  for c in df_emb[col]:
    emb = torch.tensor(multilingual_bpemb.embed(c))
    embs.append(emb)
  return embs

train_emb_contexts = embed(df_train_answerability, 'context')
train_emb_questions = embed(df_train_answerability, 'question')
train_emb_labels = torch.tensor(df_train_answerability['answerable'].astype(int).values)

val_emb_contexts = embed(df_val_answerability, 'context')
val_emb_questions = embed(df_val_answerability, 'question')
val_emb_labels = torch.tensor(df_val_answerability['answerable'].astype(int).values)

train_data = list(zip(train_emb_contexts, train_emb_questions, train_emb_labels))
val_data = list(zip(val_emb_contexts, val_emb_questions, val_emb_labels))

In [ ]:
# Fill sequences with 0s to get same length
# Save original length
def collate(batch):
  c, q, y = zip(*batch)

  c_len = [len(x) for x in c]
  q_len = [len(x) for x in q]

  return (
      pad_sequence(c, batch_first=True), c_len,
      pad_sequence(q, batch_first=True), q_len,
      torch.stack(y)
  )

# Shapes when iterating DataLoader
# B = batch size
# maxLc/maxLq = len of longest ctx/q
# dim = input dimensions (300)
# c: (B, maxLc, dim)
# q: (B, maxLq, dim)
# c_len/q_len: (B,) -> original lengths
# y: (B,) -> labels 0 or 1
train_loader = DataLoader(train_data, batch_size=32, shuffle=True,  collate_fn=collate)
val_loader   = DataLoader(val_data,   batch_size=64, shuffle=False, collate_fn=collate)

### LSTM

In [ ]:
class LSTM_Classifier(nn.Module):
  def __init__(
    self,
    input_size,
    hidden_size,
    output_size,
    num_layers,
    dropout=0.2
  ):
    super(LSTM_Classifier, self).__init__()
    self.lstm_c = nn.LSTM(input_size, hidden_size,
                          num_layers, batch_first=True)
    self.lstm_q = nn.LSTM(input_size, hidden_size,
                          num_layers, batch_first=True)

    self.drop = nn.Dropout(dropout)

    self.fc = nn.Linear(hidden_size, output_size)

  def forward(self, c, c_len, q, q_len):
    c = self.drop(c)
    q = self.drop(q)
    # c: (B, maxLc, dim)   c_len: (B,)   q: (B, maxLq, dim)   q_len: (B,)
    # Removes padding and sort by length of sequences
    c = pack_padded_sequence(c, c_len, batch_first=True, enforce_sorted=False)
    q = pack_padded_sequence(q, q_len, batch_first=True, enforce_sorted=False)

    _, (hn, cn) = self.lstm_c(c)
    _, (hk, ck) = self.lstm_q(q, (hn, cn))

    # hk: (N, B, H)
    # -> one vector per layer per sample
    # -1: (B, H)
    # -> picks last layer -> one vector per sample
    # fc: (B, O) = (B, 1)
    # -> maps from H to number of classes
    # squeeze(-1): (B,)
    # -> removes one dimension -> column to vector
    return self.fc(self.drop(hk[-1])).squeeze(-1)

In [ ]:
INPUT_SIZE = INPUT_DIMENSIONS
HIDDEN_SIZE = 128
NUM_LAYERS = 1
OUTPUT_SIZE = 1
LEARNING_RATE = 0.001

lstm_model = LSTM_Classifier(
  input_size=INPUT_SIZE,
  hidden_size=HIDDEN_SIZE,
  output_size=OUTPUT_SIZE,
  num_layers=NUM_LAYERS
)

criterion = nn.BCEWithLogitsLoss()
optimizer = torch.optim.Adam(lstm_model.parameters(), lr=LEARNING_RATE)

### Train

In [ ]:
RNN_MODEL_PATH = "./models/week39_rnn"

def train_lstm(
    model,
    criterion,
    optimizer,
    num_epochs,
    loader
):
  device = "cuda" if torch.cuda.is_available() else "cpu"
  print(device)
  model = model.to(device)
  for epoch in range(num_epochs):
    model.train()
    epoch_loss = 0.0
    for i, (c, c_len, q, q_len, y) in enumerate(loader, start=1):  # Per batch
      c, q, y = c.to(device), q.to(device), y.to(device)
      optimizer.zero_grad()
      outputs = model(c, c_len, q, q_len)
      # criterion applies sigmoid to scale from 0-1
      # and compares with actual label
      loss = criterion(outputs, y.float())
      loss.backward()
      # rescales gradients to prevent exploding gradients (large steps)
      nn.utils.clip_grad_norm_(model.parameters(), 1.0)
      optimizer.step()
      epoch_loss += loss.item()

    print(f'Epoch [{epoch+1}/{num_epochs}], Loss: {epoch_loss / len(loader):.4f}')
  torch.save(model.state_dict(), RNN_MODEL_PATH)

In [ ]:
if os.path.exists(RNN_MODEL_PATH):
  lstm_model.load_state_dict(torch.load(RNN_MODEL_PATH, map_location="cpu"))
else:
  train_lstm(
      model=lstm_model,
      criterion=criterion,
      optimizer=optimizer,
      num_epochs=10,
      loader=train_loader
  )

cuda
Epoch [1/10], Loss: 0.1840
Epoch [2/10], Loss: 0.1186
Epoch [3/10], Loss: 0.1156
Epoch [4/10], Loss: 0.1117
Epoch [5/10], Loss: 0.1082
Epoch [6/10], Loss: 0.1073
Epoch [7/10], Loss: 0.0992
Epoch [8/10], Loss: 0.0898
Epoch [9/10], Loss: 0.0833
Epoch [10/10], Loss: 0.0764

### Predict

In [ ]:
@torch.no_grad()
def predict(model, loader):
    device = next(model.parameters()).device
    model.eval()
    preds, labels = [], []
    for c, c_len, q, q_len, y in loader:
        logits = model(c.to(device), c_len, q.to(device), q_len)
        preds += (logits > 0).long().cpu().tolist()
        labels += y.tolist()
    return preds, labels

In [ ]:
preds, labels = predict(lstm_model, val_loader)
lang_list = df_val_answerability['lang'].to_list()
df_preds_lstm = pd.DataFrame({
    'pred': preds,
    'label': labels,
    'lang': lang_list
})

df_preds_lstm_ar = df_preds_lstm[df_preds_lstm['lang'] == 'ar']
df_preds_lstm_ko = df_preds_lstm[df_preds_lstm['lang'] == 'ko']
df_preds_lstm_te = df_preds_lstm[df_preds_lstm['lang'] == 'te']

### Results

In [ ]:
def answerability_scores(annotated, predicted):
    TP = TN = FP = FN = 0
    for a, p in zip(annotated, predicted):
        if a == 1:
          if p == 1: TP += 1
          else: FN += 1
        else:
          if p == 1: FP += 1
          else: TN += 1

    precision_ans = TP / (TP + FP) if TP + FP else 0.0
    recall_ans = TP / (TP + FN) if TP + FN else 0.0
    f1_ans = (2*precision_ans*recall_ans) / (precision_ans + recall_ans) if precision_ans + recall_ans else 0.0

    precision_unans = TN / (TN + FN) if TN + FN else 0.0
    recall_unans = TN / (TN + FP) if TN + FP else 0.0
    f1_unans = (2*precision_unans*recall_unans) / (precision_unans + recall_unans) if precision_unans + recall_unans else 0.0

    accuracy = (TP+TN) / (TP+TN+FP+FN) if TP+TN+FP+FN else 0.0

    return precision_ans, recall_ans, f1_ans, precision_unans, recall_unans, f1_unans, accuracy

def evaluate_answerability(name, annotated, predicted):
  precision_ans, recall_ans, f1_ans, precision_unans, recall_unans, f1_unans, accuracy = answerability_scores(annotated, predicted)
  result = {
      "model": name,

      "accuracy": accuracy,

      "macro_avg_f1": (f1_ans + f1_unans)/2,

      "precision_answerable": precision_ans,
      "recall_answerable": recall_ans,
      "f1_answerable": f1_ans,

      "precision_unanswerable": precision_unans,
      "recall_unanswerable": recall_unans,
      "f1_unanswerable": f1_unans,
  }
  return result

In [ ]:
lstm_result_ar = evaluate_answerability("LSTM (AR)", df_preds_lstm_ar['label'].to_list(), df_preds_lstm_ar['pred'].to_list())
lstm_result_ko = evaluate_answerability("LSTM (KO)", df_preds_lstm_ko['label'].to_list(), df_preds_lstm_ko['pred'].to_list())
lstm_result_te = evaluate_answerability("LSTM (TE)", df_preds_lstm_te['label'].to_list(), df_preds_lstm_te['pred'].to_list())
lstm_result_overall = evaluate_answerability("LSTM (Overall)", labels, preds)

In [ ]:
pd.DataFrame([lstm_result_ar, lstm_result_ko, lstm_result_te, lstm_result_overall])

,model,accuracy,macro_avg_f1,precision_answerable,recall_answerable,f1_answerable,precision_unanswerable,recall_unanswerable,f1_unanswerable
0,LSTM (AR),0.978313,0.951720,0.991667,0.983471,0.987552,0.890909,0.942308,0.915888
1,LSTM (KO),0.969101,0.814504,0.973837,0.994065,0.983847,0.833333,0.526316,0.645161
2,LSTM (TE),0.869792,0.781620,0.857567,0.993127,0.920382,0.957447,0.483871,0.642857
3,LSTM (Overall),0.939394,0.856876,0.942363,0.989909,0.965551,0.912281,0.634146,0.748201

# Week 40-41

## Tokenizer and Model

In [26]:
MODEL_NAME = "google-bert/bert-base-multilingual-cased"

bert_tokenizer = AutoTokenizer.from_pretrained(
    MODEL_NAME,
    use_fast=True,
)

bert_model = AutoModelForQuestionAnswering.from_pretrained(
    MODEL_NAME
)

config.json:   0%|          | 0.00/625 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/49.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/996k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.96M [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  714MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] BertForQuestionAnswering LOAD REPORT from: google-bert/bert-base-multilingual-cased
Key                                        | Status     |
-------------------------------------------+------------+-
bert.pooler.dense.bias                     | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
bert.pooler.dense.weight                   | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
qa_outputs.weight                          | MISSING    |
qa_outputs.bias                            | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

## Data processing

In [27]:
import torch
import pandas as pd


def make_training_data(row):

    encoding = bert_tokenizer(
        row["question"],
        row["context"],
        max_length=512,
        truncation="only_second",
        padding="max_length",
        return_offsets_mapping=True,
        return_tensors="pt",
    )
    answer = row["answer"]
    answer_start = row["answer_start"]

    input_ids = encoding["input_ids"][0]
    offsets = encoding["offset_mapping"][0].tolist()
    sequence_ids = encoding.sequence_ids(0)

    start_position = 0
    end_position = 0

    if answer_start != -1:
        answer_end = answer_start + len(answer)

        answer_token_indices = []

        for token_index, (offset, sequence_id) in enumerate(
            zip(offsets, sequence_ids)
        ):
            token_start, token_end = offset

            if (
                sequence_id == 1
                and token_end > answer_start
                and token_start < answer_end
            ):
                answer_token_indices.append(token_index)

        if answer_token_indices:
            start_position = answer_token_indices[0]
            end_position = answer_token_indices[-1]

    return {
        "input_ids": input_ids,
        "attention_mask": encoding["attention_mask"][0],
        "token_type_ids": encoding["token_type_ids"][0],
        "start_positions": torch.tensor(start_position),
        "end_positions": torch.tensor(end_position),
    }

In [28]:
result = make_training_data(df_train.iloc[3])


result

{'input_ids': tensor([   101,   9435,  14871,  11489,  22224,   9580,  37388,  13441,  64002,
          64379,   9294, 119137,  12030,  11287,    136,    102,  10117,  11160,
          28362,  14456,    113,  11721,    114,  10124,    169,  11160,  11683,
          11989,  21391,  10165,    119,  14864,  28245,  10301,  10160,  28362,
          11545,  10106,  30795,    117,  10829,    117,  10111,  10271,  10124,
          10105,  11356,    112,    187,  27626,  11844,  51769,  19688,  10111,
          10105,  15363,  21391,  10165,  10106,  10105,  11356,  10155,  11487,
          10108,  35056,    119,  10377,  10266,  91823,  10107,  10491,  10197,
            117,  29997,  18927,  10106,  11339,    117,  10250,    117,  50776,
          10108,  18104,  10301,  10106,  11683,  17417,  51769,    119,  10117,
          11339,  11487,  10108,  18927,  10124,  10803,    117,  36427,  10841,
          10668,    118,  10635,    117,  81816,    117,  10111,  37770,    118,
          16108,  18927,  10301,  12742,    119,    102,      0,      0,      0,
              0,      0,      0,      0,      0,      0,      0,      0,      0,
              0,      0,      0,      0,      0,      0,      0,      0,      0,
              0,      0,      0,      0,      0,      0,      0,      0,      0,
              0,      0,      0,      0,      0,      0,      0,      0,      0,
              0,      0,      0,      0,      0,      0,      0,      0,      0,
              0,      0,      0,      0,      0,      0,      0,      0,      0,
              0,      0,      0,      0,      0,      0,      0,      0,      0,
              0,      0,      0,      0,      0,      0,      0,      0,      0,
              0,      0,      0,      0,      0,      0,      0,      0,      0,
              0,      0,      0,      0,      0,      0,      0,      0,      0,
              0,      0,      0,      0,      0,      0,      0,      0,      0,
              0,      0,      0,      0,      0,      0,      0,      0,      0,
              0,      0,      0,      0,      0,      0,      0,      0,      0,
              0,      0,      0,      0,      0,      0,      0,      0,      0,
              0,      0,      0,      0,      0,      0,      0,      0,      0,
              0,      0,      0,      0,      0,      0,      0,      0,      0,
              0,      0,      0,      0,      0,      0,      0,      0,      0,
              0,      0,      0,      0,      0,      0,      0,      0,      0,
              0,      0,      0,      0,      0,      0,      0,      0,      0,
              0,      0,      0,      0,      0,      0,      0,      0,      0,
              0,      0,      0,      0,      0,      0,      0,      0,      0,
              0,      0,      0,      0,      0,      0,      0,      0,      0,
              0,      0,      0,      0,      0,      0,      0,      0,      0,
              0,      0,      0,      0,      0,      0,      0,      0,      0,
              0,      0,      0,      0,      0,      0,      0,      0,      0,
              0,      0,      0,      0,      0,      0,      0,      0,      0,
              0,      0,      0,      0,      0,      0,      0,      0,      0,
              0,      0,      0,      0,      0,      0,      0,      0,      0,
              0,      0,      0,      0,      0,      0,      0,      0,      0,
              0,      0,      0,      0,      0,      0,      0,      0,      0,
              0,      0,      0,      0,      0,      0,      0,      0,      0,
              0,      0,      0,      0,      0,      0,      0,      0,      0,
              0,      0,      0,      0,      0,      0,      0,      0,      0,
              0,      0,      0,      0,      0,      0,      0,      0,      0,
              0,      0,      0,      0,      0,      0,      0,      0,      0,
              0,      0,      0,      0,      0,      0,      0,      0,      0,
              0,      0,      0,      0,      0,      0,      0,      0,      0,
              0,      0,      0,      0,      0,      0,      0,      0,      0,
              0,      0,      0,      0,      0,      0,      0,      0,      0,
              0,      0,      0,      0,      0,      0,      0,      0,      0,
              0,      0,      0,      0,      0,      0,      0,      0,      0,
              0,      0,      0,      0,      0,      0,      0,      0,      0,
              0,      0,      0,      0,      0,      0,      0,      0,      0,
              0,      0,      0,      0,      0,      0,      0,      0]),
 'attention_mask': tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0]),
 'token_type_ids': tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0]),
 'start_positions': tensor(17),
 'end_positions': tensor(22)}

In [29]:
df_train, df_val = get_data()

df_train = df_train[
    df_train["lang"].isin(["ar", "ko", "te"])
].copy()

df_val = df_val[
    df_val["lang"].isin(["ar", "ko", "te"])
].copy()

df_train["training_data"] = df_train.apply(
    make_training_data,
    axis=1,
)

df_val["training_data"] = df_val.apply(
    make_training_data,
    axis=1,
)

Found existing dataset at ./tydi_xor_rc. Loading from disk...
Loading completes.

In [30]:
train_data = df_train["training_data"].tolist()

train_loader = DataLoader(
    train_data,
    batch_size=4,
    shuffle=True,
)

val_data = df_val["training_data"].tolist()

val_loader = DataLoader(
    val_data,
    batch_size=4,
    shuffle=False,
)

## Train

In [31]:
import torch

device = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)

bert_model = bert_model.to(device)

print(device)

cuda

In [32]:
optimizer = torch.optim.AdamW(
    bert_model.parameters(),
    lr=2e-5,
    weight_decay=0.01,
)

In [33]:
BERT_MODEL_PATH = "./models/week40_berts"

def bert_train():
    NUM_EPOCHS = 1
    history = []

    bert_model.to(device)

    for epoch in range(NUM_EPOCHS):
        # Training
        bert_model.train()
        total_train_loss = 0.0

        progress_bar = tqdm(
            train_loader,
            desc=f"Epoch {epoch + 1}",
        )

        for batch in progress_bar:
            batch = {
                name: value.to(device)
                for name, value in batch.items()
            }

            optimizer.zero_grad()

            outputs = bert_model(**batch)
            loss = outputs.loss

            loss.backward()

            torch.nn.utils.clip_grad_norm_(
                bert_model.parameters(),
                max_norm=1.0,
            )

            optimizer.step()
            total_train_loss += loss.item()

            progress_bar.set_postfix(
                train_loss=loss.item()
            )

        average_train_loss = (
            total_train_loss / len(train_loader)
        )

        # Validation
        bert_model.eval()
        total_validation_loss = 0.0

        with torch.no_grad():
            for batch in val_loader:
                batch = {
                    name: value.to(device)
                    for name, value in batch.items()
                }

                outputs = bert_model(**batch)
                total_validation_loss += outputs.loss.item()

        average_validation_loss = (
            total_validation_loss / len(val_loader)
        )

        history.append({
            "epoch": epoch + 1,
            "train_loss": average_train_loss,
            "validation_loss": average_validation_loss,
        })

        print(
            f"Epoch {epoch + 1}: "
            f"train loss = {average_train_loss:.4f}, "
            f"validation loss = {average_validation_loss:.4f}"
        )

    bert_model.save_pretrained(BERT_MODEL_PATH)
    bert_tokenizer.save_pretrained(BERT_MODEL_PATH)

    return bert_model, bert_tokenizer, pd.DataFrame(history)

In [34]:
if os.path.exists(BERT_MODEL_PATH):
  bert_tokenizer = AutoTokenizer.from_pretrained(
      BERT_MODEL_PATH
  )

  bert_model = AutoModelForQuestionAnswering.from_pretrained(
      BERT_MODEL_PATH
  )
else:
  bert_model, bert_tokenizer = bert_train()

# bert_model, bert_tokenizer, training_history = bert_train()

# display(training_history)

# training_history.plot(
#     x="epoch",
#     y=["train_loss", "validation_loss"],
#     marker="o",
#     xticks=training_history["epoch"],
# )

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

## Evaluation Scores

In [35]:
def get_validation_scores(row):
    encoding = bert_tokenizer(
        row["question"],
        row["context"],
        max_length=512,
        truncation="only_second",
        padding="max_length",
        return_offsets_mapping=True,
        return_tensors="pt",
    )

    model_inputs = {
        "input_ids": encoding["input_ids"].to(device),
        "attention_mask": encoding["attention_mask"].to(device),
        "token_type_ids": encoding["token_type_ids"].to(device),
    }

    bert_model.eval()

    with torch.no_grad():
        outputs = bert_model(**model_inputs)

    start_logits = outputs.start_logits[0].cpu()
    end_logits = outputs.end_logits[0].cpu()

    input_ids = encoding["input_ids"][0]
    offsets = encoding["offset_mapping"][0].tolist()
    sequence_ids = encoding.sequence_ids(0)

    cls_span_score = (
        start_logits[0].item()
        + end_logits[0].item()
    )

    context_indices = [
        index
        for index, sequence_id in enumerate(sequence_ids)
        if sequence_id == 1
    ]

    best_span_score = float("-inf")
    best_start = None
    best_end = None

    for start_index in context_indices:
        for end_index in context_indices:
            if end_index < start_index:
                continue
            if end_index - start_index + 1 > 44:
                continue

            span_length = end_index - start_index + 1

            span_score = (
                start_logits[start_index].item()
                + end_logits[end_index].item()
            )

            if span_score > best_span_score:
                best_span_score = span_score
                best_start = start_index
                best_end = end_index

    char_start = offsets[best_start][0]
    char_end = offsets[best_end][1]

    best_span = row["context"][char_start:char_end]

    no_answer_score = cls_span_score - best_span_score

    return pd.Series({
        "cls_span_score": cls_span_score,
        "best_span_score": best_span_score,
        "no_answer_score": no_answer_score,
        "best_start_token": best_start,
        "best_end_token": best_end,
        "best_span": best_span,
    })

In [36]:
bert_model = bert_model.to(device)

validation_scores = df_val.apply(
    get_validation_scores,
    axis=1,
)

float_columns = [
    "cls_span_score",
    "best_span_score",
    "no_answer_score",
]

integer_columns = [
    "best_start_token",
    "best_end_token",
]

validation_scores[float_columns] = validation_scores[
    float_columns
].apply(
    pd.to_numeric,
    errors="raise",
)

validation_scores[integer_columns] = validation_scores[
    integer_columns
].apply(
    pd.to_numeric,
    errors="raise",
).astype("int64")

df_val = pd.concat(
    [df_val, validation_scores],
    axis=1,
)

In [ ]:
df_val.head()

,question,context,lang,answerable,answer_start,answer,answer_inlang,question_translated,training_data,cls_span_score,best_span_score,no_answer_score,best_start_token,best_end_token,best_span
0,ఒరెగాన్ రాష్ట్రంలోని అతిపెద్ద నగరం ఏది ?,Portland is the largest city in the U.S. state...,te,True,0,Portland,NaN,What is the largest city in the state of Oregon?,"{'input_ids': [tensor(101), tensor(1198), tens...",5.044863,2.353693,2.691170,114,114,Seattle
1,కలరా వ్యాధిని మొదటగా ఏ దేశంలో కనుగొన్నారు ?,"The word cholera is from ""kholera"" from χολή ""...",te,True,99,Indian subcontinent,NaN,In which country was cholera first discovered?,"{'input_ids': [tensor(101), tensor(1201), tens...",3.439209,3.860330,-0.421121,180,180,Indonesia
2,కలరా వ్యాధిని మొదటగా ఏ దేశంలో కనుగొన్నారు ?,Since it became widespread in the 19th century...,te,True,451,England,NaN,In which country was cholera first discovered?,"{'input_ids': [tensor(101), tensor(1201), tens...",3.880510,2.402852,1.477658,47,47,Russia
3,మొదటి ప్రపంచ యుద్ధం ఎప్పుడు మొదలయింది ?,World War I occurred from 1914 to 1918. In ter...,te,True,26,1914,NaN,When did World War I begin?,"{'input_ids': [tensor(101), tensor(54040), ten...",1.233079,11.721845,-10.488766,20,22,1914 to 1918
4,మొదటి ప్రపంచ యుద్ధం ఎప్పుడు మొదలయింది ?,"World War I (often abbreviated as WWI or WW1),...",te,True,155,28 July 1914,NaN,When did World War I begin?,"{'input_ids': [tensor(101), tensor(54040), ten...",1.303955,11.587665,-10.283710,56,58,28 July 1914

## Threshold Selection

In [37]:
import string

def squad_v2_normalize(text):
    text = text.lower()

    text = "".join(
        character
        for character in text
        if character not in string.punctuation
    )

    text = re.sub(r"\b(a|an|the)\b", " ", text)

    return " ".join(text.split())

def exact_match(prediction, gold):
    return float(squad_v2_normalize(prediction) == squad_v2_normalize(gold))

def token_f1(prediction, gold):
    prediction_tokens = squad_v2_normalize(prediction).split()
    gold_tokens = squad_v2_normalize(gold).split()

    if not prediction_tokens or not gold_tokens:
      return float(prediction_tokens == gold_tokens)

    overlap_number = sum((Counter(prediction_tokens) & Counter(gold_tokens)).values())

    if overlap_number == 0:
      return 0.0

    precision = overlap_number / len(prediction_tokens)
    recall = overlap_number / len(gold_tokens)

    return 2 * precision * recall / (precision + recall)

In [38]:
threshold_results = []

for threshold in np.arange(-50, 50, 0.1):
    predictions = [
        ""
        if score > threshold
        else str(best_span)
        for score, best_span in zip(
            df_val["no_answer_score"],
            df_val["best_span"],
        )
    ]

    f1_scores = [
        token_f1(prediction, gold)
        for prediction, gold in zip(
            predictions,
            df_val["answer"],
        )
    ]

    exact_scores = [
        exact_match(prediction, gold)
        for prediction, gold in zip(
            predictions,
            df_val["answer"],
        )
    ]

    unanswerable_exact_scores = [
        exact_match(prediction, gold)
        for prediction, gold, answer_start in zip(
            predictions,
            df_val["answer"],
            df_val["answer_start"],
        )
        if answer_start == -1
    ]

    gold_answerability = (df_val["answer_start"] != -1).astype(int).values
    predicted_answerability = np.array([int(p.strip() != "") for p in predictions])
    ans_macro_f1 = f1_score(
        gold_answerability,
        predicted_answerability,
        labels=[0, 1],
        average="macro",
        zero_division=0,
    )

    threshold_results.append({
        "threshold": threshold,
        "ans_macro_f1": ans_macro_f1,
        "token_f1": np.mean(f1_scores),
        "exact_match": np.mean(exact_scores),
        "unanswerable_exact_match": np.mean(unanswerable_exact_scores),
    })

In [39]:
best_result = max(
    threshold_results,
    key=lambda result: (result["ans_macro_f1"], result["token_f1"]),
)

best_threshold = best_result["threshold"]

print("Best threshold:", best_threshold)
print("Validation answerability macro-F1:", best_result["ans_macro_f1"])
print("Validation token F1:", best_result["token_f1"])
print("Validation exact match:", best_result["exact_match"])
print("Validation unanswerable exact match:", best_result["unanswerable_exact_match"])

Best threshold: 3.5000000000007603
Validation answerability macro-F1: 0.7881002575153109
Validation token F1: 0.5330843482548085
Validation exact match: 0.44155844155844154
Validation unanswerable exact match: 0.018292682926829267

# Week 43

## Extension 1: Zero-shot transfer to Japanese

In [40]:
df_train, df_val = get_data()

df_train_ja = df_train[
    df_train["lang"] == "ja"
].copy()

df_val_ja = df_val[
    df_val["lang"] == "ja"
].copy()

Found existing dataset at ./tydi_xor_rc. Loading from disk...
Loading completes.

In [41]:
bert_model = bert_model.to(device)

validation_scores = df_val_ja.apply(
    get_validation_scores,
    axis=1,
)

float_columns = [
    "cls_span_score",
    "best_span_score",
    "no_answer_score",
]

integer_columns = [
    "best_start_token",
    "best_end_token",
]

validation_scores[float_columns] = validation_scores[
    float_columns
].apply(
    pd.to_numeric
)

validation_scores[integer_columns] = validation_scores[
    integer_columns
].apply(
    pd.to_numeric
).astype("int64")

df_val_ja = pd.concat(
    [df_val_ja, validation_scores],
    axis=1,
)

In [44]:
df_val_ja.head()

,question,context,lang,answerable,answer_start,answer,answer_inlang,question_translated,cls_span_score,best_span_score,no_answer_score,best_start_token,best_end_token,best_span
332,月の地表の温度は何度,An underground colony would escape the extreme...,ja,True,145,−5 °C,NaN,NaN,0.529623,10.206463,-9.676840,39,41,−5 °C
333,ポリマーを発見したのは誰,The work of Henri Braconnot in 1777 and the wo...,ja,True,12,Henri Braconnot,NaN,NaN,0.691921,10.318582,-9.626660,14,17,Henri Braconnot
334,西洋のクラシック音楽が日本に伝来したのはいつ,Shuji Isawa (1851-1917) studied music at Bridg...,ja,True,192,1868,NaN,NaN,-1.683982,-2.134587,0.450605,21,62,Shuji Isawa (1851-1917) studied music at Bridg...
335,相撲部屋を新しく作るには、どのような資格が必要ですか？,"The number of stables peaked at 54, with the o...",ja,True,253,former wrestlers wishing to branch out (namely...,NaN,NaN,3.860492,1.558719,2.301772,59,62,Japan Sumo Association
336,日本最初の眼科医は誰,"Tsutomu Sato (1902 - June 9, 1960) was a Japan...",ja,True,0,Tsutomu Sato,NaN,NaN,-0.018870,13.124755,-13.143625,12,15,Tsutomu Sato

In [42]:
predictions = [
    ""
    if score > best_threshold
    else str(best_span)
    for score, best_span in zip(
        df_val_ja["no_answer_score"],
        df_val_ja["best_span"],
    )
]

f1_scores = [
    token_f1(prediction, gold)
    for prediction, gold in zip(
        predictions,
        df_val_ja["answer"],
    )
]

exact_scores = [
    exact_match(prediction, gold)
    for prediction, gold in zip(
        predictions,
        df_val_ja["answer"],
    )
]

unanswerable_exact_scores = [
    exact_match(prediction, gold)
    for prediction, gold, answer_start in zip(
        predictions,
        df_val_ja["answer"],
        df_val_ja["answer_start"],
    )
    if answer_start == -1
]

gold_answerability = (df_val_ja["answer_start"] != -1).astype(int).values
predicted_answerability = np.array([int(p.strip() != "") for p in predictions])
ans_macro_f1 = f1_score(
    gold_answerability,
    predicted_answerability,
    labels=[0, 1],
    average="macro",
    zero_division=0,
)

{
    "threshold": best_threshold,
    "ans_macro_f1": ans_macro_f1,
    "token_f1": np.mean(f1_scores),
    "exact_match": np.mean(exact_scores),
    "unanswerable_exact_match": np.mean(unanswerable_exact_scores),
}

{'threshold': np.float64(3.5000000000007603),
 'ans_macro_f1': 0.6473232628398791,
 'token_f1': np.float64(0.35271253120176516),
 'exact_match': np.float64(0.2807017543859649),
 'unanswerable_exact_match': np.float64(0.01775147928994083)}

## Extension 2: Alternative span architecture

### Setup

In [ ]:
import torch, torch.nn as nn, torch.nn.functional as F
from transformers import AutoModel

In [ ]:
device = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)

print(device)

cuda

In [ ]:
MODEL_NAME = "google-bert/bert-base-multilingual-cased"

In [ ]:
bert_tokenizer = AutoTokenizer.from_pretrained(
    MODEL_NAME,
    use_fast=True,
)

### Model

In [ ]:
class BiaffinneHeadQA(nn.Module):
  def __init__(self, model_name, dim_projs=8, max_predicted_span=64):
    super().__init__()

    self.encoder = AutoModel.from_pretrained(model_name)
    h_dim = self.encoder.config.hidden_size # encoder contextual embedding dim size (= 768)

    self.S = nn.Sequential(nn.Linear(h_dim, dim_projs), nn.GELU())
    self.E = nn.Sequential(nn.Linear(h_dim, dim_projs), nn.GELU())

    self.U = nn.Parameter(torch.empty(dim_projs,dim_projs))
    nn.init.xavier_uniform_(self.U)

    self.W_s = nn.Linear(dim_projs, 1)
    self.W_e = nn.Linear(dim_projs, 1, bias=False)

    self.max_predicted_span = max_predicted_span


  def span_scores(self, input_ids, attention_mask, token_type_ids):
    h = self.encoder(
        input_ids=input_ids,
        attention_mask=attention_mask,
        token_type_ids=token_type_ids
    ).last_hidden_state

    s = self.S(h)
    e = self.E(h)

    bilinear = (s @ self.U) @ (e.transpose(1,2))

    start = self.W_s(s)
    end = self.W_e(e).transpose(1,2)

    return bilinear + start + end

  def mask_scores(self,scores, attention_mask, token_type_ids):
    B, T, _ = scores.shape

    pos = (token_type_ids == 1) & (attention_mask == 1)

    # mask [SEP] context token
    last = attention_mask.sum(dim=1) - 1
    pos[torch.arange(B, device=scores.device), last] = False

    idx = torch.arange(T, device=scores.device)
    diff = idx.unsqueeze(0) - idx.unsqueeze(-1)
    band = (diff >= 0) & (diff < self.max_predicted_span)

    valid = band.unsqueeze(0) & pos.unsqueeze(1) & pos.unsqueeze(2)
    valid[:, 0, 0] = True

    return scores.masked_fill(~valid, -1e4)



  def forward(self, input_ids, attention_mask, token_type_ids,
              start_positions=None, end_positions=None):
    scores = self.span_scores(input_ids, attention_mask, token_type_ids)
    scores = self.mask_scores(scores, attention_mask, token_type_ids)
    out = {"scores": scores}
    if start_positions is not None:
      T = scores.size(dim=1)
      out["loss"] = F.cross_entropy(scores.flatten(1),
                                    start_positions*T + end_positions)
    return out

### Data processing

In [ ]:
def make_training_data(row):

    encoding = bert_tokenizer(
        row["question"],
        row["context"],
        max_length=512,
        truncation="only_second",
        padding="max_length",
        return_offsets_mapping=True,
        return_tensors="pt",
    )
    answer = row["answer"]
    answer_start = row["answer_start"]

    input_ids = encoding["input_ids"][0]
    offsets = encoding["offset_mapping"][0].tolist()
    sequence_ids = encoding.sequence_ids(0)

    start_position = 0
    end_position = 0

    if answer_start != -1:
        answer_end = answer_start + len(answer)

        answer_token_indices = []

        for token_index, (offset, sequence_id) in enumerate(
            zip(offsets, sequence_ids)
        ):
            token_start, token_end = offset

            if (
                sequence_id == 1
                and token_end > answer_start
                and token_start < answer_end
            ):
                answer_token_indices.append(token_index)

        if answer_token_indices:
            start_position = answer_token_indices[0]
            end_position = answer_token_indices[-1]

    return {
        "input_ids": input_ids,
        "attention_mask": encoding["attention_mask"][0],
        "token_type_ids": encoding["token_type_ids"][0],
        "start_positions": torch.tensor(start_position),
        "end_positions": torch.tensor(end_position),
    }

In [ ]:
result = make_training_data(df_train.iloc[3])
print(df_train.iloc[3])
result

question               আরব-ইসরায়েলি যুদ্ধে আরবের মোট কয়জন সৈন্যের মৃ...
context                The exact number of Arab casualties is unknown...
lang                                                                  bn
answerable                                                          True
answer_start                                                          39
answer                                                           unknown
answer_inlang                                                        NaN
question_translated                                                  NaN
Name: 3, dtype: object

{'input_ids': tensor([   101,  46085,  19910,    118,    939,  98410,  29484,  42620,  12235,
         107531,  11199,  46085, 100047,  96134,    100,    978, 111238,  11737,
          50263,    972,  45908,  15215,  16166,    100,    136,    102,  10117,
          45809,  11487,  10108,  17365,  69297,  10124,  27306,    119,  11340,
          78059,  19261,  10105,  17365,  12557,  81754,  10160,    128,    117,
          10259,    117,  11198,    124,    117,  10259,  56119,  10107,    117,
            123,    117,  10259,  34624,  10107,    117,    122,    117,  10259,
          16366,  34615,    117,  10111,    122,    117,  10259,  44152,  10107,
            119,  10167,  10947,    117,  56119,  27914,  13491,  10575,  10164,
            118,  13491,  10575,  87382,  10189,  10105,  17365,  84773,    112,
          25302,  45353,  24074,  10336,  10114,    124,    117,  12367,    117,
          10169,  20440,  27817,  72488,  15670,  10111,  10777,  55143,  23324,
          10111,  16366,  27817,  37257,  15670,  10107,  10111,  10777,  55143,
          10107,    119,  14156,  10114,  11601,  41712,  10107,    117,  10105,
          56119,  10107,  26090,  15790,  10105,  17119,  45353,    117,  10169,
          10249,    117,  10259,  23457,    117,    122,    117,  35112,  10108,
          18104,  10301,  11053,  10114,  10529,  12482,  10106,  18159,  52844,
            119,  12610,  10105,  50308,    117,    125,    117,  44827,  25430,
          11324,  14985,  10473,  10105,  11192,    117,  36243,  10157,  10111,
          13664,  10108,  10455,  12557,  10124,  11053,    117,  10111,    169,
          14586,    128,    117, 104367,    117,  10142,  18104,  10893,  10105,
          11192,  10108,  12557,  10124,  11053,    117,  10472,  10455,  38938,
          12752,  14197,  31515,  10105,  13664,  10108,  10455,  12557,    119,
          14156,  10114,  41712,  10107,    117,  10105,  15363,  10668,  10108,
          56119,  69297,  31465,  10108,  10446,    118,  18159,  22595,  10111,
          42996,  10107,  10114,  10105,  17330,  18356,  10108,  10105,  28446,
          10107,    119,    102,      0,      0,      0,      0,      0,      0,
              0,      0,      0,      0,      0,      0,      0,      0,      0,
              0,      0,      0,      0,      0,      0,      0,      0,      0,
              0,      0,      0,      0,      0,      0,      0,      0,      0,
              0,      0,      0,      0,      0,      0,      0,      0,      0,
              0,      0,      0,      0,      0,      0,      0,      0,      0,
              0,      0,      0,      0,      0,      0,      0,      0,      0,
              0,      0,      0,      0,      0,      0,      0,      0,      0,
              0,      0,      0,      0,      0,      0,      0,      0,      0,
              0,      0,      0,      0,      0,      0,      0,      0,      0,
              0,      0,      0,      0,      0,      0,      0,      0,      0,
              0,      0,      0,      0,      0,      0,      0,      0,      0,
              0,      0,      0,      0,      0,      0,      0,      0,      0,
              0,      0,      0,      0,      0,      0,      0,      0,      0,
              0,      0,      0,      0,      0,      0,      0,      0,      0,
              0,      0,      0,      0,      0,      0,      0,      0,      0,
              0,      0,      0,      0,      0,      0,      0,      0,      0,
              0,      0,      0,      0,      0,      0,      0,      0,      0,
              0,      0,      0,      0,      0,      0,      0,      0,      0,
              0,      0,      0,      0,      0,      0,      0,      0,      0,
              0,      0,      0,      0,      0,      0,      0,      0,      0,
              0,      0,      0,      0,      0,      0,      0,      0,      0,
              0,      0,      0,      0,      0,      0,      0,      0,      0,
              0,      0,      0,      0,      0,      0,      0,      0,      0,
              0,      0,      0,      0,      0,      0,      0,      0,      0,
              0,      0,      0,      0,      0,      0,      0,      0,      0,
              0,      0,      0,      0,      0,      0,      0,      0,      0,
              0,      0,      0,      0,      0,      0,      0,      0,      0,
              0,      0,      0,      0,      0,      0,      0,      0,      0,
              0,      0,      0,      0,      0,      0,      0,      0,      0,
              0,      0,      0,      0,      0,      0,      0,      0]),
 'attention_mask': tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0]),
 'token_type_ids': tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0]),
 'start_positions': tensor(33),
 'end_positions': tensor(33)}

In [ ]:
df_train = df_train[
    df_train["lang"].isin(["ar", "ko", "te"])
].copy()

df_val = df_val[
    df_val["lang"].isin(["ar", "ko", "te"])
].copy()

df_train["training_data"] = df_train.apply(
    make_training_data,
    axis=1,
)

df_val["training_data"] = df_val.apply(
    make_training_data,
    axis=1,
)

In [ ]:
# max answer token length - training data
df_train["answer_span_length"] = df_train.apply(
    lambda row : (row["training_data"]["end_positions"] - row["training_data"]["start_positions"]).item(),
    axis = 1
)
df_train["answer_span_length"].describe()

count    6335.000000
mean        3.611365
std         5.696475
min         0.000000
25%         0.000000
50%         2.000000
75%         4.000000
max        63.000000
Name: answer_span_length, dtype: float64

In [ ]:
# max answer token length - validation data
df_val["answer_span_length"] = df_val.apply(
    lambda row : (row["training_data"]["end_positions"] - row["training_data"]["start_positions"]).item(),
    axis = 1
)
df_val["answer_span_length"].describe()

count    1155.000000
mean        3.030303
std         5.469938
min         0.000000
25%         0.000000
50%         1.000000
75%         3.000000
max        44.000000
Name: answer_span_length, dtype: float64

In [ ]:
train_data = df_train["training_data"].tolist()

train_loader = DataLoader(
    train_data,
    batch_size=4,
    shuffle=True,
)

val_data = df_val["training_data"].tolist()

val_loader = DataLoader(
    val_data,
    batch_size=4,
    shuffle=False,
)

### Training

In [ ]:
bqa_model_toTrain = BiaffinneHeadQA(MODEL_NAME).to(device)

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertModel LOAD REPORT from: google-bert/bert-base-multilingual-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [ ]:
for n, p in bqa_model_toTrain.named_parameters():
    if not n.startswith("encoder."):
        print(n, tuple(p.shape))

U (8, 8)
S.0.weight (8, 768)
S.0.bias (8,)
E.0.weight (8, 768)
E.0.bias (8,)
W_s.weight (1, 8)
W_s.bias (1,)
W_e.weight (1, 8)

In [ ]:
total_params = sum(p.numel() for p in bqa_model_toTrain.parameters())
print(f"Number of parameters: {total_params}")

Number of parameters: 177865825

In [ ]:
BQA_MODEL_PATH = "./models_week43/BQA_extension_model"

os.makedirs(os.path.dirname(BQA_MODEL_PATH), exist_ok=True)

def bqa_train(model):
  NUM_EPOCHS = 1
  history = []

  head_params = [p for n, p in model.named_parameters() if not n.startswith("encoder.")]
  enc_params  = [p for n, p in model.named_parameters() if n.startswith("encoder.")]
  optimizer = torch.optim.AdamW([
      {"params": enc_params,  "lr": 2e-5},
      {"params": head_params, "lr": 1e-3, "weight_decay": 0.0},
  ], weight_decay=0.01)

  # initial validation loss
  model.eval()
  total_initial_validation_loss = 0.0

  with torch.no_grad():
      for batch in val_loader:
          batch = {
              name: value.to(device)
              for name, value in batch.items()
          }

          initial_outputs = model(**batch)
          total_initial_validation_loss += initial_outputs["loss"]

  initial_validation_loss = (
      total_initial_validation_loss / len(val_loader)
  )

  print(f"Pre-training validation loss = {initial_validation_loss:.4f}")

  for epoch in range(NUM_EPOCHS):
      # Training
      model.train()
      total_train_loss = 0

      progress_bar = tqdm(
          train_loader,
          desc=f"Epoch {epoch + 1}",
      )

      for batch in progress_bar:
          batch = {
              name: value.to(device)
              for name, value in batch.items()
          }

          optimizer.zero_grad()

          outputs = model(**batch)
          loss = outputs["loss"]

          loss.backward()

          optimizer.step()

          total_train_loss += loss.item()

          progress_bar.set_postfix(
                train_loss=loss.item()
          )

      average_train_loss = (
          total_train_loss / len(train_loader)
      )

      # Validation
      model.eval()
      total_validation_loss = 0.0

      with torch.no_grad():
          for batch in val_loader:
              batch = {
                  name: value.to(device)
                  for name, value in batch.items()
              }

              outputs = model(**batch)
              total_validation_loss += outputs["loss"]

      average_validation_loss = (
          total_validation_loss / len(val_loader)
      )

      history.append({
          "epoch": epoch + 1,
          "train_loss": average_train_loss,
          "validation_loss": average_validation_loss,
      })

      print(
          f"Epoch {epoch + 1}: "
          f"train loss = {average_train_loss:.4f}, "
          f"validation loss = {average_validation_loss:.4f}"
      )

      # Save model after each epoch
      checkpoint_path = f"{BQA_MODEL_PATH}_epoch_{epoch + 1}.pth"
      torch.save(model.state_dict(), checkpoint_path)

  checkpoint_path = f"{BQA_MODEL_PATH}.pth"
  torch.save(model.state_dict(), checkpoint_path)

  return model, bert_tokenizer, pd.DataFrame(history)

In [ ]:
if not os.path.exists(f"{BQA_MODEL_PATH}.pth"):
  bqa_model, bert_tokenizer, training_history = bqa_train(bqa_model_toTrain)
  display(training_history)

In [ ]:
if os.path.exists(f"{BQA_MODEL_PATH}.pth"):
  state_dict = torch.load(f"{BQA_MODEL_PATH}.pth", weights_only=True)
  bqa_model = BiaffinneHeadQA(MODEL_NAME).to(device)
  bqa_model.load_state_dict(state_dict)

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertModel LOAD REPORT from: google-bert/bert-base-multilingual-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

### Evaluation

In [ ]:
def get_validation_scores(row, model=bqa_model):
    encoding = bert_tokenizer(
        row["question"],
        row["context"],
        max_length=512,
        truncation="only_second",
        padding="max_length",
        return_offsets_mapping=True,
        return_tensors="pt",
    )

    model_inputs = {
        "input_ids": encoding["input_ids"].to(device),
        "attention_mask": encoding["attention_mask"].to(device),
        "token_type_ids": encoding["token_type_ids"].to(device),
    }

    model.eval()

    with torch.no_grad():
        outputs = model(**model_inputs)

    scores = outputs["scores"].squeeze(dim=0)

    input_ids = encoding["input_ids"][0]
    offsets = encoding["offset_mapping"][0].tolist()
    sequence_ids = encoding.sequence_ids(0)

    cls_span_score = scores[0,0]

    scores_ = scores.clone()
    scores_[0,0] = float("-inf")
    idx = torch.argmax(scores_)
    r,c = torch.unravel_index(idx, scores_.shape)

    best_span_score = scores_[r,c]
    best_start = r.item()
    best_end = c.item()

    char_start = offsets[best_start][0]
    char_end = offsets[best_end][1]

    best_span = row["context"][char_start:char_end]

    no_answer_score = cls_span_score - best_span_score

    return pd.Series({
        "cls_span_score": cls_span_score.item(),
        "best_span_score": best_span_score.item(),
        "no_answer_score": no_answer_score.item(),
        "best_start_token": best_start,
        "best_end_token": best_end,
        "best_span": best_span,
    })

In [ ]:
id = 439

print(df_train.iloc[id])
get_validation_scores(df_train.iloc[id])

question                                                달의 지름은 몇 키로미터인가?
context                The Moon's average orbital distance is , or 1....
lang                                                                  ko
answerable                                                          True
answer_start                                                          44
answer                                                1.28 light-seconds
answer_inlang                                                        NaN
question_translated     How many kilometers is the diameter of the moon?
training_data          {'input_ids': [tensor(101), tensor(9061), tens...
answer_span_length                                                     5
Name: 5231, dtype: object

cls_span_score                 0.84836
best_span_score               7.896226
no_answer_score              -7.047866
best_start_token                    25
best_end_token                      30
best_span           1.28 light-seconds
dtype: object

In [ ]:
bqa_model = bqa_model.to(device)

validation_scores = df_val.apply(
    get_validation_scores,
    axis=1,
)

float_columns = [
    "cls_span_score",
    "best_span_score",
    "no_answer_score",
]

integer_columns = [
    "best_start_token",
    "best_end_token",
]

validation_scores[float_columns] = validation_scores[
    float_columns
].apply(
    pd.to_numeric,
    errors="raise",
)

validation_scores[integer_columns] = validation_scores[
    integer_columns
].apply(
    pd.to_numeric,
    errors="raise",
).astype("int64")

df_val = pd.concat(
    [df_val, validation_scores],
    axis=1,
)

In [ ]:
df_val.head()

,question,context,lang,answerable,answer_start,answer,answer_inlang,question_translated,training_data,answer_span_length,cls_span_score,best_span_score,no_answer_score,best_start_token,best_end_token,best_span
0,ఒరెగాన్ రాష్ట్రంలోని అతిపెద్ద నగరం ఏది ?,Portland is the largest city in the U.S. state...,te,True,0,Portland,NaN,What is the largest city in the state of Oregon?,"{'input_ids': [tensor(101), tensor(1198), tens...",0,0.658845,4.679156,-4.020311,20,20,Portland
1,కలరా వ్యాధిని మొదటగా ఏ దేశంలో కనుగొన్నారు ?,"The word cholera is from ""kholera"" from χολή ""...",te,True,99,Indian subcontinent,NaN,In which country was cholera first discovered?,"{'input_ids': [tensor(101), tensor(1201), tens...",3,0.308296,5.902933,-5.594637,180,180,Indonesia
2,కలరా వ్యాధిని మొదటగా ఏ దేశంలో కనుగొన్నారు ?,Since it became widespread in the 19th century...,te,True,451,England,NaN,In which country was cholera first discovered?,"{'input_ids': [tensor(101), tensor(1201), tens...",0,0.580539,6.151104,-5.570565,47,47,Russia
3,మొదటి ప్రపంచ యుద్ధం ఎప్పుడు మొదలయింది ?,World War I occurred from 1914 to 1918. In ter...,te,True,26,1914,NaN,When did World War I begin?,"{'input_ids': [tensor(101), tensor(54040), ten...",0,1.209456,9.445196,-8.235740,20,20,1914
4,మొదటి ప్రపంచ యుద్ధం ఎప్పుడు మొదలయింది ?,"World War I (often abbreviated as WWI or WW1),...",te,True,155,28 July 1914,NaN,When did World War I begin?,"{'input_ids': [tensor(101), tensor(54040), ten...",2,1.064779,9.039950,-7.975172,56,58,28 July 1914

In [ ]:
df_val["no_answer_score"].describe()

count    1155.000000
mean       -4.824213
std         3.063245
min       -10.430193
25%        -7.015365
50%        -5.470097
75%        -3.075328
max         5.156090
Name: no_answer_score, dtype: float64

In [ ]:
import string

def squad_v2_normalize(text):
    text = text.lower()

    text = "".join(
        character
        for character in text
        if character not in string.punctuation
    )

    text = re.sub(r"\b(a|an|the)\b", " ", text)

    return " ".join(text.split())

def exact_match(prediction, gold):
    return float(squad_v2_normalize(prediction) == squad_v2_normalize(gold))

def token_f1(prediction, gold):
    prediction_tokens = squad_v2_normalize(prediction).split()
    gold_tokens = squad_v2_normalize(gold).split()

    if not prediction_tokens or not gold_tokens:
      return float(prediction_tokens == gold_tokens)

    overlap_number = sum((Counter(prediction_tokens) & Counter(gold_tokens)).values())

    if overlap_number == 0:
      return 0.0

    precision = overlap_number / len(prediction_tokens)
    recall = overlap_number / len(gold_tokens)

    return 2 * precision * recall / (precision + recall)

In [ ]:
threshold_results = []

for threshold in np.arange(-15, 10, 0.1):
    predictions = [
        ""
        if score > threshold
        else str(best_span)
        for score, best_span in zip(
            df_val["no_answer_score"],
            df_val["best_span"],
        )
    ]

    f1_scores = [
        token_f1(prediction, gold)
        for prediction, gold in zip(
            predictions,
            df_val["answer"],
        )
    ]

    exact_scores = [
        exact_match(prediction, gold)
        for prediction, gold in zip(
            predictions,
            df_val["answer"],
        )
    ]

    unanswerable_exact_scores = [
        exact_match(prediction, gold)
        for prediction, gold, answer_start in zip(
            predictions,
            df_val["answer"],
            df_val["answer_start"],
        )
        if answer_start == -1
    ]

    gold_answerability = (df_val["answer_start"] != -1).astype(int).values
    predicted_answerability = np.array([int(p.strip() != "") for p in predictions])
    ans_macro_f1 = f1_score(
        gold_answerability,
        predicted_answerability,
        labels=[0, 1],
        average="macro",
        zero_division=0,
    )

    threshold_results.append({
        "threshold": threshold,
        "ans_macro_f1": ans_macro_f1,
        "token_f1": np.mean(f1_scores),
        "exact_match": np.mean(exact_scores),
        "unanswerable_exact_match": np.mean(unanswerable_exact_scores),
    })

In [ ]:
best_result = max(
    threshold_results,
    key=lambda result: (result["ans_macro_f1"], result["token_f1"]),
)

best_threshold = best_result["threshold"]

print("Best threshold:", best_threshold)
print("Validation answerability macro-F1:", best_result["ans_macro_f1"])
print("Validation token F1:", best_result["token_f1"])
print("Validation exact match:", best_result["exact_match"])
print("Validation unanswerable exact match:", best_result["unanswerable_exact_match"])

Best threshold: -1.3000000000000487
Validation answerability macro-F1: 0.757428779793256
Validation token F1: 0.552088104155859
Validation exact match: 0.4683982683982684
Validation unanswerable exact match: 0.042682926829268296

In [ ]:
# character span length
df_val["best_span_length"] = df_val.apply(
    lambda row : len(row["best_span"]),
    axis=1
)
df_val["best_span_length"].describe()

count    1155.000000
mean       16.188745
std        16.978344
min         1.000000
25%         6.000000
50%        12.000000
75%        19.000000
max       176.000000
Name: best_span_length, dtype: float64

## Extension 3: Translating questions to English

### Tokenizer and Model

In [ ]:
MODEL_NAME = "google-bert/bert-base-multilingual-cased"

bert_tokenizer_eng = AutoTokenizer.from_pretrained(
    MODEL_NAME,
    use_fast=True,
)

bert_model_eng = AutoModelForQuestionAnswering.from_pretrained(
    MODEL_NAME
)

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] BertForQuestionAnswering LOAD REPORT from: google-bert/bert-base-multilingual-cased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.seq_relationship.bias                  | UNEXPECTED |
bert.pooler.dense.bias                     | UNEXPECTED |
bert.pooler.dense.weight                   | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
qa_outputs.bias                            | MISSING    |
qa_outputs.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

### Data processing

In [ ]:
import torch
import pandas as pd

def make_training_data(row):

    encoding = bert_tokenizer_eng(
        row["question_translated"],
        row["context"],
        max_length=512,
        truncation="only_second",
        padding="max_length",
        return_offsets_mapping=True,
        return_tensors="pt",
    )
    answer = row["answer"]
    answer_start = row["answer_start"]

    input_ids = encoding["input_ids"][0]
    offsets = encoding["offset_mapping"][0].tolist()
    sequence_ids = encoding.sequence_ids(0)

    start_position = 0
    end_position = 0

    if answer_start != -1:
        answer_end = answer_start + len(answer)

        answer_token_indices = []

        for token_index, (offset, sequence_id) in enumerate(
            zip(offsets, sequence_ids)
        ):
            token_start, token_end = offset

            if (
                sequence_id == 1
                and token_end > answer_start
                and token_start < answer_end
            ):
                answer_token_indices.append(token_index)

        if answer_token_indices:
            start_position = answer_token_indices[0]
            end_position = answer_token_indices[-1]

    return {
        "input_ids": input_ids,
        "attention_mask": encoding["attention_mask"][0],
        "token_type_ids": encoding["token_type_ids"][0],
        "start_positions": torch.tensor(start_position),
        "end_positions": torch.tensor(end_position),
    }

In [ ]:
df_train = df_train[
    df_train["lang"].isin(["ar", "ko", "te"])
].copy()

df_val = df_val[
    df_val["lang"].isin(["ar", "ko", "te"])
].copy()

df_train["training_data_eng"] = df_train.apply(
    make_training_data,
    axis=1,
)

In [ ]:
df_train.head()

,question,context,lang,answerable,answer_start,answer,answer_inlang,question_translated,training_data_eng
4792,30년 전쟁의 승자는 누구인가?,The conflict between France and Spain continue...,ko,True,21,France,NaN,Who is the winner of the Thirty Years' War?,"{'input_ids': [tensor(101), tensor(14516), ten..."
4793,엑스선은 누가 발견하였는가?,"X-rays make up X-radiation, a form of electrom...",ko,True,503,Wilhelm Röntgen,NaN,Who discovered the X-ray?,"{'input_ids': [tensor(101), tensor(14516), ten..."
4794,아테네에서 언제 가장 최근의 올림픽이 올렸나요?,"In 2022, Beijing will become the first-ever ci...",ko,True,188,2004,NaN,When was the last time the Olympics were held ...,"{'input_ids': [tensor(101), tensor(12242), ten..."
4795,세상에서 가장 오래된 방송사는 무엇인가?,The British Broadcasting Corporation (BBC) is ...,ko,True,4,British Broadcasting Corporation (BBC),NaN,What's the oldest broadcaster in the world?,"{'input_ids': [tensor(101), tensor(12489), ten..."
4796,팔레스타인 수도는 어딘가요?,"Palestine ( '), officially the State of Palest...",ko,True,205,Jerusalem,NaN,Where is the Palestinian capital?,"{'input_ids': [tensor(101), tensor(23525), ten..."

In [ ]:
train_data_eng = df_train["training_data_eng"].tolist()

train_loader_eng = DataLoader(
    train_data_eng,
    batch_size=4,
    shuffle=True,
)

df_val["training_data_eng"] = df_val.apply(
    make_training_data,
    axis=1,
)

val_data_eng = df_val["training_data_eng"].tolist()

val_loader_eng = DataLoader(
    val_data_eng,
    batch_size=4,
    shuffle=False,
)

### Train

In [ ]:
import torch

device = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)

bert_model_eng = bert_model_eng.to(device)

print(device)

cpu

In [ ]:
optimizer_eng = torch.optim.AdamW(
    bert_model_eng.parameters(),
    lr=2e-5,
    weight_decay=0.01,
)

In [ ]:
BERT_MODEL_PATH_ENG = "./models/week40_berts_eng"

os.makedirs(os.path.dirname(BERT_MODEL_PATH_ENG), exist_ok=True)

def bert_train_eng():
    NUM_EPOCHS = 1
    history = []

    bert_model_eng.to(device)

    for epoch in range(NUM_EPOCHS):
        # Training
        bert_model_eng.train()
        total_train_loss = 0.0

        progress_bar = tqdm(
            train_loader_eng,
            desc=f"Epoch {epoch + 1}",
        )

        for batch in progress_bar:
            batch = {
                name: value.to(device)
                for name, value in batch.items()
            }

            optimizer_eng.zero_grad()

            outputs = bert_model_eng(**batch)
            loss = outputs.loss

            loss.backward()

            torch.nn.utils.clip_grad_norm_(
                bert_model_eng.parameters(),
                max_norm=1.0,
            )

            optimizer_eng.step()
            total_train_loss += loss.item()

            progress_bar.set_postfix(
                train_loss=loss.item()
            )

        average_train_loss = (
            total_train_loss / len(train_loader_eng)
        )

        # Validation
        bert_model_eng.eval()
        total_validation_loss = 0.0

        with torch.no_grad():
            for batch in val_loader_eng:
                batch = {
                    name: value.to(device)
                    for name, value in batch.items()
                }

                outputs = bert_model_eng(**batch)
                total_validation_loss += outputs.loss.item()

        average_validation_loss = (
            total_validation_loss / len(val_loader_eng)
        )

        history.append({
            "epoch": epoch + 1,
            "train_loss": average_train_loss,
            "validation_loss": average_validation_loss,
        })

        print(
            f"Epoch {epoch + 1}: "
            f"train loss = {average_train_loss:.4f}, "
            f"validation loss = {average_validation_loss:.4f}"
        )

    bert_model_eng.save_pretrained(BERT_MODEL_PATH_ENG)
    bert_tokenizer_eng.save_pretrained(BERT_MODEL_PATH_ENG)

    return bert_model_eng, bert_tokenizer_eng, pd.DataFrame(history)

In [ ]:
if os.path.exists(BERT_MODEL_PATH_ENG):
  bert_tokenizer_eng = AutoTokenizer.from_pretrained(
      BERT_MODEL_PATH_ENG
  )

  bert_model_eng = AutoModelForQuestionAnswering.from_pretrained(
      BERT_MODEL_PATH_ENG
  )
else:
  bert_model_eng, bert_tokenizer_eng, training_history_eng = bert_train_eng()

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

### Evaluation Scores

In [ ]:
def get_validation_scores_eng(row):
    encoding = bert_tokenizer_eng(
        row["question_translated"],
        row["context"],
        max_length=512,
        truncation="only_second",
        padding="max_length",
        return_offsets_mapping=True,
        return_tensors="pt",
    )

    model_inputs = {
        "input_ids": encoding["input_ids"].to(device),
        "attention_mask": encoding["attention_mask"].to(device),
        "token_type_ids": encoding["token_type_ids"].to(device),
    }

    bert_model_eng.eval()

    with torch.no_grad():
        outputs = bert_model_eng(**model_inputs)

    start_logits = outputs.start_logits[0].cpu()
    end_logits = outputs.end_logits[0].cpu()

    input_ids = encoding["input_ids"][0]
    offsets = encoding["offset_mapping"][0].tolist()
    sequence_ids = encoding.sequence_ids(0)

    cls_span_score = (
        start_logits[0].item()
        + end_logits[0].item()
    )

    context_indices = [
        index
        for index, sequence_id in enumerate(sequence_ids)
        if sequence_id == 1
    ]

    best_span_score = float("-inf")
    best_start = None
    best_end = None

    for start_index in context_indices:
        for end_index in context_indices:
            if end_index < start_index:
                continue
            if end_index - start_index + 1 > 44:
                continue

            span_length = end_index - start_index + 1

            span_score = (
                start_logits[start_index].item()
                + end_logits[end_index].item()
            )

            if span_score > best_span_score:
                best_span_score = span_score
                best_start = start_index
                best_end = end_index

    char_start = offsets[best_start][0]
    char_end = offsets[best_end][1]

    best_span = row["context"][char_start:char_end]

    no_answer_score = cls_span_score - best_span_score

    return pd.Series({
        "cls_span_score": cls_span_score,
        "best_span_score": best_span_score,
        "no_answer_score": no_answer_score,
        "best_start_token": best_start,
        "best_end_token": best_end,
        "best_span": best_span,
    })

In [ ]:
bert_model_eng = bert_model_eng.to(device)

validation_scores_eng = df_val.apply(
    get_validation_scores_eng,
    axis=1,
)

# df_val = pd.concat(
#     [df_val, validation_scores_eng],
#     axis=1,
# )

float_columns = [
    "cls_span_score",
    "best_span_score",
    "no_answer_score",
]

integer_columns = [
    "best_start_token",
    "best_end_token",
]

validation_scores_eng[float_columns] = validation_scores_eng[
    float_columns
].apply(
    pd.to_numeric,
    errors="raise",
)

validation_scores_eng[integer_columns] = validation_scores_eng[
    integer_columns
].apply(
    pd.to_numeric,
    errors="raise",
).astype("int64")

df_val = pd.concat(
    [df_val, validation_scores_eng],
    axis=1,
)

In [ ]:
import string

def squad_v2_normalize(text):
    text = text.lower()

    text = "".join(
        character
        for character in text
        if character not in string.punctuation
    )

    text = re.sub(r"\b(a|an|the)\b", " ", text)

    return " ".join(text.split())

def exact_match(prediction, gold):
    return float(squad_v2_normalize(prediction) == squad_v2_normalize(gold))

def token_f1(prediction, gold):
    prediction_tokens = squad_v2_normalize(prediction).split()
    gold_tokens = squad_v2_normalize(gold).split()

    if not prediction_tokens or not gold_tokens:
      return float(prediction_tokens == gold_tokens)

    overlap_number = sum((Counter(prediction_tokens) & Counter(gold_tokens)).values())

    if overlap_number == 0:
      return 0.0

    precision = overlap_number / len(prediction_tokens)
    recall = overlap_number / len(gold_tokens)

    return 2 * precision * recall / (precision + recall)

In [ ]:
threshold_results = []

for threshold in np.arange(-50, 50, 0.1):
    predictions = [
        ""
        if score > threshold
        else str(best_span)
        for score, best_span in zip(
            df_val["no_answer_score"],
            df_val["best_span"],
        )
    ]

    f1_scores = [
        token_f1(prediction, gold)
        for prediction, gold in zip(
            predictions,
            df_val["answer"],
        )
    ]

    exact_scores = [
        exact_match(prediction, gold)
        for prediction, gold in zip(
            predictions,
            df_val["answer"],
        )
    ]

    unanswerable_exact_scores = [
        exact_match(prediction, gold)
        for prediction, gold, answer_start in zip(
            predictions,
            df_val["answer"],
            df_val["answer_start"],
        )
        if answer_start == -1
    ]

    gold_answerability = (df_val["answer_start"] != -1).astype(int).values
    predicted_answerability = np.array([int(p.strip() != "") for p in predictions])
    ans_macro_f1 = f1_score(
        gold_answerability,
        predicted_answerability,
        labels=[0, 1],
        average="macro",
        zero_division=0,
    )

    threshold_results.append({
        "threshold": threshold,
        "ans_macro_f1": ans_macro_f1,
        "token_f1": np.mean(f1_scores),
        "exact_match": np.mean(exact_scores),
        "unanswerable_exact_match": np.mean(unanswerable_exact_scores),
    })

In [ ]:
best_result = max(
    threshold_results,
    key=lambda result: (result["ans_macro_f1"], result["token_f1"]),
)

best_threshold = best_result["threshold"]

print("Best threshold:", best_threshold)
print("Answerability macro-F1:", best_result["ans_macro_f1"])
print("Validation token F1:", best_result["token_f1"])
print("Validation exact match:", best_result["exact_match"])
print("Validation unanswerable exact match:", best_result["unanswerable_exact_match"])

Best threshold: -2.699999999999328
Answerability macro-F1: 0.7861111111111111
Validation token F1: 0.5621703527858175
Validation exact match: 0.45800865800865803
Validation unanswerable exact match: 0.042682926829268296

# Week 43-44

## Paired Challenge Set

## Week 36 Rule-based Classifier

In [ ]:
# deterministic rule-based classifier

def overlap_rule(question_, context, threshold = 0.20):
  overlap = set(question_) & set(context)
  return len(overlap)/len(set(context)) >= threshold

def number_overlap_rule(question, context):
  question_nums = [int(n) for n in re.findall(r'\d+', question)]
  context_nums = [int(n) for n in re.findall(r'\d+', context)]

  if len(question_nums) == 0:
    return True

  for qn in question_nums:
    for cn in context_nums:
      if abs(qn-cn) <= qn*0.1:
        return True
  return False

question_words = {
    AR: {"من": "who", "متى": "when", "أين": "where", "كم عدد": "how many"},
    KO: {"누구": "who", "언제": "when", "어디": "where", "얼마나": "how many"},
    TE: {"ఎవరు": "who", "ఎప్పుడు": "when", "ఎక్కడ": "where", "ఎన్ని": "how many"}
}

months = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"]
week_days = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]

# see presence of each of these question words in the question train dataset
def check_context(qword,context):
  context_nums = [int(n) for n in re.findall(r'\d+', context)]
  if qword == "when":
    if len(context_nums) > 0 and any(w in context for w in months+week_days):
      return True
    else:
      return False
  elif qword == "how many":
    if len(context_nums) > 0:
      return True
    else:
      return False
  return True

def qw_rule(lang, question, context):
  count_qws = 0
  for qword in question_words[lang].keys():
    if qword in question:
      count_qws += 1
      if not check_context(qword,context):
        return False
  if count_qws > 1:
    return False
  return True

def rule_classifier(question,question_translated,context):
  cnt = (
      (question.count("?") + question.count("؟") == 1)
      + overlap_rule(question_translated,context)
      + number_overlap_rule(question,context)
      + qw_rule(AR,question,context) + qw_rule(KO,question,context) + qw_rule(TE,question,context) # at least two will evaluate to 1
  )
  if cnt >= 6:
    return 1
  return 0

In [ ]:
# evaluation metrics answerability

def answerability_scores(annotated, predicted):
    TP = TN = FP = FN = 0
    for a, p in zip(annotated, predicted):
        if a == 1:
          if p == 1: TP += 1
          else: FN += 1
        else:
          if p == 1: FP += 1
          else: TN += 1

    precision_ans = TP / (TP + FP) if TP + FP else 0.0
    recall_ans = TP / (TP + FN) if TP + FN else 0.0
    f1_ans = (2*precision_ans*recall_ans) / (precision_ans + recall_ans) if precision_ans + recall_ans else 0.0

    precision_unans = TN / (TN + FN) if TN + FN else 0.0
    recall_unans = TN / (TN + FP) if TP + FN else 0.0
    f1_unans = (2*precision_unans*recall_unans) / (precision_unans + recall_unans) if precision_unans + recall_unans else 0.0

    accuracy = (TP+TN) / (TP+TN+FP+FN) if TP+TN+FP+FN else 0.0

    return precision_ans, recall_ans, f1_ans, precision_unans, recall_unans, f1_unans, accuracy

def evaluate_answerability(name, annotated, predicted):
  precision_ans, recall_ans, f1_ans, precision_unans, recall_unans, f1_unans, accuracy = answerability_scores(annotated, predicted)
  result = {
      "model": name,

      "accuracy": accuracy,

      "macro_avg_f1": (f1_ans + f1_unans)/2,

      "precision_answerable": precision_ans,
      "recall_answerable": recall_ans,
      "f1_answerable": f1_ans,

      "precision_unanswerable": precision_unans,
      "recall_unanswerable": recall_unans,
      "f1_unanswerable": f1_unans,
  }
  return result

In [ ]:
CHALLENGE_PATH = "./challenge-pairs/challenge.json"

with open(CHALLENGE_PATH, "r", encoding="utf-8") as file:
    challenge_data = json.load(file)

df_challenge = pd.DataFrame(challenge_data)

df_challenge_ = df_challenge.replace({True: 1, False: 0})

df_challenge['predict_answerable'] =  df_challenge_.apply(lambda row: rule_classifier(row['question'], translate(row['question'],row['lang'],EN), row['context']), axis=1)
df_challenge['predict_answerable'] = df_challenge['predict_answerable'].replace({1: True, 0: False})

display(df_challenge)

rbc_mlangs_metrics = evaluate_answerability("RBC - Challenge set", df_challenge_["answerable"], df_challenge_.apply(lambda row: rule_classifier(row['question'], translate(row['question'],row['lang'],EN), row['context']), axis=1))
pd.DataFrame([rbc_mlangs_metrics])

/tmp/ipykernel_14818/2679676595.py:8: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_challenge_ = df_challenge.replace({True: 1, False: 0})
/tmp/ipykernel_14818/2679676595.py:11: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_challenge['predict_answerable'] = df_challenge['predict_answerable'].replace({1: True, 0: False})

,id,pair_id,created_by,question,context,lang,answerable,answer_start,answer,source_url,predict_answerable
0,south-korea-geography-answerable,south-korea-geography,gdw810,대한민국은 어느 대륙에 위치해 있나요?,"South Korea, officially the Republic of Korea ...",ko,True,74,Asia,https://en.wikipedia.org/wiki/South_Korea#Geog...,True
1,south-korea-geography-unanswerable,south-korea-geography,gdw810,대한민국은 어느 반구에 위치해 있나요?,"South Korea, officially the Republic of Korea ...",ko,False,-1,,https://en.wikipedia.org/wiki/South_Korea#Geog...,True
2,seoul-history-answerable,seoul-history,gdw810,서울은 몇 년에 세워졌나요?,Seoul's history traces back to 18 BC when it w...,ko,True,31,18 BC,https://en.wikipedia.org/wiki/Seoul,True
3,seoul-history-unanswerable,seoul-history,gdw810,서울은 몇 년에 파괴되었나요?,Seoul's history traces back to 18 BC when it w...,ko,False,-1,,https://en.wikipedia.org/wiki/Seoul,True
4,tokyo-history-answerable,tokyo-history,gdw810,도쿄가 당시 에도라는 이름으로 도쿠가와 막부의 중심지가 된 해는 언제인가?,"Tokyo, originally known as Edo, rose to politi...",ko,True,64,1603,https://en.wikipedia.org/wiki/Tokyo,True
5,tokyo-history-unanswerable,tokyo-history,gdw810,에도가 도쿠가와 막부의 중심지가 된 달은 언제인가?,"Tokyo, originally known as Edo, rose to politi...",ko,False,-1,,https://en.wikipedia.org/wiki/Tokyo,True
6,bloomberg-answerable,bloomberg,gdw810,블룸버그 뉴스는 어디에 텔레비전 방송국을 개설했나요?,"During this growth period, Bloomberg News open...",ko,True,79,New York,https://en.wikipedia.org/wiki/Bloomberg_News,True
7,bloomberg-unanswerable,bloomberg,gdw810,블룸버그 뉴스는 사무실을 몇 개 소유하고 있었나요?,"During this growth period, Bloomberg News open...",ko,False,-1,,https://en.wikipedia.org/wiki/Bloomberg_News,True
8,computer-security-answerable,computer-security,gdw810,DDoS 공격은 어디에서 발생하나요?,While a network attack from a single IP addres...,ko,True,195,a large number of points,https://en.wikipedia.org/wiki/Computer_security,True
9,computer-security-unanswerable,computer-security,gdw810,DDoS 공격은 정확히 몇 개의 지점에서 발생하나요?,While a network attack from a single IP addres...,ko,False,-1,,https://en.wikipedia.org/wiki/Computer_security,True
10,example-egypt-answerable,example-egypt,tzg292,ما هو عدد سكان مصر؟,"Egypt, officially the Arab Republic of Egypt, ...",ar,True,163,107 million,https://en.wikipedia.org/wiki/Egypt,True
11,example-egypt-unanswerable,example-egypt,tzg292,ما هي الكثافة السكانية في مصر؟,"Egypt, officially the Arab Republic of Egypt, ...",ar,False,-1,,https://en.wikipedia.org/wiki/Egypt,True
12,example-worldCup-answerable,example-worldCup,tzg292,من الذي تم اختياره كأفضل لاعب في بطولة كأس الع...,The 2022 FIFA World Cup was the 22nd FIFA Worl...,ar,True,153,Lionel Messi,https://en.wikipedia.org/wiki/2022_FIFA_World_Cup,True
13,example-worldCup-unanswerable,example-worldCup,tzg292,من الذي تم اختياره كأكثر لاعب تهذيبًا في بطولة...,The 2022 FIFA World Cup was the 22nd FIFA Worl...,ar,False,-1,,https://en.wikipedia.org/wiki/2022_FIFA_World_Cup,True
14,example-teleguLang-answerable,example-teleguLang,tzg292,భారతదేశంలో ఎన్ని అధికారిక భాషలు ఉన్నాయి?,Telugu is one of the 22 languages with officia...,te,True,21,22,https://en.wikipedia.org/wiki/Telugu_language#...,True
15,example-teleguLang-unanswerable,example-teleguLang,tzg292,భారతదేశంలో ఎన్ని భాషలు ఉన్నాయి?,Telugu is one of the 22 languages with officia...,te,False,-1,,https://en.wikipedia.org/wiki/Telugu_language#...,True
16,example-birthday-answerable,example-birthday,tzg292,ఆగస్టు 29న తన పుట్టినరోజును జరుపుకునే వ్యక్తి ...,Telugu Language Day is celebrated every year o...,te,True,87,Gidugu Venkata Ramamurthy,https://en.wikipedia.org/wiki/Telugu_language#...,True
17,example-birthday-unanswerable,example-birthday,tzg292,ఫిబ్రవరి 29న తన పుట్టినరోజును జరుపుకునే వ్యక్త...,Telugu Language Day is celebrated every year o...,te,False,-1,,https://en.wikipedia.org/wiki/Telugu_language#...,True
18,example-seoul-answerable,example-seoul,tzg292,서울의 주요 종교는 무엇인가요?,The two major religions in Seoul are Christian...,ko,True,37,Christianity and Buddhism,https://en.wikipedia.org/wiki/Seoul#Religion,True
19,example-seoul-unanswerable,example-seoul,tzg292,서울에서 세 번째로 큰 종교는 무엇인가요?,The two major religions in Seoul are Christian...,ko,False,-1,,https://en.wikipedia.org/wiki/Seoul#Religion,True
20,example-quantum-answerable,example-quantum,cbp183,ما هو حد الفيزياء الكلاسيكية؟,Quantum mechanics can describe many systems th...,ar,True,223,describing aspects at very small submicroscopi...,https://de.wikipedia.org/wiki/Quantenphysik,True
21,example-quantum-unanswerable,example-quantum,cbp183,ما هو حد الفيزياء الكمومية؟,Quantum mechanics can describe many systems th...,ar,False,-1,,https://de.wikipedia.org/wiki/Quantenphysik,True
22,example-particle-answerable,example-particle,cbp183,ما هو الجسيم الحر في بُعد مكاني واحد؟,The simplest example of a quantum system with ...,ar,True,0,The simplest example of a quantum system with ...,https://de.wikipedia.org/wiki/Quantenphysik,True
23,example-particle-unanswerable,example-particle,cbp183,ما هو الجسيم الحر في ثلاثة أبعاد مكانية؟,The simplest example of a quantum system with ...,ar,False,-1,,https://de.wikipedia.org/wiki/Quantenphysik,True
24,example-einstein-answerable,example-einstein,cbp183,ما هي أشهر معادلة في العالم؟,Albert Einstein (14 March 1879 – 18 April 1955...,ar,True,238,E = mc2,https://en.wikipedia.org/wiki/Albert_Einstein,True
25,example-einstein-unanswerable,example-einstein,cbp183,في أي عام نشر أينشتاين معادلة تكافؤ الكتلة وال...,Albert Einstein (14 March 1879 – 18 April 1955...,ar,False,-1,,https://en.wikipedia.org/wiki/Albert_Einstein,True
26,example-father-answerable,example-father,cbp183,ماذا كان يعمل والد أينشتاين؟,Einstein was born in Ulm as a subject to the K...,ar,True,169,salesman and engineer,https://en.wikipedia.org/wiki/Albert_Einstein,True
27,example-father-unanswerable,example-father,cbp183,أين درس والد أينشتاين؟,Einstein was born in Ulm as a subject to the K...,ar,False,-1,,https://en.wikipedia.org/wiki/Albert_Einstein,True
28,example-relativity-answerable,example-relativity,cbp183,ఐన్‌స్టీన్ గురుత్వాకర్షణ సిద్ధాంతాన్ని అభివృద్...,General relativity (GR) is a theory of gravita...,te,True,90,1907,https://en.wikipedia.org/wiki/Albert_Einstein,True
29,example-relativity-unanswerable,example-relativity,cbp183,1905లో ఐన్‌స్టీన్ ఏమి చేశాడు?,General relativity (GR) is a theory of gravita...,te,False,-1,,https://en.wikipedia.org/wiki/Albert_Einstein,True

,model,accuracy,macro_avg_f1,precision_answerable,recall_answerable,f1_answerable,precision_unanswerable,recall_unanswerable,f1_unanswerable
0,RBC - Challenge set,0.5,0.333333,0.5,1.0,0.666667,0.0,0.0,0.0

## Week 37 Sequence Labeler

In [45]:
sequence_labeler = joblib.load(
    "models/week37_sequence_labeller.joblib"
)

vectorizer = sequence_labeler["vectorizer"]
token_classifier = sequence_labeler["classifier"]

In [46]:
CHALLENGE_PATH = "./challenge-pairs/challenge.json"

with open(CHALLENGE_PATH, "r", encoding="utf-8") as file:
    challenge_data = json.load(file)

df_challenge = pd.DataFrame(challenge_data)

df_challenge["sequence_labels"] = df_challenge.apply(
    bio_labeller_row,
    axis=1,
)
df_challenge["context_tokens"] = df_challenge.apply(
    tokenizer_row,
    axis=1,
)

challenge_features, challenge_labels, challenge_lengths = featurize_split(df_challenge)

X_challenge = vectorizer.transform(challenge_features)

challenge_flat_predictions = token_classifier.predict(X_challenge)

challenge_predictions = split_by_lengths(challenge_flat_predictions, challenge_lengths)


df_challenge["predicted_labels"] = challenge_predictions

display(
    df_challenge[
        [
            "id",
            "question",
            "answer",
            "sequence_labels",
            "predicted_labels",
        ]
    ]
)

challenge_gold = split_by_lengths(
    challenge_labels, challenge_lengths
)

print(evaluate_sequences(
    "Sequence labeler on challenge data",
    challenge_gold,
    challenge_predictions,
))

,id,question,answer,sequence_labels,predicted_labels
0,south-korea-geography-answerable,대한민국은 어느 대륙에 위치해 있나요?,Asia,"[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ...","[B, I, O, O, O, O, O, I, O, O, O, O, O, O, O, ..."
1,south-korea-geography-unanswerable,대한민국은 어느 반구에 위치해 있나요?,,"[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ...","[B, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."
2,seoul-history-answerable,서울은 몇 년에 세워졌나요?,18 BC,"[O, O, O, O, O, O, B, I, O, O, O, O, O, O, O, ...","[B, O, O, O, O, O, B, I, O, O, O, O, O, O, O, ..."
3,seoul-history-unanswerable,서울은 몇 년에 파괴되었나요?,,"[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ...","[B, O, O, O, O, O, B, I, O, O, O, O, O, O, O, ..."
4,tokyo-history-answerable,도쿄가 당시 에도라는 이름으로 도쿠가와 막부의 중심지가 된 해는 언제인가?,1603,"[O, O, O, O, O, O, O, O, O, O, O, O, B, O, O, ...","[B, O, O, O, O, O, O, O, O, O, O, O, B, O, O, ..."
5,tokyo-history-unanswerable,에도가 도쿠가와 막부의 중심지가 된 달은 언제인가?,,"[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ...","[B, O, O, O, O, O, O, O, O, O, O, O, B, O, O, ..."
6,bloomberg-answerable,블룸버그 뉴스는 어디에 텔레비전 방송국을 개설했나요?,New York,"[O, O, O, O, O, O, O, O, O, O, O, O, O, B, I, ...","[O, O, O, O, O, I, O, O, O, O, O, O, O, O, O, ..."
7,bloomberg-unanswerable,블룸버그 뉴스는 사무실을 몇 개 소유하고 있었나요?,,"[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ...","[O, O, O, O, O, I, O, O, O, O, O, O, O, B, O, ..."
8,computer-security-answerable,DDoS 공격은 어디에서 발생하나요?,a large number of points,"[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."
9,computer-security-unanswerable,DDoS 공격은 정확히 몇 개의 지점에서 발생하나요?,,"[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ...","[B, O, O, O, O, O, B, O, O, O, O, O, O, O, O, ..."
10,example-egypt-answerable,ما هو عدد سكان مصر؟,107 million,"[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ...","[B, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."
11,example-egypt-unanswerable,ما هي الكثافة السكانية في مصر؟,,"[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ...","[B, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."
12,example-worldCup-answerable,من الذي تم اختياره كأفضل لاعب في بطولة كأس الع...,Lionel Messi,"[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."
13,example-worldCup-unanswerable,من الذي تم اختياره كأكثر لاعب تهذيبًا في بطولة...,,"[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."
14,example-teleguLang-answerable,భారతదేశంలో ఎన్ని అధికారిక భాషలు ఉన్నాయి?,22,"[O, O, O, O, O, B, O, O, O, O, O, O, O, O, O, ...","[B, O, O, O, O, B, O, O, O, O, O, O, O, O, O, ..."
15,example-teleguLang-unanswerable,భారతదేశంలో ఎన్ని భాషలు ఉన్నాయి?,,"[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ...","[B, O, O, O, O, B, O, O, O, O, O, O, O, O, O, ..."
16,example-birthday-answerable,ఆగస్టు 29న తన పుట్టినరోజును జరుపుకునే వ్యక్తి ...,Gidugu Venkata Ramamurthy,"[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ...","[B, O, O, O, O, I, O, O, B, I, O, O, O, O, O, ..."
17,example-birthday-unanswerable,ఫిబ్రవరి 29న తన పుట్టినరోజును జరుపుకునే వ్యక్త...,,"[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ...","[B, O, O, O, O, I, O, O, O, I, O, O, O, O, O, ..."
18,example-seoul-answerable,서울의 주요 종교는 무엇인가요?,Christianity and Buddhism,"[O, O, O, O, O, O, O, B, I, I, O, O, O, O, O, ...","[O, O, O, O, O, O, O, B, O, O, O, O, O, O, O, ..."
19,example-seoul-unanswerable,서울에서 세 번째로 큰 종교는 무엇인가요?,,"[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ...","[O, O, O, O, O, O, O, B, O, O, O, O, O, O, O, ..."
20,example-quantum-answerable,ما هو حد الفيزياء الكلاسيكية؟,describing aspects at very small submicroscopi...,"[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ...","[B, O, O, O, O, O, I, O, O, O, O, O, O, O, O, ..."
21,example-quantum-unanswerable,ما هو حد الفيزياء الكمومية؟,,"[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ...","[B, O, O, O, O, O, I, I, O, O, O, O, O, O, O, ..."
22,example-particle-answerable,ما هو الجسيم الحر في بُعد مكاني واحد؟,The simplest example of a quantum system with ...,"[B, I, I, I, I, I, I, I, I, I, I, I, I, O, O, ...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."
23,example-particle-unanswerable,ما هو الجسيم الحر في ثلاثة أبعاد مكانية؟,,"[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."
24,example-einstein-answerable,ما هي أشهر معادلة في العالم؟,E = mc2,"[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ...","[B, I, O, B, I, I, O, B, I, I, O, O, O, O, O, ..."
25,example-einstein-unanswerable,في أي عام نشر أينشتاين معادلة تكافؤ الكتلة وال...,,"[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ...","[B, I, O, B, I, I, O, B, I, I, O, O, O, B, O, ..."
26,example-father-answerable,ماذا كان يعمل والد أينشتاين؟,salesman and engineer,"[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ...","[B, O, O, O, B, O, O, O, O, O, O, O, I, O, O, ..."
27,example-father-unanswerable,أين درس والد أينشتاين؟,,"[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ...","[B, O, O, O, B, O, O, O, O, O, O, O, I, O, O, ..."
28,example-relativity-answerable,ఐన్‌స్టీన్ గురుత్వాకర్షణ సిద్ధాంతాన్ని అభివృద్...,1907,"[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ...","[B, O, O, O, O, O, O, O, O, O, O, O, O, O, B, ..."
29,example-relativity-unanswerable,1905లో ఐన్‌స్టీన్ ఏమి చేశాడు?,,"[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ...","[B, O, O, O, O, O, O, O, O, O, O, O, O, O, B, ..."

{'model': 'Sequence labeler on challenge data', 'token_accuracy': 0.9196538936959209, 'answer_token_f1': 0.1103448275862069, 'exact_span_match': np.float64(0.06666666666666667), 'unanswerable_exact_match': np.float64(0.13333333333333333)}

## Week 39 Recurrent Neural Classifier

### Embedding

In [ ]:
CHALLENGE_PATH = "./challenge-pairs/challenge.json"

with open(CHALLENGE_PATH, "r", encoding="utf-8") as file:
    challenge_data = json.load(file)

df_challenge = pd.DataFrame(challenge_data)

In [ ]:
!pip install bpemb sentencepiece
from bpemb import BPEmb

Requirement already satisfied: bpemb in /usr/local/lib/python3.13/dist-packages (0.3.6)
Requirement already satisfied: sentencepiece in /usr/local/lib/python3.13/dist-packages (0.2.2)
Requirement already satisfied: gensim in /usr/local/lib/python3.13/dist-packages (from bpemb) (4.4.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.13/dist-packages (from bpemb) (2.1.3)
Requirement already satisfied: requests in /usr/local/lib/python3.13/dist-packages (from bpemb) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.13/dist-packages (from bpemb) (4.67.3)
Requirement already satisfied: scipy>=1.7.0 in /usr/local/lib/python3.13/dist-packages (from gensim->bpemb) (1.16.3)
Requirement already satisfied: smart_open>=1.8.1 in /usr/local/lib/python3.13/dist-packages (from gensim->bpemb) (8.0.4)
Requirement already satisfied: wrapt in /usr/local/lib/python3.13/dist-packages (from smart_open>=1.8.1->gensim->bpemb) (2.5.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests->bpemb) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests->bpemb) (3.20)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests->bpemb) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests->bpemb) (2026.10.23)

In [ ]:
VECTOR_SIZE = 100000
INPUT_DIMENSIONS = 300
multilingual_bpemb = BPEmb(lang="multi", vs=VECTOR_SIZE, dim=INPUT_DIMENSIONS)

In [ ]:
def embed(df_emb, col):
  embs = []
  for c in df_emb[col]:
    emb = torch.tensor(multilingual_bpemb.embed(c))
    embs.append(emb)
  return embs

challenge_emb_contexts = embed(df_challenge, 'context')
challenge_emb_questions = embed(df_challenge, 'question')
challenge_emb_labels = torch.tensor(df_challenge['answerable'].astype(int).values)

chal_data = list(zip(challenge_emb_contexts, challenge_emb_questions, challenge_emb_labels))

In [ ]:
# Fill sequences with 0s to get same length
# Save original length
def collate(batch):
  c, q, y = zip(*batch)

  c_len = [len(x) for x in c]
  q_len = [len(x) for x in q]

  return (
      pad_sequence(c, batch_first=True), c_len,
      pad_sequence(q, batch_first=True), q_len,
      torch.stack(y)
  )

# Shapes when iterating DataLoader
# B = batch size
# maxLc/maxLq = len of longest ctx/q
# dim = input dimensions (300)
# c: (B, maxLc, dim)
# q: (B, maxLq, dim)
# c_len/q_len: (B,) -> original lengths
# y: (B,) -> labels 0 or 1
challenge_loader   = DataLoader(chal_data,   batch_size=64, shuffle=False, collate_fn=collate)

### LSTM

In [ ]:
class LSTM_Classifier(nn.Module):
  def __init__(
    self,
    input_size,
    hidden_size,
    output_size,
    num_layers,
    dropout=0.2
  ):
    super(LSTM_Classifier, self).__init__()
    self.lstm_c = nn.LSTM(input_size, hidden_size,
                          num_layers, batch_first=True)
    self.lstm_q = nn.LSTM(input_size, hidden_size,
                          num_layers, batch_first=True)

    self.drop = nn.Dropout(dropout)

    self.fc = nn.Linear(hidden_size, output_size)

  def forward(self, c, c_len, q, q_len):
    c = self.drop(c)
    q = self.drop(q)

    c = pack_padded_sequence(c, c_len, batch_first=True, enforce_sorted=False)
    q = pack_padded_sequence(q, q_len, batch_first=True, enforce_sorted=False)

    _, (hn, cn) = self.lstm_c(c)
    _, (hk, ck) = self.lstm_q(q, (hn, cn))

    return self.fc(self.drop(hk[-1])).squeeze(-1)

In [ ]:
INPUT_SIZE = INPUT_DIMENSIONS
HIDDEN_SIZE = 128
NUM_LAYERS = 1
OUTPUT_SIZE = 1
LEARNING_RATE = 0.001

lstm_model = LSTM_Classifier(
  input_size=INPUT_SIZE,
  hidden_size=HIDDEN_SIZE,
  output_size=OUTPUT_SIZE,
  num_layers=NUM_LAYERS
)

In [ ]:
lstm_model.load_state_dict(torch.load(RNN_MODEL_PATH, map_location="cpu"))

### Predict

In [ ]:
@torch.no_grad()
def predict(model, loader):
    device = next(model.parameters()).device
    model.eval()
    preds, labels = [], []
    for c, c_len, q, q_len, y in loader:
        logits = model(c.to(device), c_len, q.to(device), q_len)
        preds += (logits > 0).long().cpu().tolist()
        labels += y.tolist()
    return preds, labels

In [ ]:
preds, labels = predict(lstm_model, challenge_loader)
lang_list = df_challenge['lang'].to_list()
df_preds_lstm = pd.DataFrame({
    'pred': preds,
    'label': labels,
    'lang': lang_list
})

df_preds_lstm_ar = df_preds_lstm[df_preds_lstm['lang'] == 'ar']
df_preds_lstm_ko = df_preds_lstm[df_preds_lstm['lang'] == 'ko']
df_preds_lstm_te = df_preds_lstm[df_preds_lstm['lang'] == 'te']

### Scores

In [ ]:
def answerability_scores(annotated, predicted):
    TP = TN = FP = FN = 0
    for a, p in zip(annotated, predicted):
        if a == 1:
          if p == 1: TP += 1
          else: FN += 1
        else:
          if p == 1: FP += 1
          else: TN += 1

    precision_ans = TP / (TP + FP) if TP + FP else 0.0
    recall_ans = TP / (TP + FN) if TP + FN else 0.0
    f1_ans = (2*precision_ans*recall_ans) / (precision_ans + recall_ans) if precision_ans + recall_ans else 0.0

    precision_unans = TN / (TN + FN) if TN + FN else 0.0
    recall_unans = TN / (TN + FP) if TN + FP else 0.0
    f1_unans = (2*precision_unans*recall_unans) / (precision_unans + recall_unans) if precision_unans + recall_unans else 0.0

    accuracy = (TP+TN) / (TP+TN+FP+FN) if TP+TN+FP+FN else 0.0

    return precision_ans, recall_ans, f1_ans, precision_unans, recall_unans, f1_unans, accuracy

def evaluate_answerability(name, annotated, predicted):
  precision_ans, recall_ans, f1_ans, precision_unans, recall_unans, f1_unans, accuracy = answerability_scores(annotated, predicted)
  result = {
      "model": name,

      "accuracy": accuracy,

      "macro_avg_f1": (f1_ans + f1_unans)/2,

      "precision_answerable": precision_ans,
      "recall_answerable": recall_ans,
      "f1_answerable": f1_ans,

      "precision_unanswerable": precision_unans,
      "recall_unanswerable": recall_unans,
      "f1_unanswerable": f1_unans,
  }
  return result

In [ ]:
lstm_result_ar = evaluate_answerability("LSTM (AR)", df_preds_lstm_ar['label'].to_list(), df_preds_lstm_ar['pred'].to_list())
lstm_result_ko = evaluate_answerability("LSTM (KO)", df_preds_lstm_ko['label'].to_list(), df_preds_lstm_ko['pred'].to_list())
lstm_result_te = evaluate_answerability("LSTM (TE)", df_preds_lstm_te['label'].to_list(), df_preds_lstm_te['pred'].to_list())
lstm_result_overall = evaluate_answerability("LSTM (Overall)", labels, preds)

In [ ]:
pd.DataFrame([lstm_result_ar, lstm_result_ko, lstm_result_te, lstm_result_overall])

,model,accuracy,macro_avg_f1,precision_answerable,recall_answerable,f1_answerable,precision_unanswerable,recall_unanswerable,f1_unanswerable
0,LSTM (AR),0.5,0.333333,0.5,1.0,0.666667,0.0,0.0,0.0
1,LSTM (KO),0.5,0.333333,0.5,1.0,0.666667,0.0,0.0,0.0
2,LSTM (TE),0.5,0.333333,0.5,1.0,0.666667,0.0,0.0,0.0
3,LSTM (Overall),0.5,0.333333,0.5,1.0,0.666667,0.0,0.0,0.0

## Weeks 40-41 Integrated QA Model

In [47]:
BERT_MODEL_PATH = "./models/week40_berts"

bert_tokenizer = AutoTokenizer.from_pretrained(
    BERT_MODEL_PATH
)

bert_model = AutoModelForQuestionAnswering.from_pretrained(
    BERT_MODEL_PATH
)

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

In [48]:
CHALLENGE_PATH = "./challenge-pairs/challenge.json"

with open(CHALLENGE_PATH, "r", encoding="utf-8") as file:
    challenge_data = json.load(file)

df_challenge = pd.DataFrame(challenge_data)

bert_model = bert_model.to(device)

challenge_scores = df_challenge.apply(
    get_validation_scores,
    axis=1,
)

float_columns = [
    "cls_span_score",
    "best_span_score",
    "no_answer_score",
]

integer_columns = [
    "best_start_token",
    "best_end_token",
]

challenge_scores[float_columns] = challenge_scores[
    float_columns
].apply(
    pd.to_numeric,
    errors="raise",
)

challenge_scores[integer_columns] = challenge_scores[
    integer_columns
].apply(
    pd.to_numeric,
    errors="raise",
).astype("int64")

df_challenge = pd.concat(
    [df_challenge, challenge_scores],
    axis=1,
)
df_challenge

,id,pair_id,created_by,question,context,lang,answerable,answer_start,answer,source_url,cls_span_score,best_span_score,no_answer_score,best_start_token,best_end_token,best_span
0,south-korea-geography-answerable,south-korea-geography,gdw810,대한민국은 어느 대륙에 위치해 있나요?,"South Korea, officially the Republic of Korea ...",ko,True,74,Asia,https://en.wikipedia.org/wiki/South_Korea#Geog...,1.110191,8.838606,-7.728416,32,33,East Asia
1,south-korea-geography-unanswerable,south-korea-geography,gdw810,대한민국은 어느 반구에 위치해 있나요?,"South Korea, officially the Republic of Korea ...",ko,False,-1,,https://en.wikipedia.org/wiki/South_Korea#Geog...,0.369377,10.068304,-9.698927,32,33,East Asia
2,seoul-history-answerable,seoul-history,gdw810,서울은 몇 년에 세워졌나요?,Seoul's history traces back to 18 BC when it w...,ko,True,31,18 BC,https://en.wikipedia.org/wiki/Seoul,4.282255,8.968500,-4.686244,20,21,18 BC
3,seoul-history-unanswerable,seoul-history,gdw810,서울은 몇 년에 파괴되었나요?,Seoul's history traces back to 18 BC when it w...,ko,False,-1,,https://en.wikipedia.org/wiki/Seoul,4.878444,5.214624,-0.336180,21,22,18 BC
4,tokyo-history-answerable,tokyo-history,gdw810,도쿄가 당시 에도라는 이름으로 도쿠가와 막부의 중심지가 된 해는 언제인가?,"Tokyo, originally known as Edo, rose to politi...",ko,True,64,1603,https://en.wikipedia.org/wiki/Tokyo,-1.166842,11.893509,-13.060351,38,38,1603
5,tokyo-history-unanswerable,tokyo-history,gdw810,에도가 도쿠가와 막부의 중심지가 된 달은 언제인가?,"Tokyo, originally known as Edo, rose to politi...",ko,False,-1,,https://en.wikipedia.org/wiki/Tokyo,-0.857863,11.363574,-12.221437,33,33,1603
6,bloomberg-answerable,bloomberg,gdw810,블룸버그 뉴스는 어디에 텔레비전 방송국을 개설했나요?,"During this growth period, Bloomberg News open...",ko,True,79,New York,https://en.wikipedia.org/wiki/Bloomberg_News,4.395690,6.269533,-1.873843,34,35,New York
7,bloomberg-unanswerable,bloomberg,gdw810,블룸버그 뉴스는 사무실을 몇 개 소유하고 있었나요?,"During this growth period, Bloomberg News open...",ko,False,-1,,https://en.wikipedia.org/wiki/Bloomberg_News,5.143161,-0.749219,5.892380,44,66,fifteen-minute weekday business news programs ...
8,computer-security-answerable,computer-security,gdw810,DDoS 공격은 어디에서 발생하나요?,While a network attack from a single IP addres...,ko,True,195,a large number of points,https://en.wikipedia.org/wiki/Computer_security,1.110947,2.184756,-1.073809,19,25,network attack from a single IP address
9,computer-security-unanswerable,computer-security,gdw810,DDoS 공격은 정확히 몇 개의 지점에서 발생하나요?,While a network attack from a single IP addres...,ko,False,-1,,https://en.wikipedia.org/wiki/Computer_security,2.413614,0.937143,1.476471,28,70,single IP address can be blocked by adding a n...
10,example-egypt-answerable,example-egypt,tzg292,ما هو عدد سكان مصر؟,"Egypt, officially the Arab Republic of Egypt, ...",ar,True,163,107 million,https://en.wikipedia.org/wiki/Egypt,-1.399125,11.536683,-12.935808,38,39,107 million
11,example-egypt-unanswerable,example-egypt,tzg292,ما هي الكثافة السكانية في مصر؟,"Egypt, officially the Arab Republic of Egypt, ...",ar,False,-1,,https://en.wikipedia.org/wiki/Egypt,-1.712700,6.876622,-8.589322,38,40,over 107 million
12,example-worldCup-answerable,example-worldCup,tzg292,من الذي تم اختياره كأفضل لاعب في بطولة كأس الع...,The 2022 FIFA World Cup was the 22nd FIFA Worl...,ar,True,153,Lionel Messi,https://en.wikipedia.org/wiki/2022_FIFA_World_Cup,-2.042225,14.575495,-16.617720,47,48,Lionel Messi
13,example-worldCup-unanswerable,example-worldCup,tzg292,من الذي تم اختياره كأكثر لاعب تهذيبًا في بطولة...,The 2022 FIFA World Cup was the 22nd FIFA Worl...,ar,False,-1,,https://en.wikipedia.org/wiki/2022_FIFA_World_Cup,-2.008400,14.459633,-16.468033,52,53,Lionel Messi
14,example-teleguLang-answerable,example-teleguLang,tzg292,భారతదేశంలో ఎన్ని అధికారిక భాషలు ఉన్నాయి?,Telugu is one of the 22 languages with officia...,te,True,21,22,https://en.wikipedia.org/wiki/Telugu_language#...,0.214378,12.077137,-11.862759,22,22,22
15,example-teleguLang-unanswerable,example-teleguLang,tzg292,భారతదేశంలో ఎన్ని భాషలు ఉన్నాయి?,Telugu is one of the 22 languages with officia...,te,False,-1,,https://en.wikipedia.org/wiki/Telugu_language#...,0.099766,12.222844,-12.123078,18,18,22
16,example-birthday-answerable,example-birthday,tzg292,ఆగస్టు 29న తన పుట్టినరోజును జరుపుకునే వ్యక్తి ...,Telugu Language Day is celebrated every year o...,te,True,87,Gidugu Venkata Ramamurthy,https://en.wikipedia.org/wiki/Telugu_language#...,0.102210,11.418958,-11.316748,44,52,Gidugu Venkata Ramamurthy
17,example-birthday-unanswerable,example-birthday,tzg292,ఫిబ్రవరి 29న తన పుట్టినరోజును జరుపుకునే వ్యక్త...,Telugu Language Day is celebrated every year o...,te,False,-1,,https://en.wikipedia.org/wiki/Telugu_language#...,0.569836,11.316668,-10.746832,45,53,Gidugu Venkata Ramamurthy
18,example-seoul-answerable,example-seoul,tzg292,서울의 주요 종교는 무엇인가요?,The two major religions in Seoul are Christian...,ko,True,37,Christianity and Buddhism,https://en.wikipedia.org/wiki/Seoul#Religion,-2.234689,11.442082,-13.676771,21,23,Christianity and Buddhism
19,example-seoul-unanswerable,example-seoul,tzg292,서울에서 세 번째로 큰 종교는 무엇인가요?,The two major religions in Seoul are Christian...,ko,False,-1,,https://en.wikipedia.org/wiki/Seoul#Religion,-1.714736,12.056896,-13.771632,24,26,Christianity and Buddhism
20,example-quantum-answerable,example-quantum,cbp183,ما هو حد الفيزياء الكلاسيكية؟,Quantum mechanics can describe many systems th...,ar,True,223,describing aspects at very small submicroscopi...,https://de.wikipedia.org/wiki/Quantenphysik,-0.888863,1.859915,-2.748779,34,48,ordinary (macroscopic and (optical) microscopi...
21,example-quantum-unanswerable,example-quantum,cbp183,ما هو حد الفيزياء الكمومية؟,Quantum mechanics can describe many systems th...,ar,False,-1,,https://de.wikipedia.org/wiki/Quantenphysik,-0.625255,1.619898,-2.245152,34,48,ordinary (macroscopic and (optical) microscopi...
22,example-particle-answerable,example-particle,cbp183,ما هو الجسيم الحر في بُعد مكاني واحد؟,The simplest example of a quantum system with ...,ar,True,0,The simplest example of a quantum system with ...,https://de.wikipedia.org/wiki/Quantenphysik,-0.274855,5.956538,-6.231393,34,40,free particle in a single spatial dimension
23,example-particle-unanswerable,example-particle,cbp183,ما هو الجسيم الحر في ثلاثة أبعاد مكانية؟,The simplest example of a quantum system with ...,ar,False,-1,,https://de.wikipedia.org/wiki/Quantenphysik,-0.222248,5.665097,-5.887345,34,40,free particle in a single spatial dimension
24,example-einstein-answerable,example-einstein,cbp183,ما هي أشهر معادلة في العالم؟,Albert Einstein (14 March 1879 – 18 April 1955...,ar,True,238,E = mc2,https://en.wikipedia.org/wiki/Albert_Einstein,-0.279531,11.720641,-12.000172,58,62,E = mc2
25,example-einstein-unanswerable,example-einstein,cbp183,في أي عام نشر أينشتاين معادلة تكافؤ الكتلة وال...,Albert Einstein (14 March 1879 – 18 April 1955...,ar,False,-1,,https://en.wikipedia.org/wiki/Albert_Einstein,3.412926,4.313463,-0.900537,72,76,E = mc2
26,example-father-answerable,example-father,cbp183,ماذا كان يعمل والد أينشتاين؟,Einstein was born in Ulm as a subject to the K...,ar,True,169,salesman and engineer,https://en.wikipedia.org/wiki/Albert_Einstein,-2.283736,7.271112,-9.554848,44,45,Hermann Einstein
27,example-father-unanswerable,example-father,cbp183,أين درس والد أينشتاين؟,Einstein was born in Ulm as a subject to the K...,ar,False,-1,,https://en.wikipedia.org/wiki/Albert_Einstein,-0.699896,7.178455,-7.878351,15,15,Ulm
28,example-relativity-answerable,example-relativity,cbp183,ఐన్‌స్టీన్ గురుత్వాకర్షణ సిద్ధాంతాన్ని అభివృద్...,General relativity (GR) is a theory of gravita...,te,True,90,1907,https://en.wikipedia.org/wiki/Albert_Einstein,2.676091,12.876906,-10.200815,52,54,1907 and 1915
29,example-relativity-unanswerable,example-relativity,cbp183,1905లో ఐన్‌స్టీన్ ఏమి చేశాడు?,General relativity (GR) is a theory of gravita...,te,False,-1,,https://en.wikipedia.org/wiki/Albert_Einstein,2.901674,1.245882,1.655792,31,31,Einstein

In [49]:
predictions = [
    ""
    if score > best_threshold
    else str(best_span)
    for score, best_span in zip(
        df_challenge["no_answer_score"],
        df_challenge["best_span"],
    )
]

f1_scores = [
    token_f1(prediction, gold)
    for prediction, gold in zip(
        predictions,
        df_challenge["answer"],
    )
]

exact_scores = [
    exact_match(prediction, gold)
    for prediction, gold in zip(
        predictions,
        df_challenge["answer"],
    )
]

unanswerable_exact_scores = [
    exact_match(prediction, gold)
    for prediction, gold, answer_start in zip(
        predictions,
        df_challenge["answer"],
        df_challenge["answer_start"],
    )
    if answer_start == -1
]

gold_answerability = (df_challenge["answer_start"] != -1).astype(int).values
predicted_answerability = np.array([int(p.strip() != "") for p in predictions])
ans_macro_f1 = f1_score(
    gold_answerability,
    predicted_answerability,
    labels=[0, 1],
    average="macro",
    zero_division=0,
)

{
    "threshold": best_threshold,
    "ans_macro_f1": ans_macro_f1,
    "token_f1": np.mean(f1_scores),
    "exact_match": np.mean(exact_scores),
    "unanswerable_exact_match": np.mean(unanswerable_exact_scores),
}

{'threshold': np.float64(3.5000000000007603),
 'ans_macro_f1': 0.4034090909090909,
 'token_f1': np.float64(0.3763888888888889),
 'exact_match': np.float64(0.3333333333333333),
 'unanswerable_exact_match': np.float64(0.06666666666666667)}

In [50]:
df_challenge = pd.concat(
    [df_challenge, pd.DataFrame(predictions)],
    axis=1,
)
df_challenge

,id,pair_id,created_by,question,context,lang,answerable,answer_start,answer,source_url,cls_span_score,best_span_score,no_answer_score,best_start_token,best_end_token,best_span,0
0,south-korea-geography-answerable,south-korea-geography,gdw810,대한민국은 어느 대륙에 위치해 있나요?,"South Korea, officially the Republic of Korea ...",ko,True,74,Asia,https://en.wikipedia.org/wiki/South_Korea#Geog...,1.110191,8.838606,-7.728416,32,33,East Asia,East Asia
1,south-korea-geography-unanswerable,south-korea-geography,gdw810,대한민국은 어느 반구에 위치해 있나요?,"South Korea, officially the Republic of Korea ...",ko,False,-1,,https://en.wikipedia.org/wiki/South_Korea#Geog...,0.369377,10.068304,-9.698927,32,33,East Asia,East Asia
2,seoul-history-answerable,seoul-history,gdw810,서울은 몇 년에 세워졌나요?,Seoul's history traces back to 18 BC when it w...,ko,True,31,18 BC,https://en.wikipedia.org/wiki/Seoul,4.282255,8.968500,-4.686244,20,21,18 BC,18 BC
3,seoul-history-unanswerable,seoul-history,gdw810,서울은 몇 년에 파괴되었나요?,Seoul's history traces back to 18 BC when it w...,ko,False,-1,,https://en.wikipedia.org/wiki/Seoul,4.878444,5.214624,-0.336180,21,22,18 BC,18 BC
4,tokyo-history-answerable,tokyo-history,gdw810,도쿄가 당시 에도라는 이름으로 도쿠가와 막부의 중심지가 된 해는 언제인가?,"Tokyo, originally known as Edo, rose to politi...",ko,True,64,1603,https://en.wikipedia.org/wiki/Tokyo,-1.166842,11.893509,-13.060351,38,38,1603,1603
5,tokyo-history-unanswerable,tokyo-history,gdw810,에도가 도쿠가와 막부의 중심지가 된 달은 언제인가?,"Tokyo, originally known as Edo, rose to politi...",ko,False,-1,,https://en.wikipedia.org/wiki/Tokyo,-0.857863,11.363574,-12.221437,33,33,1603,1603
6,bloomberg-answerable,bloomberg,gdw810,블룸버그 뉴스는 어디에 텔레비전 방송국을 개설했나요?,"During this growth period, Bloomberg News open...",ko,True,79,New York,https://en.wikipedia.org/wiki/Bloomberg_News,4.395690,6.269533,-1.873843,34,35,New York,New York
7,bloomberg-unanswerable,bloomberg,gdw810,블룸버그 뉴스는 사무실을 몇 개 소유하고 있었나요?,"During this growth period, Bloomberg News open...",ko,False,-1,,https://en.wikipedia.org/wiki/Bloomberg_News,5.143161,-0.749219,5.892380,44,66,fifteen-minute weekday business news programs ...,
8,computer-security-answerable,computer-security,gdw810,DDoS 공격은 어디에서 발생하나요?,While a network attack from a single IP addres...,ko,True,195,a large number of points,https://en.wikipedia.org/wiki/Computer_security,1.110947,2.184756,-1.073809,19,25,network attack from a single IP address,network attack from a single IP address
9,computer-security-unanswerable,computer-security,gdw810,DDoS 공격은 정확히 몇 개의 지점에서 발생하나요?,While a network attack from a single IP addres...,ko,False,-1,,https://en.wikipedia.org/wiki/Computer_security,2.413614,0.937143,1.476471,28,70,single IP address can be blocked by adding a n...,single IP address can be blocked by adding a n...
10,example-egypt-answerable,example-egypt,tzg292,ما هو عدد سكان مصر؟,"Egypt, officially the Arab Republic of Egypt, ...",ar,True,163,107 million,https://en.wikipedia.org/wiki/Egypt,-1.399125,11.536683,-12.935808,38,39,107 million,107 million
11,example-egypt-unanswerable,example-egypt,tzg292,ما هي الكثافة السكانية في مصر؟,"Egypt, officially the Arab Republic of Egypt, ...",ar,False,-1,,https://en.wikipedia.org/wiki/Egypt,-1.712700,6.876622,-8.589322,38,40,over 107 million,over 107 million
12,example-worldCup-answerable,example-worldCup,tzg292,من الذي تم اختياره كأفضل لاعب في بطولة كأس الع...,The 2022 FIFA World Cup was the 22nd FIFA Worl...,ar,True,153,Lionel Messi,https://en.wikipedia.org/wiki/2022_FIFA_World_Cup,-2.042225,14.575495,-16.617720,47,48,Lionel Messi,Lionel Messi
13,example-worldCup-unanswerable,example-worldCup,tzg292,من الذي تم اختياره كأكثر لاعب تهذيبًا في بطولة...,The 2022 FIFA World Cup was the 22nd FIFA Worl...,ar,False,-1,,https://en.wikipedia.org/wiki/2022_FIFA_World_Cup,-2.008400,14.459633,-16.468033,52,53,Lionel Messi,Lionel Messi
14,example-teleguLang-answerable,example-teleguLang,tzg292,భారతదేశంలో ఎన్ని అధికారిక భాషలు ఉన్నాయి?,Telugu is one of the 22 languages with officia...,te,True,21,22,https://en.wikipedia.org/wiki/Telugu_language#...,0.214378,12.077137,-11.862759,22,22,22,22
15,example-teleguLang-unanswerable,example-teleguLang,tzg292,భారతదేశంలో ఎన్ని భాషలు ఉన్నాయి?,Telugu is one of the 22 languages with officia...,te,False,-1,,https://en.wikipedia.org/wiki/Telugu_language#...,0.099766,12.222844,-12.123078,18,18,22,22
16,example-birthday-answerable,example-birthday,tzg292,ఆగస్టు 29న తన పుట్టినరోజును జరుపుకునే వ్యక్తి ...,Telugu Language Day is celebrated every year o...,te,True,87,Gidugu Venkata Ramamurthy,https://en.wikipedia.org/wiki/Telugu_language#...,0.102210,11.418958,-11.316748,44,52,Gidugu Venkata Ramamurthy,Gidugu Venkata Ramamurthy
17,example-birthday-unanswerable,example-birthday,tzg292,ఫిబ్రవరి 29న తన పుట్టినరోజును జరుపుకునే వ్యక్త...,Telugu Language Day is celebrated every year o...,te,False,-1,,https://en.wikipedia.org/wiki/Telugu_language#...,0.569836,11.316668,-10.746832,45,53,Gidugu Venkata Ramamurthy,Gidugu Venkata Ramamurthy
18,example-seoul-answerable,example-seoul,tzg292,서울의 주요 종교는 무엇인가요?,The two major religions in Seoul are Christian...,ko,True,37,Christianity and Buddhism,https://en.wikipedia.org/wiki/Seoul#Religion,-2.234689,11.442082,-13.676771,21,23,Christianity and Buddhism,Christianity and Buddhism
19,example-seoul-unanswerable,example-seoul,tzg292,서울에서 세 번째로 큰 종교는 무엇인가요?,The two major religions in Seoul are Christian...,ko,False,-1,,https://en.wikipedia.org/wiki/Seoul#Religion,-1.714736,12.056896,-13.771632,24,26,Christianity and Buddhism,Christianity and Buddhism
20,example-quantum-answerable,example-quantum,cbp183,ما هو حد الفيزياء الكلاسيكية؟,Quantum mechanics can describe many systems th...,ar,True,223,describing aspects at very small submicroscopi...,https://de.wikipedia.org/wiki/Quantenphysik,-0.888863,1.859915,-2.748779,34,48,ordinary (macroscopic and (optical) microscopi...,ordinary (macroscopic and (optical) microscopi...
21,example-quantum-unanswerable,example-quantum,cbp183,ما هو حد الفيزياء الكمومية؟,Quantum mechanics can describe many systems th...,ar,False,-1,,https://de.wikipedia.org/wiki/Quantenphysik,-0.625255,1.619898,-2.245152,34,48,ordinary (macroscopic and (optical) microscopi...,ordinary (macroscopic and (optical) microscopi...
22,example-particle-answerable,example-particle,cbp183,ما هو الجسيم الحر في بُعد مكاني واحد؟,The simplest example of a quantum system with ...,ar,True,0,The simplest example of a quantum system with ...,https://de.wikipedia.org/wiki/Quantenphysik,-0.274855,5.956538,-6.231393,34,40,free particle in a single spatial dimension,free particle in a single spatial dimension
23,example-particle-unanswerable,example-particle,cbp183,ما هو الجسيم الحر في ثلاثة أبعاد مكانية؟,The simplest example of a quantum system with ...,ar,False,-1,,https://de.wikipedia.org/wiki/Quantenphysik,-0.222248,5.665097,-5.887345,34,40,free particle in a single spatial dimension,free particle in a single spatial dimension
24,example-einstein-answerable,example-einstein,cbp183,ما هي أشهر معادلة في العالم؟,Albert Einstein (14 March 1879 – 18 April 1955...,ar,True,238,E = mc2,https://en.wikipedia.org/wiki/Albert_Einstein,-0.279531,11.720641,-12.000172,58,62,E = mc2,E = mc2
25,example-einstein-unanswerable,example-einstein,cbp183,في أي عام نشر أينشتاين معادلة تكافؤ الكتلة وال...,Albert Einstein (14 March 1879 – 18 April 1955...,ar,False,-1,,https://en.wikipedia.org/wiki/Albert_Einstein,3.412926,4.313463,-0.900537,72,76,E = mc2,E = mc2
26,example-father-answerable,example-father,cbp183,ماذا كان يعمل والد أينشتاين؟,Einstein was born in Ulm as a subject to the K...,ar,True,169,salesman and engineer,https://en.wikipedia.org/wiki/Albert_Einstein,-2.283736,7.271112,-9.554848,44,45,Hermann Einstein,Hermann Einstein
27,example-father-unanswerable,example-father,cbp183,أين درس والد أينشتاين؟,Einstein was born in Ulm as a subject to the K...,ar,False,-1,,https://en.wikipedia.org/wiki/Albert_Einstein,-0.699896,7.178455,-7.878351,15,15,Ulm,Ulm
28,example-relativity-answerable,example-relativity,cbp183,ఐన్‌స్టీన్ గురుత్వాకర్షణ సిద్ధాంతాన్ని అభివృద్...,General relativity (GR) is a theory of gravita...,te,True,90,1907,https://en.wikipedia.org/wiki/Albert_Einstein,2.676091,12.876906,-10.200815,52,54,1907 and 1915,1907 and 1915
29,example-relativity-unanswerable,example-relativity,cbp183,1905లో ఐన్‌స్టీన్ ఏమి చేశాడు?,General relativity (GR) is a theory of gravita...,te,False,-1,,https://en.wikipedia.org/wiki/Albert_Einstein,2.901674,1.245882,1.655792,31,31,Einstein,Einstein

## Week 43 - Zero-shot transfer to Japanese

## Week 43 - Alternative span architecture extension

### Load model

In [ ]:
import torch, torch.nn as nn, torch.nn.functional as F
from transformers import AutoModel

In [ ]:
device = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)

print(device)

cuda

In [ ]:
class BiaffinneHeadQA(nn.Module):
  def __init__(self, model_name, dim_projs=8, max_predicted_span=64):
    super().__init__()

    self.encoder = AutoModel.from_pretrained(model_name)
    h_dim = self.encoder.config.hidden_size # encoder contextual embedding dim size (= 768)

    self.S = nn.Sequential(nn.Linear(h_dim, dim_projs), nn.GELU())
    self.E = nn.Sequential(nn.Linear(h_dim, dim_projs), nn.GELU())

    self.U = nn.Parameter(torch.empty(dim_projs,dim_projs))
    nn.init.xavier_uniform_(self.U)

    self.W_s = nn.Linear(dim_projs, 1)
    self.W_e = nn.Linear(dim_projs, 1, bias=False)

    self.max_predicted_span = max_predicted_span


  def span_scores(self, input_ids, attention_mask, token_type_ids):
    h = self.encoder(
        input_ids=input_ids,
        attention_mask=attention_mask,
        token_type_ids=token_type_ids
    ).last_hidden_state

    s = self.S(h)
    e = self.E(h)

    bilinear = (s @ self.U) @ (e.transpose(1,2))

    start = self.W_s(s)
    end = self.W_e(e).transpose(1,2)

    return bilinear + start + end

  def mask_scores(self,scores, attention_mask, token_type_ids):
    B, T, _ = scores.shape

    pos = (token_type_ids == 1) & (attention_mask == 1)

    # mask [SEP] context token
    last = attention_mask.sum(dim=1) - 1
    pos[torch.arange(B, device=scores.device), last] = False

    idx = torch.arange(T, device=scores.device)
    diff = idx.unsqueeze(0) - idx.unsqueeze(-1)
    band = (diff >= 0) & (diff < self.max_predicted_span)

    valid = band.unsqueeze(0) & pos.unsqueeze(1) & pos.unsqueeze(2)
    valid[:, 0, 0] = True

    return scores.masked_fill(~valid, -1e4)



  def forward(self, input_ids, attention_mask, token_type_ids,
              start_positions=None, end_positions=None):
    scores = self.span_scores(input_ids, attention_mask, token_type_ids)
    scores = self.mask_scores(scores, attention_mask, token_type_ids)
    out = {"scores": scores}
    if start_positions is not None:
      T = scores.size(dim=1)
      out["loss"] = F.cross_entropy(scores.flatten(1),
                                    start_positions*T + end_positions)
    return out

In [ ]:
MODEL_NAME = "google-bert/bert-base-multilingual-cased"

bert_tokenizer = AutoTokenizer.from_pretrained(
    MODEL_NAME,
    use_fast=True,
)

BQA_MODEL_PATH = "./models_week43/BQA_extension_model"

state_dict = torch.load(f"{BQA_MODEL_PATH}.pth", weights_only=True)
bqa_model = BiaffinneHeadQA(MODEL_NAME).to(device)
bqa_model.load_state_dict(state_dict)

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertModel LOAD REPORT from: google-bert/bert-base-multilingual-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [ ]:
def get_validation_scores(row, model=bqa_model):
    encoding = bert_tokenizer(
        row["question"],
        row["context"],
        max_length=512,
        truncation="only_second",
        padding="max_length",
        return_offsets_mapping=True,
        return_tensors="pt",
    )

    model_inputs = {
        "input_ids": encoding["input_ids"].to(device),
        "attention_mask": encoding["attention_mask"].to(device),
        "token_type_ids": encoding["token_type_ids"].to(device),
    }

    model.eval()

    with torch.no_grad():
        outputs = model(**model_inputs)

    scores = outputs["scores"].squeeze(dim=0)

    input_ids = encoding["input_ids"][0]
    offsets = encoding["offset_mapping"][0].tolist()
    sequence_ids = encoding.sequence_ids(0)

    cls_span_score = scores[0,0]

    scores_ = scores.clone()
    scores_[0,0] = float("-inf")
    idx = torch.argmax(scores_)
    r,c = torch.unravel_index(idx, scores_.shape)

    best_span_score = scores_[r,c]
    best_start = r.item()
    best_end = c.item()

    char_start = offsets[best_start][0]
    char_end = offsets[best_end][1]

    best_span = row["context"][char_start:char_end]

    no_answer_score = cls_span_score - best_span_score

    return pd.Series({
        "cls_span_score": cls_span_score.item(),
        "best_span_score": best_span_score.item(),
        "no_answer_score": no_answer_score.item(),
        "best_start_token": best_start,
        "best_end_token": best_end,
        "best_span": best_span,
    })

In [ ]:
import string

def squad_v2_normalize(text):
    text = text.lower()

    text = "".join(
        character
        for character in text
        if character not in string.punctuation
    )

    text = re.sub(r"\b(a|an|the)\b", " ", text)

    return " ".join(text.split())

def exact_match(prediction, gold):
    return float(squad_v2_normalize(prediction) == squad_v2_normalize(gold))

def token_f1(prediction, gold):
    prediction_tokens = squad_v2_normalize(prediction).split()
    gold_tokens = squad_v2_normalize(gold).split()

    if not prediction_tokens or not gold_tokens:
      return float(prediction_tokens == gold_tokens)

    overlap_number = sum((Counter(prediction_tokens) & Counter(gold_tokens)).values())

    if overlap_number == 0:
      return 0.0

    precision = overlap_number / len(prediction_tokens)
    recall = overlap_number / len(gold_tokens)

    return 2 * precision * recall / (precision + recall)

### Extraction

In [ ]:
CHALLENGE_PATH = "./challenge-pairs/challenge.json"

with open(CHALLENGE_PATH, "r", encoding="utf-8") as file:
    challenge_data = json.load(file)

df_challenge = pd.DataFrame(challenge_data)

challenge_scores = df_challenge.apply(
    get_validation_scores,
    axis=1,
)

float_columns = [
    "cls_span_score",
    "best_span_score",
    "no_answer_score",
]

integer_columns = [
    "best_start_token",
    "best_end_token",
]

challenge_scores[float_columns] = challenge_scores[
    float_columns
].apply(
    pd.to_numeric,
    errors="raise",
)

challenge_scores[integer_columns] = challenge_scores[
    integer_columns
].apply(
    pd.to_numeric,
    errors="raise",
).astype("int64")

df_challenge = pd.concat(
    [df_challenge, challenge_scores],
    axis=1,
)
df_challenge

,id,pair_id,created_by,question,context,lang,answerable,answer_start,answer,source_url,cls_span_score,best_span_score,no_answer_score,best_start_token,best_end_token,best_span
0,south-korea-geography-answerable,south-korea-geography,gdw810,대한민국은 어느 대륙에 위치해 있나요?,"South Korea, officially the Republic of Korea ...",ko,True,74,Asia,https://en.wikipedia.org/wiki/South_Korea#Geog...,0.697222,5.748847,-5.051625,32,33,East Asia
1,south-korea-geography-unanswerable,south-korea-geography,gdw810,대한민국은 어느 반구에 위치해 있나요?,"South Korea, officially the Republic of Korea ...",ko,False,-1,,https://en.wikipedia.org/wiki/South_Korea#Geog...,0.690511,6.622225,-5.931714,32,33,East Asia
2,seoul-history-answerable,seoul-history,gdw810,서울은 몇 년에 세워졌나요?,Seoul's history traces back to 18 BC when it w...,ko,True,31,18 BC,https://en.wikipedia.org/wiki/Seoul,0.756562,8.563862,-7.807300,20,21,18 BC
3,seoul-history-unanswerable,seoul-history,gdw810,서울은 몇 년에 파괴되었나요?,Seoul's history traces back to 18 BC when it w...,ko,False,-1,,https://en.wikipedia.org/wiki/Seoul,0.570542,7.370981,-6.800438,21,22,18 BC
4,tokyo-history-answerable,tokyo-history,gdw810,도쿄가 당시 에도라는 이름으로 도쿠가와 막부의 중심지가 된 해는 언제인가?,"Tokyo, originally known as Edo, rose to politi...",ko,True,64,1603,https://en.wikipedia.org/wiki/Tokyo,0.836293,9.112430,-8.276136,38,38,1603
5,tokyo-history-unanswerable,tokyo-history,gdw810,에도가 도쿠가와 막부의 중심지가 된 달은 언제인가?,"Tokyo, originally known as Edo, rose to politi...",ko,False,-1,,https://en.wikipedia.org/wiki/Tokyo,1.123200,9.634865,-8.511665,33,33,1603
6,bloomberg-answerable,bloomberg,gdw810,블룸버그 뉴스는 어디에 텔레비전 방송국을 개설했나요?,"During this growth period, Bloomberg News open...",ko,True,79,New York,https://en.wikipedia.org/wiki/Bloomberg_News,0.752092,9.144732,-8.392641,34,35,New York
7,bloomberg-unanswerable,bloomberg,gdw810,블룸버그 뉴스는 사무실을 몇 개 소유하고 있었나요?,"During this growth period, Bloomberg News open...",ko,False,-1,,https://en.wikipedia.org/wiki/Bloomberg_News,0.457070,1.908381,-1.451311,34,35,New York
8,computer-security-answerable,computer-security,gdw810,DDoS 공격은 어디에서 발생하나요?,While a network attack from a single IP addres...,ko,True,195,a large number of points,https://en.wikipedia.org/wiki/Computer_security,0.746596,3.999547,-3.252951,19,25,network attack from a single IP address
9,computer-security-unanswerable,computer-security,gdw810,DDoS 공격은 정확히 몇 개의 지점에서 발생하나요?,While a network attack from a single IP addres...,ko,False,-1,,https://en.wikipedia.org/wiki/Computer_security,0.793870,3.896076,-3.102206,67,70,large number of points
10,example-egypt-answerable,example-egypt,tzg292,ما هو عدد سكان مصر؟,"Egypt, officially the Arab Republic of Egypt, ...",ar,True,163,107 million,https://en.wikipedia.org/wiki/Egypt,0.500764,7.941221,-7.440457,38,39,107 million
11,example-egypt-unanswerable,example-egypt,tzg292,ما هي الكثافة السكانية في مصر؟,"Egypt, officially the Arab Republic of Egypt, ...",ar,False,-1,,https://en.wikipedia.org/wiki/Egypt,0.385328,8.087337,-7.702008,39,40,107 million
12,example-worldCup-answerable,example-worldCup,tzg292,من الذي تم اختياره كأفضل لاعب في بطولة كأس الع...,The 2022 FIFA World Cup was the 22nd FIFA Worl...,ar,True,153,Lionel Messi,https://en.wikipedia.org/wiki/2022_FIFA_World_Cup,0.427153,8.046036,-7.618883,47,48,Lionel Messi
13,example-worldCup-unanswerable,example-worldCup,tzg292,من الذي تم اختياره كأكثر لاعب تهذيبًا في بطولة...,The 2022 FIFA World Cup was the 22nd FIFA Worl...,ar,False,-1,,https://en.wikipedia.org/wiki/2022_FIFA_World_Cup,0.409230,7.853409,-7.444179,52,53,Lionel Messi
14,example-teleguLang-answerable,example-teleguLang,tzg292,భారతదేశంలో ఎన్ని అధికారిక భాషలు ఉన్నాయి?,Telugu is one of the 22 languages with officia...,te,True,21,22,https://en.wikipedia.org/wiki/Telugu_language#...,0.927797,10.359939,-9.432141,22,22,22
15,example-teleguLang-unanswerable,example-teleguLang,tzg292,భారతదేశంలో ఎన్ని భాషలు ఉన్నాయి?,Telugu is one of the 22 languages with officia...,te,False,-1,,https://en.wikipedia.org/wiki/Telugu_language#...,0.962168,10.226257,-9.264090,18,18,22
16,example-birthday-answerable,example-birthday,tzg292,ఆగస్టు 29న తన పుట్టినరోజును జరుపుకునే వ్యక్తి ...,Telugu Language Day is celebrated every year o...,te,True,87,Gidugu Venkata Ramamurthy,https://en.wikipedia.org/wiki/Telugu_language#...,0.468484,8.327389,-7.858904,44,52,Gidugu Venkata Ramamurthy
17,example-birthday-unanswerable,example-birthday,tzg292,ఫిబ్రవరి 29న తన పుట్టినరోజును జరుపుకునే వ్యక్త...,Telugu Language Day is celebrated every year o...,te,False,-1,,https://en.wikipedia.org/wiki/Telugu_language#...,0.458707,8.366309,-7.907602,45,53,Gidugu Venkata Ramamurthy
18,example-seoul-answerable,example-seoul,tzg292,서울의 주요 종교는 무엇인가요?,The two major religions in Seoul are Christian...,ko,True,37,Christianity and Buddhism,https://en.wikipedia.org/wiki/Seoul#Religion,0.746286,7.602588,-6.856302,21,21,Christianity
19,example-seoul-unanswerable,example-seoul,tzg292,서울에서 세 번째로 큰 종교는 무엇인가요?,The two major religions in Seoul are Christian...,ko,False,-1,,https://en.wikipedia.org/wiki/Seoul#Religion,0.701937,8.107225,-7.405289,24,24,Christianity
20,example-quantum-answerable,example-quantum,cbp183,ما هو حد الفيزياء الكلاسيكية؟,Quantum mechanics can describe many systems th...,ar,True,223,describing aspects at very small submicroscopi...,https://de.wikipedia.org/wiki/Quantenphysik,0.490048,2.626486,-2.136439,34,48,ordinary (macroscopic and (optical) microscopi...
21,example-quantum-unanswerable,example-quantum,cbp183,ما هو حد الفيزياء الكمومية؟,Quantum mechanics can describe many systems th...,ar,False,-1,,https://de.wikipedia.org/wiki/Quantenphysik,0.482147,2.844610,-2.362463,34,48,ordinary (macroscopic and (optical) microscopi...
22,example-particle-answerable,example-particle,cbp183,ما هو الجسيم الحر في بُعد مكاني واحد؟,The simplest example of a quantum system with ...,ar,True,0,The simplest example of a quantum system with ...,https://de.wikipedia.org/wiki/Quantenphysik,0.553033,5.348847,-4.795815,34,40,free particle in a single spatial dimension
23,example-particle-unanswerable,example-particle,cbp183,ما هو الجسيم الحر في ثلاثة أبعاد مكانية؟,The simplest example of a quantum system with ...,ar,False,-1,,https://de.wikipedia.org/wiki/Quantenphysik,0.523926,5.132167,-4.608241,38,40,single spatial dimension
24,example-einstein-answerable,example-einstein,cbp183,ما هي أشهر معادلة في العالم؟,Albert Einstein (14 March 1879 – 18 April 1955...,ar,True,238,E = mc2,https://en.wikipedia.org/wiki/Albert_Einstein,0.468916,5.327765,-4.858849,11,12,Albert Einstein
25,example-einstein-unanswerable,example-einstein,cbp183,في أي عام نشر أينشتاين معادلة تكافؤ الكتلة وال...,Albert Einstein (14 March 1879 – 18 April 1955...,ar,False,-1,,https://en.wikipedia.org/wiki/Albert_Einstein,0.584888,-0.041975,0.626862,25,26,Albert Einstein
26,example-father-answerable,example-father,cbp183,ماذا كان يعمل والد أينشتاين؟,Einstein was born in Ulm as a subject to the K...,ar,True,169,salesman and engineer,https://en.wikipedia.org/wiki/Albert_Einstein,0.401021,3.512530,-3.111509,89,99,Elektrotechnische Fabrik J. Einstein & Cie
27,example-father-unanswerable,example-father,cbp183,أين درس والد أينشتاين؟,Einstein was born in Ulm as a subject to the K...,ar,False,-1,,https://en.wikipedia.org/wiki/Albert_Einstein,0.483451,7.820601,-7.337150,15,15,Ulm
28,example-relativity-answerable,example-relativity,cbp183,ఐన్‌స్టీన్ గురుత్వాకర్షణ సిద్ధాంతాన్ని అభివృద్...,General relativity (GR) is a theory of gravita...,te,True,90,1907,https://en.wikipedia.org/wiki/Albert_Einstein,0.637111,8.904799,-8.267688,52,52,1907
29,example-relativity-unanswerable,example-relativity,cbp183,1905లో ఐన్‌స్టీన్ ఏమి చేశాడు?,General relativity (GR) is a theory of gravita...,te,False,-1,,https://en.wikipedia.org/wiki/Albert_Einstein,0.625697,3.680860,-3.055163,31,31,Einstein

In [ ]:
best_threshold = -1.3

predictions = [
    ""
    if score > best_threshold
    else str(best_span)
    for score, best_span in zip(
        df_challenge["no_answer_score"],
        df_challenge["best_span"],
    )
]

f1_scores = [
    token_f1(prediction, gold)
    for prediction, gold in zip(
        predictions,
        df_challenge["answer"],
    )
]

exact_scores = [
    exact_match(prediction, gold)
    for prediction, gold in zip(
        predictions,
        df_challenge["answer"],
    )
]

unanswerable_exact_scores = [
    exact_match(prediction, gold)
    for prediction, gold, answer_start in zip(
        predictions,
        df_challenge["answer"],
        df_challenge["answer_start"],
    )
    if answer_start == -1
]

gold_answerability = (df_challenge["answer_start"] != -1).astype(int).values
predicted_answerability = np.array([int(p.strip() != "") for p in predictions])
ans_macro_f1 = f1_score(
    gold_answerability,
    predicted_answerability,
    labels=[0, 1],
    average="macro",
    zero_division=0,
)

{
    "threshold": best_threshold,
    "ans_macro_f1": ans_macro_f1,
    "token_f1": np.mean(f1_scores),
    "exact_match": np.mean(exact_scores),
    "unanswerable_exact_match": np.mean(unanswerable_exact_scores),
}

{'threshold': -1.3,
 'ans_macro_f1': 0.4034090909090909,
 'token_f1': np.float64(0.34305555555555556),
 'exact_match': np.float64(0.3),
 'unanswerable_exact_match': np.float64(0.06666666666666667)}

In [ ]:
df_challenge = pd.concat(
    [df_challenge, pd.DataFrame(predictions)],
    axis=1,
)
df_challenge

,id,pair_id,created_by,question,context,lang,answerable,answer_start,answer,source_url,cls_span_score,best_span_score,no_answer_score,best_start_token,best_end_token,best_span,0
0,south-korea-geography-answerable,south-korea-geography,gdw810,대한민국은 어느 대륙에 위치해 있나요?,"South Korea, officially the Republic of Korea ...",ko,True,74,Asia,https://en.wikipedia.org/wiki/South_Korea#Geog...,0.697222,5.748847,-5.051625,32,33,East Asia,East Asia
1,south-korea-geography-unanswerable,south-korea-geography,gdw810,대한민국은 어느 반구에 위치해 있나요?,"South Korea, officially the Republic of Korea ...",ko,False,-1,,https://en.wikipedia.org/wiki/South_Korea#Geog...,0.690511,6.622225,-5.931714,32,33,East Asia,East Asia
2,seoul-history-answerable,seoul-history,gdw810,서울은 몇 년에 세워졌나요?,Seoul's history traces back to 18 BC when it w...,ko,True,31,18 BC,https://en.wikipedia.org/wiki/Seoul,0.756562,8.563862,-7.807300,20,21,18 BC,18 BC
3,seoul-history-unanswerable,seoul-history,gdw810,서울은 몇 년에 파괴되었나요?,Seoul's history traces back to 18 BC when it w...,ko,False,-1,,https://en.wikipedia.org/wiki/Seoul,0.570542,7.370981,-6.800438,21,22,18 BC,18 BC
4,tokyo-history-answerable,tokyo-history,gdw810,도쿄가 당시 에도라는 이름으로 도쿠가와 막부의 중심지가 된 해는 언제인가?,"Tokyo, originally known as Edo, rose to politi...",ko,True,64,1603,https://en.wikipedia.org/wiki/Tokyo,0.836293,9.112430,-8.276136,38,38,1603,1603
5,tokyo-history-unanswerable,tokyo-history,gdw810,에도가 도쿠가와 막부의 중심지가 된 달은 언제인가?,"Tokyo, originally known as Edo, rose to politi...",ko,False,-1,,https://en.wikipedia.org/wiki/Tokyo,1.123200,9.634865,-8.511665,33,33,1603,1603
6,bloomberg-answerable,bloomberg,gdw810,블룸버그 뉴스는 어디에 텔레비전 방송국을 개설했나요?,"During this growth period, Bloomberg News open...",ko,True,79,New York,https://en.wikipedia.org/wiki/Bloomberg_News,0.752092,9.144732,-8.392641,34,35,New York,New York
7,bloomberg-unanswerable,bloomberg,gdw810,블룸버그 뉴스는 사무실을 몇 개 소유하고 있었나요?,"During this growth period, Bloomberg News open...",ko,False,-1,,https://en.wikipedia.org/wiki/Bloomberg_News,0.457070,1.908381,-1.451311,34,35,New York,New York
8,computer-security-answerable,computer-security,gdw810,DDoS 공격은 어디에서 발생하나요?,While a network attack from a single IP addres...,ko,True,195,a large number of points,https://en.wikipedia.org/wiki/Computer_security,0.746596,3.999547,-3.252951,19,25,network attack from a single IP address,network attack from a single IP address
9,computer-security-unanswerable,computer-security,gdw810,DDoS 공격은 정확히 몇 개의 지점에서 발생하나요?,While a network attack from a single IP addres...,ko,False,-1,,https://en.wikipedia.org/wiki/Computer_security,0.793870,3.896076,-3.102206,67,70,large number of points,large number of points
10,example-egypt-answerable,example-egypt,tzg292,ما هو عدد سكان مصر؟,"Egypt, officially the Arab Republic of Egypt, ...",ar,True,163,107 million,https://en.wikipedia.org/wiki/Egypt,0.500764,7.941221,-7.440457,38,39,107 million,107 million
11,example-egypt-unanswerable,example-egypt,tzg292,ما هي الكثافة السكانية في مصر؟,"Egypt, officially the Arab Republic of Egypt, ...",ar,False,-1,,https://en.wikipedia.org/wiki/Egypt,0.385328,8.087337,-7.702008,39,40,107 million,107 million
12,example-worldCup-answerable,example-worldCup,tzg292,من الذي تم اختياره كأفضل لاعب في بطولة كأس الع...,The 2022 FIFA World Cup was the 22nd FIFA Worl...,ar,True,153,Lionel Messi,https://en.wikipedia.org/wiki/2022_FIFA_World_Cup,0.427153,8.046036,-7.618883,47,48,Lionel Messi,Lionel Messi
13,example-worldCup-unanswerable,example-worldCup,tzg292,من الذي تم اختياره كأكثر لاعب تهذيبًا في بطولة...,The 2022 FIFA World Cup was the 22nd FIFA Worl...,ar,False,-1,,https://en.wikipedia.org/wiki/2022_FIFA_World_Cup,0.409230,7.853409,-7.444179,52,53,Lionel Messi,Lionel Messi
14,example-teleguLang-answerable,example-teleguLang,tzg292,భారతదేశంలో ఎన్ని అధికారిక భాషలు ఉన్నాయి?,Telugu is one of the 22 languages with officia...,te,True,21,22,https://en.wikipedia.org/wiki/Telugu_language#...,0.927797,10.359939,-9.432141,22,22,22,22
15,example-teleguLang-unanswerable,example-teleguLang,tzg292,భారతదేశంలో ఎన్ని భాషలు ఉన్నాయి?,Telugu is one of the 22 languages with officia...,te,False,-1,,https://en.wikipedia.org/wiki/Telugu_language#...,0.962168,10.226257,-9.264090,18,18,22,22
16,example-birthday-answerable,example-birthday,tzg292,ఆగస్టు 29న తన పుట్టినరోజును జరుపుకునే వ్యక్తి ...,Telugu Language Day is celebrated every year o...,te,True,87,Gidugu Venkata Ramamurthy,https://en.wikipedia.org/wiki/Telugu_language#...,0.468484,8.327389,-7.858904,44,52,Gidugu Venkata Ramamurthy,Gidugu Venkata Ramamurthy
17,example-birthday-unanswerable,example-birthday,tzg292,ఫిబ్రవరి 29న తన పుట్టినరోజును జరుపుకునే వ్యక్త...,Telugu Language Day is celebrated every year o...,te,False,-1,,https://en.wikipedia.org/wiki/Telugu_language#...,0.458707,8.366309,-7.907602,45,53,Gidugu Venkata Ramamurthy,Gidugu Venkata Ramamurthy
18,example-seoul-answerable,example-seoul,tzg292,서울의 주요 종교는 무엇인가요?,The two major religions in Seoul are Christian...,ko,True,37,Christianity and Buddhism,https://en.wikipedia.org/wiki/Seoul#Religion,0.746286,7.602588,-6.856302,21,21,Christianity,Christianity
19,example-seoul-unanswerable,example-seoul,tzg292,서울에서 세 번째로 큰 종교는 무엇인가요?,The two major religions in Seoul are Christian...,ko,False,-1,,https://en.wikipedia.org/wiki/Seoul#Religion,0.701937,8.107225,-7.405289,24,24,Christianity,Christianity
20,example-quantum-answerable,example-quantum,cbp183,ما هو حد الفيزياء الكلاسيكية؟,Quantum mechanics can describe many systems th...,ar,True,223,describing aspects at very small submicroscopi...,https://de.wikipedia.org/wiki/Quantenphysik,0.490048,2.626486,-2.136439,34,48,ordinary (macroscopic and (optical) microscopi...,ordinary (macroscopic and (optical) microscopi...
21,example-quantum-unanswerable,example-quantum,cbp183,ما هو حد الفيزياء الكمومية؟,Quantum mechanics can describe many systems th...,ar,False,-1,,https://de.wikipedia.org/wiki/Quantenphysik,0.482147,2.844610,-2.362463,34,48,ordinary (macroscopic and (optical) microscopi...,ordinary (macroscopic and (optical) microscopi...
22,example-particle-answerable,example-particle,cbp183,ما هو الجسيم الحر في بُعد مكاني واحد؟,The simplest example of a quantum system with ...,ar,True,0,The simplest example of a quantum system with ...,https://de.wikipedia.org/wiki/Quantenphysik,0.553033,5.348847,-4.795815,34,40,free particle in a single spatial dimension,free particle in a single spatial dimension
23,example-particle-unanswerable,example-particle,cbp183,ما هو الجسيم الحر في ثلاثة أبعاد مكانية؟,The simplest example of a quantum system with ...,ar,False,-1,,https://de.wikipedia.org/wiki/Quantenphysik,0.523926,5.132167,-4.608241,38,40,single spatial dimension,single spatial dimension
24,example-einstein-answerable,example-einstein,cbp183,ما هي أشهر معادلة في العالم؟,Albert Einstein (14 March 1879 – 18 April 1955...,ar,True,238,E = mc2,https://en.wikipedia.org/wiki/Albert_Einstein,0.468916,5.327765,-4.858849,11,12,Albert Einstein,Albert Einstein
25,example-einstein-unanswerable,example-einstein,cbp183,في أي عام نشر أينشتاين معادلة تكافؤ الكتلة وال...,Albert Einstein (14 March 1879 – 18 April 1955...,ar,False,-1,,https://en.wikipedia.org/wiki/Albert_Einstein,0.584888,-0.041975,0.626862,25,26,Albert Einstein,
26,example-father-answerable,example-father,cbp183,ماذا كان يعمل والد أينشتاين؟,Einstein was born in Ulm as a subject to the K...,ar,True,169,salesman and engineer,https://en.wikipedia.org/wiki/Albert_Einstein,0.401021,3.512530,-3.111509,89,99,Elektrotechnische Fabrik J. Einstein & Cie,Elektrotechnische Fabrik J. Einstein & Cie
27,example-father-unanswerable,example-father,cbp183,أين درس والد أينشتاين؟,Einstein was born in Ulm as a subject to the K...,ar,False,-1,,https://en.wikipedia.org/wiki/Albert_Einstein,0.483451,7.820601,-7.337150,15,15,Ulm,Ulm
28,example-relativity-answerable,example-relativity,cbp183,ఐన్‌స్టీన్ గురుత్వాకర్షణ సిద్ధాంతాన్ని అభివృద్...,General relativity (GR) is a theory of gravita...,te,True,90,1907,https://en.wikipedia.org/wiki/Albert_Einstein,0.637111,8.904799,-8.267688,52,52,1907,1907
29,example-relativity-unanswerable,example-relativity,cbp183,1905లో ఐన్‌స్టీన్ ఏమి చేశాడు?,General relativity (GR) is a theory of gravita...,te,False,-1,,https://en.wikipedia.org/wiki/Albert_Einstein,0.625697,3.680860,-3.055163,31,31,Einstein,Einstein

## Week 43 - Translating questions to English

### Load Challenge Set

In [ ]:
CHALLENGE_PATH = "./challenge-pairs/challenge.json"

with open(CHALLENGE_PATH, "r", encoding="utf-8") as file:
    challenge_data = json.load(file)

df_challenge = pd.DataFrame(challenge_data)

In [ ]:
df_challenge.head()

,id,pair_id,created_by,question,context,lang,answerable,answer_start,answer,source_url
0,south-korea-geography-answerable,south-korea-geography,gdw810,대한민국은 어느 대륙에 위치해 있나요?,"South Korea, officially the Republic of Korea ...",ko,True,74,Asia,https://en.wikipedia.org/wiki/South_Korea#Geog...
1,south-korea-geography-unanswerable,south-korea-geography,gdw810,대한민국은 어느 반구에 위치해 있나요?,"South Korea, officially the Republic of Korea ...",ko,False,-1,,https://en.wikipedia.org/wiki/South_Korea#Geog...
2,seoul-history-answerable,seoul-history,gdw810,서울은 몇 년에 세워졌나요?,Seoul's history traces back to 18 BC when it w...,ko,True,31,18 BC,https://en.wikipedia.org/wiki/Seoul
3,seoul-history-unanswerable,seoul-history,gdw810,서울은 몇 년에 파괴되었나요?,Seoul's history traces back to 18 BC when it w...,ko,False,-1,,https://en.wikipedia.org/wiki/Seoul
4,tokyo-history-answerable,tokyo-history,gdw810,도쿄가 당시 에도라는 이름으로 도쿠가와 막부의 중심지가 된 해는 언제인가?,"Tokyo, originally known as Edo, rose to politi...",ko,True,64,1603,https://en.wikipedia.org/wiki/Tokyo

In [ ]:
df_challenge['question_translated'] = df_challenge.apply(translate_row, axis=1)

### Load model

In [ ]:
BERT_MODEL_PATH_ENG = "./models/week40_berts_eng"

bert_tokenizer_eng = AutoTokenizer.from_pretrained(
  BERT_MODEL_PATH_ENG
)

bert_model_eng = AutoModelForQuestionAnswering.from_pretrained(
  BERT_MODEL_PATH_ENG
)

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

In [ ]:
import torch

device = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)

bert_model_eng = bert_model_eng.to(device)

print(device)

cpu

### Evaluation Scores

In [ ]:
def get_validation_scores_eng(row):
    encoding = bert_tokenizer_eng(
        row["question_translated"],
        row["context"],
        max_length=512,
        truncation="only_second",
        padding="max_length",
        return_offsets_mapping=True,
        return_tensors="pt",
    )

    model_inputs = {
        "input_ids": encoding["input_ids"].to(device),
        "attention_mask": encoding["attention_mask"].to(device),
        "token_type_ids": encoding["token_type_ids"].to(device),
    }

    bert_model_eng.eval()

    with torch.no_grad():
        outputs = bert_model_eng(**model_inputs)

    start_logits = outputs.start_logits[0].cpu()
    end_logits = outputs.end_logits[0].cpu()

    input_ids = encoding["input_ids"][0]
    offsets = encoding["offset_mapping"][0].tolist()
    sequence_ids = encoding.sequence_ids(0)

    cls_span_score = (
        start_logits[0].item()
        + end_logits[0].item()
    )

    context_indices = [
        index
        for index, sequence_id in enumerate(sequence_ids)
        if sequence_id == 1
    ]

    best_span_score = float("-inf")
    best_start = None
    best_end = None

    for start_index in context_indices:
        for end_index in context_indices:
            if end_index < start_index:
                continue
            if end_index - start_index + 1 > 44:
                continue

            span_length = end_index - start_index + 1

            span_score = (
                start_logits[start_index].item()
                + end_logits[end_index].item()
            )

            if span_score > best_span_score:
                best_span_score = span_score
                best_start = start_index
                best_end = end_index

    char_start = offsets[best_start][0]
    char_end = offsets[best_end][1]

    best_span = row["context"][char_start:char_end]

    no_answer_score = cls_span_score - best_span_score

    return pd.Series({
        "cls_span_score": cls_span_score,
        "best_span_score": best_span_score,
        "no_answer_score": no_answer_score,
        "best_start_token": best_start,
        "best_end_token": best_end,
        "best_span": best_span,
    })

In [ ]:
bert_model_eng = bert_model_eng.to(device)

challenge_scores_eng = df_challenge.apply(
    get_validation_scores_eng,
    axis=1,
)

float_columns = [
    "cls_span_score",
    "best_span_score",
    "no_answer_score",
]

integer_columns = [
    "best_start_token",
    "best_end_token",
]

challenge_scores_eng[float_columns] = challenge_scores_eng[
    float_columns
].apply(
    pd.to_numeric,
    errors="raise",
)

challenge_scores_eng[integer_columns] = challenge_scores_eng[
    integer_columns
].apply(
    pd.to_numeric,
    errors="raise",
).astype("int64")

df_challenge = pd.concat(
    [df_challenge, challenge_scores_eng],
    axis=1,
)

In [ ]:
import string

def squad_v2_normalize(text):
    text = text.lower()

    text = "".join(
        character
        for character in text
        if character not in string.punctuation
    )

    text = re.sub(r"\b(a|an|the)\b", " ", text)

    return " ".join(text.split())

def exact_match(prediction, gold):
    return float(squad_v2_normalize(prediction) == squad_v2_normalize(gold))

def token_f1(prediction, gold):
    prediction_tokens = squad_v2_normalize(prediction).split()
    gold_tokens = squad_v2_normalize(gold).split()

    if not prediction_tokens or not gold_tokens:
      return float(prediction_tokens == gold_tokens)

    overlap_number = sum((Counter(prediction_tokens) & Counter(gold_tokens)).values())

    if overlap_number == 0:
      return 0.0

    precision = overlap_number / len(prediction_tokens)
    recall = overlap_number / len(gold_tokens)

    return 2 * precision * recall / (precision + recall)

In [ ]:
best_threshold = -2.7

predictions = [
    ""
    if score > best_threshold
    else str(best_span)
    for score, best_span in zip(
        df_challenge["no_answer_score"],
        df_challenge["best_span"],
    )
]

f1_scores = [
    token_f1(prediction, gold)
    for prediction, gold in zip(
        predictions,
        df_challenge["answer"],
    )
]

exact_scores = [
    exact_match(prediction, gold)
    for prediction, gold in zip(
        predictions,
        df_challenge["answer"],
    )
]

unanswerable_exact_scores = [
    exact_match(prediction, gold)
    for prediction, gold, answer_start in zip(
        predictions,
        df_challenge["answer"],
        df_challenge["answer_start"],
    )
    if answer_start == -1
]

{
    "threshold": best_threshold,
    "token_f1": np.mean(f1_scores),
    "exact_match": np.mean(exact_scores),
    "unanswerable_exact_match": np.mean(unanswerable_exact_scores),
}

{'threshold': -2.7,
 'token_f1': np.float64(0.3723484848484848),
 'exact_match': np.float64(0.3333333333333333),
 'unanswerable_exact_match': np.float64(0.0)}

In [ ]:
best_predictions = [
    ""
    if score > best_threshold
    else best_span
    for score, best_span in zip(
        df_challenge["no_answer_score"],
        df_challenge["best_span"],
    )
]

gold_answerability = (
    df_challenge["answer_start"] != -1
).astype(int)

predicted_answerability = np.array([
    int(prediction.strip() != "")
    for prediction in best_predictions
])

answerability_macro_f1 = f1_score(
    gold_answerability,
    predicted_answerability,
    labels=[0, 1],
    average="macro",
    zero_division=0,
)

print("Answerability macro-F1:", answerability_macro_f1)

Answerability macro-F1: 0.3181818181818182