<a href="https://colab.research.google.com/github/lzxatdk-tech/NLP_project/blob/main/reliable_multilingual_question_answering.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Environment Setup

## Mount data folder

In [1]:
from google.colab import drive
drive.mount('/content/drive')

import os
folder_path = '/content/drive/MyDrive/Shared_NLP_Project'

os.chdir(folder_path)

Mounted at /content/drive

## Download or load dataset

In [51]:
import os
import pandas as pd
from datasets import load_dataset, load_from_disk

TARGET_DIR = "./tydi_xor_rc"

if not os.path.exists(TARGET_DIR):
    print(f"Downloading dataset to {TARGET_DIR}...")
    dataset = load_dataset("coastalcph/tydi_xor_rc")
    dataset.save_to_disk(TARGET_DIR)
    print("Download and save complete.")
else:
    print(f"Found existing dataset at {TARGET_DIR}. Loading from disk...")
    dataset = load_from_disk(TARGET_DIR)
    print("Loading completes.")

if os.path.exists("train_dataset.csv"):
  df_train = pd.read_csv("train_dataset.csv")
else:
  df_train = dataset["train"].to_pandas()


if os.path.exists("val_dataset.csv"):
  df_val = pd.read_csv("val_dataset.csv")
else:
  df_val = dataset["validation"].to_pandas()

Found existing dataset at ./tydi_xor_rc. Loading from disk...
Loading completes.

## Imports

In [3]:
%pip install -q "nltk>=3.9,<4" "spacy>=3.8,<4" "transformers>=5,<6"
!python -m spacy download ko_core_news_sm en_core_web_sm

Collecting ko-core-news-sm==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/ko_core_news_sm-3.8.0/ko_core_news_sm-3.8.0-py3-none-any.whl (14.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.7/14.7 MB 66.7 MB/s eta 0:00:00
Requirement already satisfied: en_core_web_sm in /usr/local/lib/python3.13/dist-packages (3.8.0)
Installing collected packages: ko-core-news-sm
Successfully installed ko-core-news-sm-3.8.0
✔ Download and installation successful
You can now load the package via spacy.load('ko_core_news_sm')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.

In [4]:
!pip install -q datasets accelerate

In [80]:
import random
import re

import math
import numpy as np
import pandas as pd
import spacy
from datasets import load_dataset
from sklearn.feature_extraction import DictVectorizer
from sklearn.linear_model import SGDClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, f1_score
from transformers import (
    AutoModelForSeq2SeqLM,
    AutoTokenizer,
    AutoModelForQuestionAnswering,
    DefaultDataCollator,
    TrainingArguments,
    Trainer,
)
from torch.utils.data import DataLoader
from tqdm.auto import tqdm
from collections import Counter

random.seed(42)
np.random.seed(42)

## Spacy setup

In [6]:
nlp_ar_spacy = spacy.blank("ar")
nlp_ko_spacy = spacy.load("ko_core_news_sm")
nlp_te_spacy = spacy.blank("te")
nlp_en_spacy = spacy.load("en_core_web_sm")

## Translator

In [7]:
tokenizer = AutoTokenizer.from_pretrained("facebook/nllb-200-distilled-600M")
model = AutoModelForSeq2SeqLM.from_pretrained("facebook/nllb-200-distilled-600M", attn_implementation="sdpa", device_map="auto")

lang_code_trans = {"ar": "arb_Arab", "ko": "kor_Hang", "te": "tel_Telu", "en": "eng_Latn"}

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/846 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/564 [00:00<?, ?B/s]

sentencepiece.bpe.model: reconstructing file:   0%|          |  0.00B / 4.85MB

sentencepiece.bpe.model: downloading bytes:           |  0.00B

tokenizer.json: reconstructing file:   0%|          |  0.00B / 17.3MB

tokenizer.json: downloading bytes:           |  0.00B

special_tokens_map.json:   0%|          | 0.00/3.55k [00:00<?, ?B/s]

pytorch_model.bin: reconstructing file:   0%|          |  0.00B / 2.46GB

pytorch_model.bin: downloading bytes:           |  0.00B

model.safetensors: reconstructing file:   0%|          |  0.00B / 2.46GB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/512 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/189 [00:00<?, ?B/s]

In [8]:
def translate(text, source, target):
  tokenizer.src_lang = lang_code_trans[source]
  inputs = tokenizer(text, return_tensors="pt").to(model.device)

  if inputs.input_ids.shape[1] > 128: #
    print(text) #

  translated_tokens = model.generate(
    **inputs, forced_bos_token_id=tokenizer.convert_tokens_to_ids(lang_code_trans[target]), max_length=128
  )

  return tokenizer.batch_decode(translated_tokens, skip_special_tokens=True)[0]


def translate_row(row):
  text = row["question"]
  source = row["lang"]

  if source not in [TE, AR, KO]:
    return None
  return translate(text,source,"en")


TE = "te"
AR = "ar"
KO = "ko"
EN = "en"

te_example = "ప్రపంచంలో  మొట్టమొదటి దూర విద్య విద్యాలయం ఏ దేశంలో స్థాపించబడింది ?"
ar_example = "متى تدخلت روسيا في  الحرب الأهلية السورية؟"
ko_example = "30년 전쟁의 승자는 누구인가?"

print(te_example, "->", translate(te_example,TE,EN))
print(ar_example, "->", translate(ar_example,AR,EN))
print(ko_example, "->", translate(ko_example,KO,EN))

ప్రపంచంలో  మొట్టమొదటి దూర విద్య విద్యాలయం ఏ దేశంలో స్థాపించబడింది ? -> Which country was the first distance education college in the world established?
متى تدخلت روسيا في  الحرب الأهلية السورية؟ -> When did Russia intervene in the Syrian civil war?
30년 전쟁의 승자는 누구인가? -> Who is the winner of the Thirty Years' War?

## Data processing

In [9]:
# add column of question translated to english and save it to a new csv
if not os.path.exists("train_dataset.csv"):
  df_train["question_translated"] = df_train.apply(translate_row, axis=1)
  df_train.to_csv("train_dataset.csv", index=False)

if not os.path.exists("val_dataset.csv"):
  df_val["question_translated"] = df_train.apply(translate_row, axis=1)
  df_val.to_csv("val_dataset.csv", index=False)

In [10]:
df_train

,question,context,lang,answerable,answer_start,answer,answer_inlang,question_translated
0,উইকিলিকস কত সালে সর্বপ্রথম ইন্টারনেটে প্রথম তথ...,WikiLeaks () is an international non-profit or...,bn,True,182,2006,NaN,NaN
1,দ্বিতীয় বিশ্বযুদ্ধে কোন দেশ পরাজিত হয় ?,The war in Europe concluded with an invasion o...,bn,True,48,Germany,NaN,NaN
2,মার্কিন যুক্তরাষ্ট্রের সংবিধান অনুযায়ী মার্কিন...,Same-sex marriage in the United States expande...,bn,False,-1,no,NaN,NaN
3,আরব-ইসরায়েলি যুদ্ধে আরবের মোট কয়জন সৈন্যের মৃ...,The exact number of Arab casualties is unknown...,bn,True,39,unknown,NaN,NaN
4,বিশ্বে প্রথম পুঁজিবাদী সমাজ কবে গড়ে ওঠে ?,"As Thomas Hall (2000) notes, ""The Sung Empire ...",bn,True,1219,17th century,NaN,NaN
...,...,...,...,...,...,...,...,...
15338,소말리아는 2차 개헌을 언제 했나요?,"In February 2012, Somali government officials ...",ko,True,923,23 June 2012,NaN,When did Somalia make its second inauguration?
15339,세상에서 가장 먼저 시작된 교통수단은 무엇인가?,The first earth tracks were created by humans ...,ko,True,160,animals,NaN,What was the first transportation system in th...
15340,2019년 이집트의 지도자는 누구인가?,"Abdel Fattah Saeed Hussein Khalil El-Sisi ( """"...",ko,True,0,Abdel Fattah Saeed Hussein Khalil El-Sisi,NaN,Who is the leader of Egypt in 2019?
15341,독일에서 가장 인구밀도가 높은 도시는 무엇인가?,Munich (; ; ) is the capital and most populous...,ko,True,205,Berlin,NaN,What is the most densely populated city in Ger...
15342,개혁침례교는 신교와 상관관계가있는가?,"Anabaptism (from Neo-Latin ""anabaptista"", from...",ko,False,-1,no,NaN,Is Reformed Baptism related to the New Order?

In [11]:
df_val

,question,context,lang,answerable,answer_start,answer,answer_inlang
0,ఒరెగాన్ రాష్ట్రంలోని అతిపెద్ద నగరం ఏది ?,Portland is the largest city in the U.S. state...,te,True,0,Portland,NaN
1,కలరా వ్యాధిని మొదటగా ఏ దేశంలో కనుగొన్నారు ?,"The word cholera is from ""kholera"" from χολή ""...",te,True,99,Indian subcontinent,NaN
2,కలరా వ్యాధిని మొదటగా ఏ దేశంలో కనుగొన్నారు ?,Since it became widespread in the 19th century...,te,True,451,England,NaN
3,మొదటి ప్రపంచ యుద్ధం ఎప్పుడు మొదలయింది ?,World War I occurred from 1914 to 1918. In ter...,te,True,26,1914,NaN
4,మొదటి ప్రపంచ యుద్ధం ఎప్పుడు మొదలయింది ?,"World War I (often abbreviated as WWI or WW1),...",te,True,155,28 July 1914,NaN
...,...,...,...,...,...,...,...
3006,2011 జనగణన ప్రకారం రెయ్యలగడ్ద గ్రామములో పురుషు...,Reyyalagadda is a village belonging to Gangara...,te,True,378,37,37
3007,2011 జనాభా లెక్కల ప్రకారం బూతుమిల్లిపాడు గ్రామ...,Boothumillipadu is a village in Gannavaram man...,te,True,308,433,433
3008,2011 జనాభా లెక్కల ప్రకారం మల్లవేముల గ్రామ జనాభ...,Mallavemula is a village belonging to Chagalam...,te,False,-1,1131,1131
3009,2011 నాటికి రష్యా దేశ ప్రధాన మంత్రి ఎవరు?,"Andria Urushadze (; born April 25, 1968) is a ...",te,False,-1,Vladimir Putin,వ్లాదిమిర్ పుతిన్
3010,2011 భారత జనగణన గణాంకాల ప్రకారం గుంటూరు పట్టణ ...,"Guntur district is 11,391 sq. km. Spread over ...",te,False,-1,"743,654","743,654"

## Tokenizer

In [12]:
lang_tokenizer = {AR: nlp_ar_spacy, TE: nlp_te_spacy, KO: nlp_ko_spacy, EN: nlp_en_spacy}
L = {AR: "Arabic", KO: "Korean", TE: "Telegu", EN: "English"}

In [13]:
model_tokenizer = AutoTokenizer.from_pretrained("xlm-roberta-base")
model_tokenizer.tokenize("한국어 형태소를 분석합니다.")

config.json:   0%|          | 0.00/615 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/9.10M [00:00<?, ?B/s]

['▁한국어', '▁형태', '소', '를', '▁분석', '합니다', '.']

# Week 36

In [ ]:
import matplotlib.pyplot as plt
from collections import Counter

In [ ]:
df_train

,question,context,lang,answerable,answer_start,answer,answer_inlang
0,উইকিলিকস কত সালে সর্বপ্রথম ইন্টারনেটে প্রথম তথ...,WikiLeaks () is an international non-profit or...,bn,True,182,2006,None
1,দ্বিতীয় বিশ্বযুদ্ধে কোন দেশ পরাজিত হয় ?,The war in Europe concluded with an invasion o...,bn,True,48,Germany,None
2,মার্কিন যুক্তরাষ্ট্রের সংবিধান অনুযায়ী মার্কিন...,Same-sex marriage in the United States expande...,bn,False,-1,no,None
3,আরব-ইসরায়েলি যুদ্ধে আরবের মোট কয়জন সৈন্যের মৃ...,The exact number of Arab casualties is unknown...,bn,True,39,unknown,None
4,বিশ্বে প্রথম পুঁজিবাদী সমাজ কবে গড়ে ওঠে ?,"As Thomas Hall (2000) notes, ""The Sung Empire ...",bn,True,1219,17th century,None
...,...,...,...,...,...,...,...
15338,소말리아는 2차 개헌을 언제 했나요?,"In February 2012, Somali government officials ...",ko,True,923,23 June 2012,None
15339,세상에서 가장 먼저 시작된 교통수단은 무엇인가?,The first earth tracks were created by humans ...,ko,True,160,animals,None
15340,2019년 이집트의 지도자는 누구인가?,"Abdel Fattah Saeed Hussein Khalil El-Sisi ( """"...",ko,True,0,Abdel Fattah Saeed Hussein Khalil El-Sisi,None
15341,독일에서 가장 인구밀도가 높은 도시는 무엇인가?,Munich (; ; ) is the capital and most populous...,ko,True,205,Berlin,None
15342,개혁침례교는 신교와 상관관계가있는가?,"Anabaptism (from Neo-Latin ""anabaptista"", from...",ko,False,-1,no,None

In [ ]:
df_val

,question,context,lang,answerable,answer_start,answer,answer_inlang,question_translated
0,ఒరెగాన్ రాష్ట్రంలోని అతిపెద్ద నగరం ఏది ?,Portland is the largest city in the U.S. state...,te,True,0,Portland,NaN,What is the largest city in the state of Oregon?
1,కలరా వ్యాధిని మొదటగా ఏ దేశంలో కనుగొన్నారు ?,"The word cholera is from ""kholera"" from χολή ""...",te,True,99,Indian subcontinent,NaN,In which country was cholera first discovered?
2,కలరా వ్యాధిని మొదటగా ఏ దేశంలో కనుగొన్నారు ?,Since it became widespread in the 19th century...,te,True,451,England,NaN,In which country was cholera first discovered?
3,మొదటి ప్రపంచ యుద్ధం ఎప్పుడు మొదలయింది ?,World War I occurred from 1914 to 1918. In ter...,te,True,26,1914,NaN,When did World War I begin?
4,మొదటి ప్రపంచ యుద్ధం ఎప్పుడు మొదలయింది ?,"World War I (often abbreviated as WWI or WW1),...",te,True,155,28 July 1914,NaN,When did World War I begin?
...,...,...,...,...,...,...,...,...
3006,2011 జనగణన ప్రకారం రెయ్యలగడ్ద గ్రామములో పురుషు...,Reyyalagadda is a village belonging to Gangara...,te,True,378,37,37,"According to the 2011 census, how many males a..."
3007,2011 జనాభా లెక్కల ప్రకారం బూతుమిల్లిపాడు గ్రామ...,Boothumillipadu is a village in Gannavaram man...,te,True,308,433,433,"According to the 2011 census, how many people ..."
3008,2011 జనాభా లెక్కల ప్రకారం మల్లవేముల గ్రామ జనాభ...,Mallavemula is a village belonging to Chagalam...,te,False,-1,1131,1131,What is the population of Mallavem village as ...
3009,2011 నాటికి రష్యా దేశ ప్రధాన మంత్రి ఎవరు?,"Andria Urushadze (; born April 25, 1968) is a ...",te,False,-1,Vladimir Putin,వ్లాదిమిర్ పుతిన్,Who is the Prime Minister of Russia as of 2011?
3010,2011 భారత జనగణన గణాంకాల ప్రకారం గుంటూరు పట్టణ ...,"Guntur district is 11,391 sq. km. Spread over ...",te,False,-1,"743,654","743,654","According to the 2011 census of India, what is..."

In [ ]:
# remove inconsistencies
# check (answer == substring beginning at answer start)

df_train[(df_train["answerable"] == True) &
         (
            (df_train["answer_start"] + df_train["answer"].str.len() > df_train["context"].str.len()) |
            (
                df_train.apply(
                    lambda row: row["context"][
                        row["answer_start"]:
                        row["answer_start"] + len(row["answer"])
                    ] != row["answer"],
                    axis=1
                )
            )
         )
        ].loc[:,["context","answer","answer_start"]]


# no cases with answer context inconsistency in training split

Empty DataFrame
Columns: [context, answer, answer_start]
Index: []

In [ ]:
df_val[(df_val["answerable"] == True) &
         (
            (df_val["answer_start"] + df_val["answer"].str.len() > df_val["context"].str.len()) |
            (
                df_val.apply(
                    lambda row: row["context"][
                        row["answer_start"]:
                        row["answer_start"] + len(row["answer"])
                    ] != row["answer"],
                    axis=1
                )
            )
         )
        ].loc[:,["context","answer","answer_start"]]


# no cases with answer context inconsistency in validation split

Empty DataFrame
Columns: [context, answer, answer_start]
Index: []

In [ ]:
rows_with_missing_train = df_train[df_train[["question", "context", "answerable", "answer_start", "answer"]].isnull().any(axis=1)]
rows_with_missing_train

Empty DataFrame
Columns: [question, context, lang, answerable, answer_start, answer, answer_inlang]
Index: []

In [ ]:
rows_with_missing_val = df_val[df_val[["question", "context", "answerable", "answer_start", "answer"]].isnull().any(axis=1)]
rows_with_missing_val

Empty DataFrame
Columns: [question, context, lang, answerable, answer_start, answer, answer_inlang]
Index: []

In [ ]:
# True -> 1 && False -> 0

df_train = df_train.replace({True: 1, False: 0})
df_val = df_val.replace({True: 1, False: 0})

/tmp/ipykernel_679/221756984.py:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_train = df_train.replace({True: 1, False: 0})
/tmp/ipykernel_679/221756984.py:4: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_val = df_val.replace({True: 1, False: 0})

In [ ]:
def show_ans(df_train,df_val,label=""):
    train_ans_size = df_train[df_train["answerable"] == 1].shape[0]
    train_nonans_size = df_train[df_train["answerable"] == 0].shape[0]

    val_ans_size = df_val[df_val["answerable"] == 1].shape[0]
    val_nonans_size = df_val[df_val["answerable"] == 0].shape[0]

    print(label)
    print("\nTrain count:", df_train.shape[0])
    print("Val count:", df_val.shape[0])

    print("\nAnswerable questions:")
    print("\tTrain:", train_ans_size)
    print("\tVal:", val_ans_size)
    print("Non-answerable questions: ", )
    print ("\tTrain:", train_nonans_size)
    print ("\tVal:", val_nonans_size)

    print("\nAnswerability ratios: ")
    print("\t Train: ", train_ans_size/(train_nonans_size+train_ans_size))
    print("\t Val: ", val_ans_size/(val_ans_size+val_nonans_size))


    print("\nDuplicates in train:", df_train.duplicated(subset=["question","context"], keep=False).sum())
    print("Duplicates in val:", df_val.duplicated(subset=["question","context"], keep=False).sum())

In [ ]:
show_ans(df_train,df_val,label="Overall")

Overall

Train count: 15343
Val count: 3011

Answerable questions:
	Train: 13962
	Val: 2313
Non-answerable questions:
	Train: 1381
	Val: 698

Answerability ratios:
	 Train:  0.9099915270807535
	 Val:  0.7681833277980737

Duplicates in train: 34
Duplicates in val: 0

In [ ]:
# filter for Arabic, Korean and Telegu
df_train_ar = df_train[df_train["lang"] == "ar"]
df_val_ar = df_val[df_val["lang"] == "ar"]

df_train_ko = df_train[df_train["lang"] == "ko"]
df_val_ko = df_val[df_val["lang"] == "ko"]

df_train_te = df_train[df_train["lang"] == "te"]
df_val_te = df_val[df_val["lang"] == "te"]

# check for duplicates pairs (question,context)


# combine ar, ko and te
df_train_mlangs = pd.concat([df_train_ar,df_train_ko,df_train_te])
df_val_mlangs = pd.concat([df_val_ar,df_val_ko,df_val_te])

In [ ]:
show_ans(df_train_ar,df_val_ar, "Arabic")

Arabic

Train count: 2558
Val count: 415

Answerable questions:
	Train: 2303
	Val: 363
Non-answerable questions:
	Train: 255
	Val: 52

Answerability ratios:
	 Train:  0.900312744331509
	 Val:  0.8746987951807229

Duplicates in train: 0
Duplicates in val: 0

In [ ]:
show_ans(df_train_ko,df_val_ko, "Korean")

Korean

Train count: 2422
Val count: 356

Answerable questions:
	Train: 2359
	Val: 337
Non-answerable questions:
	Train: 63
	Val: 19

Answerability ratios:
	 Train:  0.9739884393063584
	 Val:  0.9466292134831461

Duplicates in train: 20
Duplicates in val: 0

In [ ]:
show_ans(df_train_te,df_val_te, "Telugu")

Telugu

Train count: 1355
Val count: 384

Answerable questions:
	Train: 1310
	Val: 291
Non-answerable questions:
	Train: 45
	Val: 93

Answerability ratios:
	 Train:  0.966789667896679
	 Val:  0.7578125

Duplicates in train: 0
Duplicates in val: 0

In [ ]:
show_ans(df_train_mlangs,df_val_mlangs, "Ar + Ko + Te")

Ar + Ko + Te

Train count: 6335
Val count: 1155

Answerable questions:
	Train: 5972
	Val: 991
Non-answerable questions:
	Train: 363
	Val: 164

Answerability ratios:
	 Train:  0.9426992896606157
	 Val:  0.858008658008658

Duplicates in train: 20
Duplicates in val: 0

In [ ]:
%pip install -q "nltk>=3.9,<4" "spacy>=3.8,<4" "transformers>=5,<6"
!python -m spacy download ko_core_news_sm en_core_web_sm

Collecting ko-core-news-sm==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/ko_core_news_sm-3.8.0/ko_core_news_sm-3.8.0-py3-none-any.whl (14.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.7/14.7 MB 74.3 MB/s eta 0:00:00
Requirement already satisfied: en_core_web_sm in /usr/local/lib/python3.13/dist-packages (3.8.0)
Installing collected packages: ko-core-news-sm
Successfully installed ko-core-news-sm-3.8.0
✔ Download and installation successful
You can now load the package via spacy.load('ko_core_news_sm')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.

In [ ]:
import spacy

nlp_ar_spacy = spacy.blank("ar")
nlp_ko_spacy = spacy.load("ko_core_news_sm")
nlp_te_spacy = spacy.blank("te")
nlp_en_spacy = spacy.load("en_core_web_sm")

In [ ]:

languages = {
    "Arabic":  (nlp_ar_spacy, df_train_ar, df_val_ar),
    "Korean":  (nlp_ko_spacy, df_train_ko, df_val_ko),
    "Telugu":  (nlp_te_spacy, df_train_te, df_val_te),
}

def token_lengths(nlp, series):
    return [len(doc) for doc in nlp.pipe(series.astype(str))]

lengths = {}
for lang, (nlp, df_train, df_val) in languages.items():
    lengths[(lang, "question")] = {}
    lengths[(lang, "context")] = {}
    for split, df in [("Train", df_train), ("Val", df_val)]:
        for field in ["question", "context"]:
            lengths[(lang, field)][split] = token_lengths(nlp, df[field])

lengths[("Overall", "question")] = {}
lengths[("Overall", "context")] = {}
for split in ["Train", "Val"]:
    for field in ["question", "context"]:
        lengths[("Overall", field)][split] = sum(
            (lengths[(lang, field)][split] for lang in languages), []
        )

rows = []
for (lang, field), vals in lengths.items():
    q1_train, med_train, q3_train = np.percentile(vals["Train"], [25, 50, 75])
    q1_val, med_val, q3_val = np.percentile(vals["Val"], [25, 50, 75])
    rows.append({
        "Language": lang,
        "Field": field.capitalize(),
        "Median_Train": med_train,
        "Q1_Train": q1_train,
        "Q3_Train": q3_train,
        "IQR_Train": q3_train - q1_train,
        "Median_Val": med_val,
        "Q1_Val": q1_val,
        "Q3_Val": q3_val,
        "IQR_Val": q3_val- q1_val
    })

summary = pd.DataFrame(rows)
display(summary)

,Language,Field,Median_Train,Q1_Train,Q3_Train,IQR_Train,Median_Val,Q1_Val,Q3_Val,IQR_Val
0,Arabic,Question,7.0,6.0,9.0,3.0,7.0,6.00,9.0,3.00
1,Arabic,Context,100.5,67.0,145.0,78.0,99.0,67.50,142.5,75.00
2,Korean,Question,6.0,5.0,7.0,2.0,6.0,5.00,7.0,2.00
3,Korean,Context,101.0,69.0,143.0,74.0,98.0,60.75,146.0,85.25
4,Telugu,Question,6.0,5.0,8.0,3.0,7.0,6.00,8.0,2.00
5,Telugu,Context,94.0,62.0,133.5,71.5,121.0,89.50,162.0,72.50
6,Overall,Question,6.0,5.0,8.0,3.0,7.0,6.00,8.0,2.00
7,Overall,Context,100.0,67.0,142.0,75.0,107.0,71.50,151.5,80.00

In [ ]:
# most commom tokens for each language

lang_tokenizer = {AR: nlp_ar_spacy, TE: nlp_te_spacy, KO: nlp_ko_spacy, EN: nlp_en_spacy}
L = {AR: "Arabic", KO: "Korean", TE: "Telegu", EN: "English"}

def most_commom_token_lang(df_train_lang,lang):
  tokens = [token.text for doc in lang_tokenizer[lang].pipe(df_train_lang["question"].astype(str)) for token in doc]
  cnt = Counter(tokens)
  most_commom = cnt.most_common(5)
  print("Most commom tokens in", L[lang]+":")
  for i in range(5):
    token,freq = most_commom[i]
    print(f"{i+1}. {token} ({freq}) -> {translate_cached(token,lang,EN)}") # remove # from beginning of token

  print("Total tokens in train:", len(tokens))
  print()


most_commom_token_lang(df_train_ar,AR)
most_commom_token_lang(df_train_ko,KO)
most_commom_token_lang(df_train_te,TE)

Most commom tokens in Arabic:
1. ؟ (2556) -> Seeker?
2. في (593) -> at
3. من (586) -> Of
4. متى (535) -> When
5. ما (442) -> public health kind of influence and impact. This is my first project after my Master in public health
Total tokens in train: 19079

Most commom tokens in Korean:
1. ? (2419) -> User Guide
2. 가장 (527) -> the most
3. 무엇인가 (496) -> LAW OF KARMA WORK?
4. 언제 (336) -> WHEN
5. 몇 (234) -> Few
Total tokens in train: 14323

Most commom tokens in Telegu:
1. ? (1355) -> ?
2. ఎవరు (274) -> Who
3. ఏది (192) -> Which
4. ఎన్ని (165) -> How many
5. ఎప్పుడు (154) -> When
Total tokens in train: 9109

In [ ]:
# evaluation metrics answerability

def answerability_scores(annotated, predicted):
    TP = TN = FP = FN = 0
    for a, p in zip(annotated, predicted):
        if a == 1:
          if p == 1: TP += 1
          else: FN += 1
        else:
          if p == 1: FP += 1
          else: TN += 1

    precision_ans = TP / (TP + FP) if TP + FP else 0.0
    recall_ans = TP / (TP + FN) if TP + FN else 0.0
    f1_ans = (2*precision_ans*recall_ans) / (precision_ans + recall_ans) if precision_ans + recall_ans else 0.0

    precision_unans = TN / (TN + FN) if TN + FN else 0.0
    recall_unans = TN / (TN + FP) if TP + FN else 0.0
    f1_unans = (2*precision_unans*recall_unans) / (precision_unans + recall_unans) if precision_unans + recall_unans else 0.0

    accuracy = (TP+TN) / (TP+TN+FP+FN) if TP+TN+FP+FN else 0.0

    return precision_ans, recall_ans, f1_ans, precision_unans, recall_unans, f1_unans, accuracy

def evaluate_answerability(name, annotated, predicted):
  precision_ans, recall_ans, f1_ans, precision_unans, recall_unans, f1_unans, accuracy = answerability_scores(annotated, predicted)
  result = {
      "model": name,

      "accuracy": accuracy,

      "macro_avg_f1": (f1_ans + f1_unans)/2,

      "precision_answerable": precision_ans,
      "recall_answerable": recall_ans,
      "f1_answerable": f1_ans,

      "precision_unanswerable": precision_unans,
      "recall_unanswerable": recall_unans,
      "f1_unanswerable": f1_unans,
  }
  return result



# confusion matrix - TODO

In [ ]:
# majority-class baseline
def majority_class_baseline_predict(df_train_lang):
  return df_train_lang["answerable"].mode()[0]

mcb_ar_metrics = evaluate_answerability("majority class baseline for Arabic", df_val_ar["answerable"], pd.Series([majority_class_baseline_predict(df_train_ar)] * df_val_ar.shape[0]))
mcb_ko_metrics = evaluate_answerability("majority class baseline for Korean", df_val_ko["answerable"], pd.Series([majority_class_baseline_predict(df_train_ko)] * df_val_ko.shape[0]))
mcb_te_metrics = evaluate_answerability("majority class baseline for Telegu", df_val_te["answerable"], pd.Series([majority_class_baseline_predict(df_train_te)] * df_val_te.shape[0]))
mcb_mlangs_metrics = evaluate_answerability("majority class baseline for Ar+Ko+Te", df_val_mlangs["answerable"], pd.Series([majority_class_baseline_predict(df_train_mlangs)] * df_val_mlangs.shape[0]))

mcb_metrics = [mcb_ar_metrics,mcb_ko_metrics,mcb_te_metrics,mcb_mlangs_metrics]

pd.DataFrame(mcb_metrics)

,model,accuracy,macro_avg_f1,precision_answerable,recall_answerable,f1_answerable,precision_unanswerable,recall_unanswerable,f1_unanswerable
0,majority class baseline for Arabic,0.874699,0.466581,0.874699,1.0,0.933162,0.0,0.0,0.0
1,majority class baseline for Korean,0.946629,0.486291,0.946629,1.0,0.972583,0.0,0.0,0.0
2,majority class baseline for Telegu,0.757812,0.431111,0.757812,1.0,0.862222,0.0,0.0,0.0
3,majority class baseline for Ar+Ko+Te,0.858009,0.461789,0.858009,1.0,0.923579,0.0,0.0,0.0

In [ ]:
# deterministic rule-based classifier

def overlap_rule(question_, context, threshold = 0.20):
  overlap = set(question_) & set(context)
  return len(overlap)/len(set(context)) >= threshold

def number_overlap_rule(question, context):
  question_nums = [int(n) for n in re.findall(r'\d+', question)]
  context_nums = [int(n) for n in re.findall(r'\d+', context)]

  if len(question_nums) == 0:
    return True

  for qn in question_nums:
    for cn in context_nums:
      if abs(qn-cn) <= qn*0.1:
        return True
  return False

question_words = {
    AR: {"من": "who", "متى": "when", "أين": "where", "كم عدد": "how many"},
    KO: {"누구": "who", "언제": "when", "어디": "where", "얼마나": "how many"},
    TE: {"ఎవరు": "who", "ఎప్పుడు": "when", "ఎక్కడ": "where", "ఎన్ని": "how many"}
}

months = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"]
week_days = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]

# see presence of each of these question words in the question train dataset
def check_context(qword,context):
  context_nums = [int(n) for n in re.findall(r'\d+', context)]
  if qword == "when":
    if len(context_nums) > 0 and any(w in context for w in months+week_days):
      return True
    else:
      return False
  elif qword == "how many":
    if len(context_nums) > 0:
      return True
    else:
      return False
  return True

def qw_rule(lang, question, context):
  count_qws = 0
  for qword in question_words[lang].keys():
    if qword in question:
      count_qws += 1
      if not check_context(qword,context):
        return False
  if count_qws > 1:
    return False
  return True

def rule_classifier_ar(question,question_translated,context):
  cnt = (
      (question.count("؟") != 1)
      + overlap_rule(question_translated,context)
      + number_overlap_rule(question,context)
      + qw_rule(AR,question,context)
  )
  if cnt >= 3:
    return 1
  return 0

def rule_classifier_ko(question,question_translated,context):
  cnt = (
      (question.count("?") != 1)
      + overlap_rule(question_translated,context)
      + number_overlap_rule(question,context)
      + qw_rule(KO,question,context)
  )
  if cnt >= 3:
    return 1
  return 0

def rule_classifier_te(question,question_translated,context):
  cnt = (
      (question.count("?") != 1)
      + overlap_rule(question_translated,context)
      + number_overlap_rule(question,context)
      + qw_rule(TE,question,context)
  )
  if cnt >= 3:
    return 1
  return 0

def rule_classifier_overall(question,question_translated,context):
  cnt = (
      (question.count("?") + question.count("؟") != 1)
      + overlap_rule(question_translated,context)
      + number_overlap_rule(question,context)
      + qw_rule(AR,question,context) + qw_rule(KO,question,context) + qw_rule(TE,question,context) # at least two will evaluate to 1
  )
  if cnt >= 5:
    return 1
  return 0

rbc_ar_metrics = evaluate_answerability("rule based classifier for Arabic", df_val_ar["answerable"], df_val_ar.apply(lambda row: rule_classifier_ar(row['question'], row['question_translated'], row['context']), axis=1))
rbc_ko_metrics = evaluate_answerability("rule based classifier for Korean", df_val_ko["answerable"], df_val_ko.apply(lambda row: rule_classifier_ko(row['question'], row['question_translated'], row['context']), axis=1))
rbc_te_metrics = evaluate_answerability("rule based classifier for Telegu", df_val_te["answerable"], df_val_te.apply(lambda row: rule_classifier_te(row['question'],row['question_translated'], row['context']), axis=1))
rbc_mlangs_metrics = evaluate_answerability("rule based classifier for Ar+Ko+Te", df_val_mlangs["answerable"], df_val_mlangs.apply(lambda row: rule_classifier_overall(row['question'], row['question_translated'], row['context']), axis=1))

rbc_metrics = [rbc_ar_metrics,rbc_ko_metrics,rbc_te_metrics,rbc_mlangs_metrics]

pd.DataFrame(rbc_metrics)

,model,accuracy,macro_avg_f1,precision_answerable,recall_answerable,f1_answerable,precision_unanswerable,recall_unanswerable,f1_unanswerable
0,rule based classifier for Arabic,0.853012,0.476108,0.873762,0.972452,0.920469,0.090909,0.019231,0.031746
1,rule based classifier for Korean,0.873596,0.466267,0.942424,0.922849,0.932534,0.000000,0.000000,0.000000
2,rule based classifier for Telegu,0.736979,0.424288,0.752660,0.972509,0.848576,0.000000,0.000000,0.000000
3,rule based classifier for Ar+Ko+Te,0.820779,0.455522,0.853153,0.955600,0.901475,0.022222,0.006098,0.009569

# Week 37

In [ ]:
df_train = df_train[
    df_train["lang"].isin(["ar", "ko", "te"])
]

df_val = df_val[
    df_val["lang"].isin(["ar", "ko", "te"])
]

## BIO Labels

In [ ]:
# lang_tokenizer = {AR: nlp_ar_spacy, TE: nlp_te_spacy, KO: nlp_ko_spacy, EN: nlp_en_spacy}
# L = {AR: "Arabic", KO: "Korean", TE: "Telegu", EN: "English"}

In [ ]:
def is_answer_valid(answer, answer_start, context):
  return not (not answer or answer_start is None or answer_start < 0)

def bio_labeller(context, answer, answer_start):
    document = lang_tokenizer[EN](context)

    tokens = [token.text for token in document]
    offsets = [
        (token.idx, token.idx + len(token.text))
        for token in document
    ]

    labels = ["O"] * len(tokens)

    if (
        not isinstance(answer, str)
        or answer == ""
        or answer_start is None
        or pd.isna(answer_start)
        or int(answer_start) < 0
    ):
        return tokens, labels

    answer_start = int(answer_start)
    answer_end = answer_start + len(answer)

    covered_token_indices = [
        index
        for index, (token_start, token_end) in enumerate(offsets)
        if token_start < answer_end and token_end > answer_start
    ]

    labels[covered_token_indices[0]] = "B"

    for index in covered_token_indices[1:]:
        labels[index] = "I"

    return tokens, labels

def bio_labeller_row(row):
  context = row["context"]
  answer = row["answer"]
  answer_start = row["answer_start"]

  tokens, labels = bio_labeller(context, answer, answer_start)

  return labels

def tokenizer_row(row):
  context = row["context"]
  answer = row["answer"]
  answer_start = row["answer_start"]

  tokens, labels = bio_labeller(context, answer, answer_start)

  return tokens

In [ ]:
df_train["sequence_labels"] = df_train.apply(
    bio_labeller_row,
    axis=1,
)

df_train["context_tokens"] = df_train.apply(
    tokenizer_row,
    axis=1,
)

df_val["sequence_labels"] = df_val.apply(
    bio_labeller_row,
    axis=1,
)

df_val["context_tokens"] = df_val.apply(
    tokenizer_row,
    axis=1,
)

df_train.head()

/tmp/ipykernel_532/3836319473.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_train["sequence_labels"] = df_train.apply(
/tmp/ipykernel_532/3836319473.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_train["context_tokens"] = df_train.apply(
/tmp/ipykernel_532/3836319473.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_val["sequence_labels"] = df_val.apply(
/tmp/ipykernel_532/3836319473.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_val["context_tokens"] = df_val.apply(

,question,context,lang,answerable,answer_start,answer,answer_inlang,question_translated,training_data,sequence_labels,context_tokens
4792,30년 전쟁의 승자는 누구인가?,The conflict between France and Spain continue...,ko,True,21,France,NaN,Who is the winner of the Thirty Years' War?,"{'input_ids': [tensor(101), tensor(10244), ten...","[O, O, O, B, O, O, O, O, O, O, O, O, O, O, O, ...","[The, conflict, between, France, and, Spain, c..."
4793,엑스선은 누가 발견하였는가?,"X-rays make up X-radiation, a form of electrom...",ko,True,503,Wilhelm Röntgen,NaN,Who discovered the X-ray?,"{'input_ids': [tensor(101), tensor(9560), tens...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ...","[X, -, rays, make, up, X, -, radiation, ,, a, ..."
4794,아테네에서 언제 가장 최근의 올림픽이 올렸나요?,"In 2022, Beijing will become the first-ever ci...",ko,True,188,2004,NaN,When was the last time the Olympics were held ...,"{'input_ids': [tensor(101), tensor(9519), tens...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ...","[In, 2022, ,, Beijing, will, become, the, firs..."
4795,세상에서 가장 오래된 방송사는 무엇인가?,The British Broadcasting Corporation (BBC) is ...,ko,True,4,British Broadcasting Corporation (BBC),NaN,What's the oldest broadcaster in the world?,"{'input_ids': [tensor(101), tensor(9435), tens...","[O, B, I, I, I, I, I, O, O, O, O, O, O, O, O, ...","[The, British, Broadcasting, Corporation, (, B..."
4796,팔레스타인 수도는 어딘가요?,"Palestine ( '), officially the State of Palest...",ko,True,205,Jerusalem,NaN,Where is the Palestinian capital?,"{'input_ids': [tensor(101), tensor(9904), tens...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ...","[Palestine, (, ', ), ,, officially, the, State..."

## Automatic checks

In [ ]:
def answers_at_0():
  return df_train[
      df_train["answer_start"] == 0
  ]

def multi_token_answers():
  return df_train[
    df_train["sequence_labels"].apply(
        lambda labels: sum(
            label in {"B", "I"} for label in labels
        ) > 1
    )
]

import unicodedata

def is_punctuation(character):
  return (
      character is not None
      and unicodedata.category(character).startswith("P")
  )

def has_adjacent_punctuation(row):
  context = row["context"]
  answer = row["answer"]
  answer_start = row["answer_start"]

  answer_start = int(answer_start)

  if answer_start < 0:
      return False

  answer_end = answer_start + len(answer)

  character_before = (
      context[answer_start - 1]
      if answer_start > 0
      else None
  )

  character_after = (
      context[answer_end]
      if answer_end < len(context)
      else None
  )

  return (
      is_punctuation(character_before)
      or is_punctuation(character_after)
  )

def answers_adjacent_to_punctuation():
  return df_train[
      df_train.apply(
          has_adjacent_punctuation,
          axis=1,
      )
  ]

def unanswerable_answers():
  return df_train[
      df_train["answerable"] == False
  ]

In [ ]:
def test_answer_at_0():
  rows = answers_at_0().sample(5)

  for row in rows.itertuples():
    sequence_labels = row.sequence_labels

    assert sequence_labels[0] == "B"

  print("All tests on answers at 0 passed.")

def test_multi_token_answers():
  rows = multi_token_answers().sample(5)

  for row in rows.itertuples():
    sequence_labels = row.sequence_labels

    assert sequence_labels.count("B") + sequence_labels.count("I") > 1

  print("All tests on multi-token answers passed.")

def test_answers_adjacent_to_punctuation():
  rows = answers_adjacent_to_punctuation().sample(5)

  for row in rows.itertuples():
    answer = row.answer
    answer_start = row.answer_start
    answer_end = answer_start + len(answer)
    context = row.context

    char_before = None
    char_after = None
    if answer_start > 0:
      char_before = context[answer_start - 1]

    if answer_end < len(context):
      char_after = context[answer_end]

    assert (
        is_punctuation(char_before)
        or is_punctuation(char_after)
    )
  print("All tests on answers adjacent to punctuations passed.")

def test_unanswerable_answers():
  rows = unanswerable_answers().sample(5)

  for row in rows.itertuples():
    answer_start = row.answer_start
    sequence_labels = row.sequence_labels

    assert answer_start == -1
    assert sequence_labels.count("B") + sequence_labels.count("I") == 0

  print("All tests on unanswerable answers passed.")

test_answer_at_0()
test_multi_token_answers()
test_answers_adjacent_to_punctuation()
test_unanswerable_answers()

All tests on answers at 0 passed.
All tests on multi-token answers passed.
All tests on answers adjacent to punctuations passed.
All tests on unanswerable answers passed.

## Question-conditioned sequence labeller

In [ ]:
LABELS = ["O", "B", "I"]
LABEL_TO_ID = {"O": 0, "B": 1, "I": 2}

QUESTION_WORDS = {
    "who",
    "whom",
    "whose",
    "what",
    "which",
    "when",
    "where",
    "why",
    "how",
}

def spacy_tokenize(text, lang):
    document = lang_tokenizer[lang].make_doc(text)

    return [
        token.text
        for token in document
        if not token.is_space
    ]
def normalize_token(token):
    if hasattr(token, "text"):
        token = token.text

    return token.strip().casefold()

def token_features(question_tokens, context_tokens, index):
    token = context_tokens[index]
    normalized_token = normalize_token(token)

    question_set = {
        normalize_token(question_token)
        for question_token in question_tokens
        if normalize_token(question_token)
    }

    question_words = question_set & QUESTION_WORDS

    features = {
        "bias": 1.0,
        "token.lower": normalized_token,
        "token.prefix2": normalized_token[:2],
        "token.suffix2": normalized_token[-2:],
        "token.suffix3": normalized_token[-3:],
        "token.isdigit": normalized_token.isdigit(),
        "token.istitle": token.istitle(),
        "token.isupper": token.isupper(),
        "token_in_question": normalized_token in question_set,
        "relative_position": (
            index / max(len(context_tokens) - 1, 1)
        ),
    }

    if index == 0:
        features["BOS"] = True
    else:
        previous = normalize_token(context_tokens[index - 1])

        features["previous.lower"] = previous
        features["previous_in_question"] = (
            previous in question_set
        )

    if index == len(context_tokens) - 1:
        features["EOS"] = True
    else:
        following = normalize_token(context_tokens[index + 1])

        features["next.lower"] = following
        features["next_in_question"] = (
            following in question_set
        )

    for question_word in question_words:
        features[f"question_word={question_word}"] = 1.0

    return features

def featurize_split(data):
    features, labels, lengths = [], [], []

    for row in data.itertuples():
      question = row.question
      context = row.context
      sequence_labels = row.sequence_labels
      tokens = row.context_tokens

      question_doc = lang_tokenizer[EN](translate(question, row.lang, EN))
      question_tokens = [token.text for token in question_doc]
      lengths.append(len(tokens))
      features.extend(token_features(question_tokens, tokens, index) for index in range(len(tokens)))
      labels.extend(sequence_labels)

    return features, labels, lengths

def split_by_lengths(values, lengths):
    sequences = []
    offset = 0
    for length in lengths:
        sequences.append(list(values[offset:offset + length]))
        offset += length
    assert offset == len(values)
    return sequences

In [ ]:
from sklearn.feature_extraction import DictVectorizer
from sklearn.linear_model import SGDClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, f1_score
import joblib

if not os.path.exists("./models"):
  vectorizer = DictVectorizer(sparse=True)

  train_features, train_labels, train_lengths = featurize_split(df_train)

  X_train = vectorizer.fit_transform(train_features)

  token_classifier = SGDClassifier(
      loss="log_loss",
      alpha=1e-5,
      class_weight="balanced",
      max_iter=30,
      random_state=42,
  )
  token_classifier.fit(X_train, train_labels)
else:
  saved_model = joblib.load(
      "models/week37_sequence_labeller.joblib"
  )

  vectorizer = saved_model["vectorizer"]
  token_classifier = saved_model["classifier"]

In [ ]:
validation_features, validation_labels, validation_lengths = featurize_split(df_val)

X_validation = vectorizer.transform(validation_features)

independent_flat = token_classifier.predict(X_validation)
independent_predictions = split_by_lengths(
    independent_flat, validation_lengths
)

In [ ]:
def bio_spans(labels):
    spans = set()
    start = None

    for index, label in enumerate(list(labels) + ["O"]):
      if label == "B":
        if start is not None:
            spans.add((start, index))
        start = index

      elif label == "I":
        if start is None:
            start = index

      elif label == "O" and start is not None:
        spans.add((start, index))
        start = None

    return spans


def span_scores(gold_sequences, predicted_sequences):
    predicted_count = gold_count = matches = 0
    for gold, predicted in zip(gold_sequences, predicted_sequences):
        gold_spans = bio_spans(gold)
        predicted_spans = bio_spans(predicted)
        gold_count += len(gold_spans)
        predicted_count += len(predicted_spans)
        matches += len(gold_spans & predicted_spans)

    precision = matches / predicted_count if predicted_count else 0.0
    recall = matches / gold_count if gold_count else 0.0
    f1 = 2 * precision * recall / (precision + recall) if precision + recall else 0.0
    return precision, recall, f1


def evaluate_sequences(name, gold_sequences, predicted_sequences):
    gold_flat = np.concatenate(gold_sequences)
    predicted_flat = np.concatenate(predicted_sequences)

    # B and I are both positive; O is negative.
    gold_answer_tokens = np.isin(gold_flat, ["B", "I"])
    predicted_answer_tokens = np.isin(
        predicted_flat, ["B", "I"]
    )

    exact_matches = [
        bio_spans(gold) == bio_spans(predicted)
        for gold, predicted in zip(
            gold_sequences,
            predicted_sequences,
        )
    ]

    unanswerable = [
        len(bio_spans(gold)) == 0
        for gold in gold_sequences
    ]

    return {
        "model": name,
        "token_accuracy": accuracy_score(
            gold_flat,
            predicted_flat,
        ),
        "answer_token_f1": f1_score(
            gold_answer_tokens,
            predicted_answer_tokens,
            zero_division=0,
        ),
        "exact_span_match": np.mean(exact_matches),
        "unanswerable_exact_match": np.mean([
            exact
            for exact, is_unanswerable in zip(
                exact_matches,
                unanswerable,
            )
            if is_unanswerable
        ]),
    }

In [ ]:
validation_gold = split_by_lengths(
    validation_labels, validation_lengths
)

always_o_predictions = [
    ["O"] * length
    for length in validation_lengths
]

print(evaluate_sequences(
    "Always O",
    validation_gold,
    always_o_predictions,
))

print(evaluate_sequences(
    "Question-conditioned classifier",
    validation_gold,
    independent_predictions,
))

{'model': 'Always O', 'token_accuracy': 0.9754622281326413, 'answer_token_f1': 0.0, 'exact_span_match': np.float64(0.141991341991342), 'unanswerable_exact_match': np.float64(1.0)}
{'model': 'Question-conditioned classifier', 'token_accuracy': 0.9454978336407704, 'answer_token_f1': 0.18915701763878368, 'exact_span_match': np.float64(0.04242424242424243), 'unanswerable_exact_match': np.float64(0.10975609756097561)}

In [ ]:
confusion = confusion_matrix(
    validation_labels,
    independent_flat,
    labels=LABELS,
)

pd.DataFrame(confusion, index=LABELS, columns=LABELS)

        O     B     I
O  131499  3036  1899
B     523   429    39
I    2035    91   315

# Week 38

## Common setup

### Training and validation questions

In [ ]:
# df_train.drop_duplicates(subset=["question"])
df_train_ko = df_train[df_train["lang"] == "ko"].copy()

# df_val.drop_duplicates(subset=["question"])
df_val_ko = df_val[df_val["lang"] == "ko"].copy()

ko_train_questions = df_train_ko["question"].tolist()

ko_val_questions = df_val_ko["question"].tolist()

### Tokenization

In [ ]:
# nlp_ko_spacy = spacy.load("ko_core_news_sm")

def tokenize(question):
  return model_tokenizer.tokenize(question)

tokenize(ko_train_questions[1])

['▁', '엑스', '선', '은', '▁누가', '▁발견', '하였', '는', '가', '?']

### Vocabulary
Unknown strategy:
1. tokens occurring at least twice remain in the vocabulary;
2. tokens occurring only once become \<UNK>;
3. unseen validation tokens also become \<UNK>.

In [ ]:
BOS = "<BOS>"
EOS = "<EOS>"
UNK = "<UNK>"

df_train_ko["question_tokenized"] = df_train_ko["question"].apply(tokenize)
df_val_ko["question_tokenized"] = df_val_ko["question"].apply(tokenize)

train_questions_tokenized = df_train_ko["question_tokenized"].tolist()

val_questions_tokenized = df_val_ko["question_tokenized"].tolist()

token_counts = Counter(
    token
    for question in train_questions_tokenized
    for token in question
)

vocabulary = {
    token
    for token, count in token_counts.items()
    if count >= 2
}

prediction_vocabulary = set(vocabulary) | {
    UNK,
    EOS,
}

In [ ]:
def replace_unknown_tokens(tokens):
    return [
        token if token in vocabulary else "<UNK>"
        for token in tokens
    ]

train_sequences = [
    replace_unknown_tokens(tokens)
    for tokens in train_questions_tokenized
]

# ADDED
val_sequences = [
    replace_unknown_tokens(tokens)
    for tokens in val_questions_tokenized
]

df_train_ko["question_tokenized"] = df_train_ko["question_tokenized"].apply(replace_unknown_tokens)
df_val_ko["question_tokenized"] = df_val_ko["question_tokenized"].apply(replace_unknown_tokens)

df_train_ko.head()

,question,context,lang,answerable,answer_start,answer,answer_inlang,question_tokenized
4792,30년 전쟁의 승자는 누구인가?,The conflict between France and Spain continue...,ko,True,21,France,None,"[▁30, 년, ▁전쟁, 의, ▁승, 자는, ▁누구, 인가, ?]"
4793,엑스선은 누가 발견하였는가?,"X-rays make up X-radiation, a form of electrom...",ko,True,503,Wilhelm Röntgen,None,"[▁, 엑스, 선, 은, ▁누가, ▁발견, 하였, 는, 가, ?]"
4794,아테네에서 언제 가장 최근의 올림픽이 올렸나요?,"In 2022, Beijing will become the first-ever ci...",ko,True,188,2004,None,"[▁아, 테, 네, 에서, ▁언제, ▁가장, ▁최근, 의, ▁, 올림픽, 이, ▁올..."
4795,세상에서 가장 오래된 방송사는 무엇인가?,The British Broadcasting Corporation (BBC) is ...,ko,True,4,British Broadcasting Corporation (BBC),None,"[▁세상, 에서, ▁가장, ▁오래, 된, ▁방송, 사는, ▁무엇인가, ?]"
4796,팔레스타인 수도는 어딘가요?,"Palestine ( '), officially the State of Palest...",ko,True,205,Jerusalem,None,"[▁팔, 레, 스타, 인, ▁수도, 는, ▁어, 딘, 가요, ?]"

In [ ]:
print("Number of tokens: ", len(token_counts.keys()))
print("Number of tokens with just one occurrence: ",len([cnt for _,cnt in token_counts.items() if cnt < 2]))
print("Size of prediction vocabulary:", len(prediction_vocabulary))

Number of tokens:  2223
Number of tokens with just one occurrence:  697
Size of prediction vocabulary: 1528


### NGram model

In [ ]:
class NGram:
    def __init__(self, _N, _ALPHA=0.1):
        self.N = _N
        self.ALPHA = _ALPHA
        self.gram_counts = Counter()
        self.context_counts = Counter()

    def train(self, train_sequences):
        for tokens in train_sequences:
            padded_tokens = [BOS]*(self.N-1) + [*tokens, EOS]

            for index in range(self.N-1, len(padded_tokens)):
                context = tuple(
                    padded_tokens[index - (self.N-1) + i]
                    for i in range(self.N-1)
                )

                current_token = padded_tokens[index]

                n_gram = tuple(
                    context[i] if i<self.N-1 else current_token for i in range(self.N)
                )

                self.gram_counts[n_gram] += 1
                self.context_counts[context] += 1

    def model_probability(self, context, token, smoothing="add-k"):
        if len(context) != self.N-1:
          return None

        context = tuple(context)
        ngram = context + (token,)

        if smoothing == "laplace":
            return (self.gram_counts[ngram] + 1) / (self.context_counts[context] + len(prediction_vocabulary))
        elif smoothing == "add-k":
            return (self.gram_counts[ngram] + self.ALPHA) / (self.context_counts[context] + self.ALPHA * len(prediction_vocabulary))
        else:
            raise Exception("Unknown smoothing method")

    def question_log_probability(self, question, smoothing="add-k"):
        tokens = tokenize(question)
        tokens = replace_unknown_tokens(tokens)

        padded =  [BOS]*(self.N-1) + [*tokens, EOS]

        log_probability = 0.0
        for i in range(self.N-1, len(padded)):
            probability = self.model_probability(
                [padded[i - (self.N-1) + j] for j in range(self.N-1)],
                padded[i],
                smoothing
            )
            log_probability += math.log(probability)

        # Includes EOS, but not the three BOS tokens
        predicted_token_count = len(tokens) + 1
        return log_probability, predicted_token_count

    def question_perplexity(self, question, smoothing="add-k"):
        log_probability, token_count = self.question_log_probability(
            question,
            smoothing
        )
        return math.exp(-log_probability / token_count)

    def sample(self,max_length=50, smoothing="add-k"):
      context = [BOS]*(self.N-1)
      sentence = []
      random.seed(42)
      sample_vocabulary = [token for token in prediction_vocabulary if token != "<UNK>"]
      for _ in range(max_length):
        probs = []

        for token in sample_vocabulary:
            if token == "<UNK>":
              continue
            p = self.model_probability(context, token, smoothing)
            probs.append(p)

        next_token = random.choices(
            sample_vocabulary,
            weights=probs,
            k=1
        )[0]

        if next_token == EOS:
            break

        sentence.append(next_token)

        if self.N > 1:
          context = context[1:] + [next_token]

      return " ".join(sentence)

    def highest_lowest_perplexity(self, data, model, smoothing="add-k"):
      question_scores = [
          {
              "model": model,
              "question": row.question,
              "question_tokenized": row.question_tokenized,
              "perplexity": self.question_perplexity(row.question, smoothing),
          }
          for row in data.itertuples()
      ]

      question_scores = pd.DataFrame(question_scores)

      lowest = question_scores.nsmallest(5, "perplexity").copy()
      highest = question_scores.nlargest(5, "perplexity").copy()

      for table in (lowest, highest):
          table["translation_en"] = table["question"].apply(
              lambda question: translate(question, KO, EN)
          )

      return (
          lowest, highest, question_scores["perplexity"].mean(),
          question_scores["perplexity"].min(), question_scores["perplexity"].max(),
          question_scores["perplexity"].median()
      )

## Unigram

In [ ]:
unigram_model = NGram(1)
unigram_model.train(train_sequences)

In [ ]:
probability = unigram_model.model_probability(
    [],
    "대한민국의",
    "laplace"
)

print(probability)

2.999760019198464e-05

In [ ]:
unigram_lowest, unigram_highest, unigram_mean_perplexity, unigram_min_perplexity, unigram_max_perplexity, unigram_median_perplexity = unigram_model.highest_lowest_perplexity(df_val_ko, "unigram")
unigram_metrics = {
    "model": "unigram",
    "average_perplexity": unigram_mean_perplexity,
    "median_perplexity": unigram_median_perplexity,
    "min_perplexity": unigram_min_perplexity,
    "max_perplexity": unigram_max_perplexity
}

## Bigram

In [ ]:
bigram_model = NGram(2)
bigram_model.train(train_sequences)

In [ ]:
bigram_lowest, bigram_highest, bigram_mean_perplexity, bigram_min_perplexity, bigram_max_perplexity, bigram_median_perplexity = bigram_model.highest_lowest_perplexity(df_val_ko, "bigram")
bigram_metrics = {
    "model": "bigram",
    "average_perplexity": bigram_mean_perplexity,
    "median_perplexity": bigram_median_perplexity,
    "min_perplexity": bigram_min_perplexity,
    "max_perplexity": bigram_max_perplexity
}

In [ ]:
probability = bigram_model.model_probability(
    [BOS],
    "대한민국의",
)

print(probability)

3.883796799751437e-05

In [ ]:
sample = bigram_model.sample()
print(sample)
print(translate(sample,KO,EN))

▁지 어 났 나 브리 ▁고려 멕 ▁만든 ▁삼 ▁제일 > ▁2016 직 ▁광 시는 ▁대전 ▁외 엘 ▁공격 잉 ▁돌 기로 농 ▁위치 ▁토 ▁역할 하우스 섭 ▁대통령이 이라고 ▁하나 료 됐 ▁스마트폰 법을 ▁최근 테이션 벤처 ▁참 택 류 관 DF ▁팔 중 ▁지구 ▁티 스가 ▁영 심
The first time I saw the newly formed company, the newly formed company, the newly formed company, the newly formed company, the newly formed company, the newly formed company, the newly formed company, the newly formed company, the newly formed company, the newly formed company, the newly formed company, the newly formed company, the newly formed company, the newly formed company, the newly formed company, the newly formed company, the newly formed company, the newly formed company, the newly formed company, the newly formed company, the

## Four-gram

In [ ]:
fourgram_model = NGram(4)
fourgram_model.train(train_sequences)

In [ ]:
fourgram_add_k_lowest, fourgram_add_k_highest, fourgram_add_k_mean_perplexity, fourgram_add_k_min_perplexity, fourgram_add_k_max_perplexity, fourgram_add_k_median_perplexity = fourgram_model.highest_lowest_perplexity(df_val_ko, "4-gram add-k", "add-k")
fourgram_laplace_lowest, fourgram_laplace_highest, fourgram_laplace_mean_perplexity, fourgram_laplace_min_perplexity, fourgram_laplace_max_perplexity, fourgram_laplace_median_perplexity = fourgram_model.highest_lowest_perplexity(df_val_ko, "4-gram laplace", "laplace")
fourgram_add_k_metrics = {
    "model": "fourgram add-k",
    "average_perplexity": fourgram_add_k_mean_perplexity,
    "median_perplexity": fourgram_add_k_median_perplexity,
    "min_perplexity": fourgram_add_k_min_perplexity,
    "max_perplexity": fourgram_add_k_max_perplexity
}
fourgram_laplace_metrics = {
    "model": "fourgram laplace",
    "average_perplexity": fourgram_laplace_mean_perplexity,
    "median_perplexity": fourgram_laplace_median_perplexity,
    "min_perplexity": fourgram_laplace_min_perplexity,
    "max_perplexity": fourgram_laplace_max_perplexity
}

In [ ]:
probability = fourgram_model.model_probability(
    [BOS, BOS, BOS],
    "대한민국의",
)

print(probability)

3.883796799751437e-05

In [ ]:
sample = fourgram_model.sample()
print(sample)
print(translate(sample,KO,EN))

▁지 ▁가 트리 분 - ▁태양 수의 률 되었 ▁형 ▁외 ▁2016 ▁합 ▁브루 낙 측 기업 ▁사진 ▁공격 하기 ▁DNA ▁초 ▁8 ▁학교 ▁곳 ▁인류 ▁판 ▁등장 마리 ▁표 ▁비 콜 혈 ▁스마트폰 ▁다이 ▁애 ▁종료 년도 징 ▁아마 망 갔 ▁지구 핵 텍 가는 ▁의 ▁통 나라 ▁의미
The number of solar cells has been regulated by the geographically excluded 2016 aggregate blue chip corporate photos attack the early eighth school where the human plate appeared mary list v call blood smartphone diary end of year also the year the chin probably went down the earth nuclear tech means the country of the go

## Six-gram

In [ ]:
sixgram_model = NGram(6)
sixgram_model.train(train_sequences)

In [ ]:
sixgram_lowest, sixgram_highest, sixgram_mean_perplexity, sixgram_min_perplexity, sixgram_max_perplexity, sixgram_median_perplexity = sixgram_model.highest_lowest_perplexity(df_val_ko, "6-gram")
sixgram_metrics = {
    "model": "sixgram",
    "average_perplexity": sixgram_mean_perplexity,
    "median_perplexity": sixgram_median_perplexity,
    "min_perplexity": sixgram_min_perplexity,
    "max_perplexity": sixgram_max_perplexity
}

In [ ]:
probability = sixgram_model.model_probability(
    [BOS]*5,
    "대한민국의",
)

print(probability)

3.883796799751437e-05

In [ ]:
sample = sixgram_model.sample()
print(sample)
print(translate(sample,KO,EN))

▁지 ▁가 트리 분 - ▁태양 수의 률 되었 ▁형 ▁외 ▁2016 ▁합 ▁브루 낙 측 기업 ▁사진 ▁공격 하기 ▁DNA ▁초 ▁8 ▁학교 ▁곳 ▁인류 ▁판 ▁등장 마리 ▁표 ▁비 콜 혈 ▁스마트폰 ▁다이 ▁애 ▁종료 년도 징 ▁아마 망 갔 ▁지구 핵 텍 가는 ▁의 ▁통 나라 ▁의미
The number of solar cells has been regulated by the geographically excluded 2016 aggregate blue chip corporate photos attack the early eighth school where the human plate appeared mary list v call blood smartphone diary end of year also the year the chin probably went down the earth nuclear tech means the country of the go

## N-gram Results

In [ ]:
combined_lowest = pd.concat(
    [unigram_lowest, bigram_lowest, fourgram_add_k_lowest, fourgram_laplace_lowest, sixgram_lowest],
    ignore_index=True
)

combined_highest = pd.concat(
    [unigram_highest, bigram_highest, fourgram_add_k_highest, fourgram_laplace_highest, sixgram_highest],
    ignore_index=True
)

In [ ]:
combined_lowest

,model,question,question_tokenized,perplexity,translation_en
0,unigram,최초의 광고 대행 업체는 무엇인가?,"[▁최초, 의, <UNK>, ▁, <UNK>, <UNK>, 는, ▁무엇인가, ?]",43.569209,What was the first advertising agency?
1,unigram,세상에서 가장 넓은 산은 무엇인가?,"[▁세상, 에서, ▁가장, <UNK>, ▁산, 은, ▁무엇인가, ?]",63.432125,What is the widest mountain in the world?
2,unigram,세상에서 가장 큰 대학교는 무엇인가?,"[▁세상, 에서, ▁가장, ▁큰, ▁, 대학교, 는, ▁무엇인가, ?]",67.809011,What is the largest university in the world?
3,unigram,KKK의 지도자는 누구인가?,"[<UNK>, <UNK>, 의, ▁지도, 자는, ▁누구, 인가, ?]",69.120848,Who is the leader of the KKK?
4,unigram,창원시에서 가장 높은 건물은 무엇인가?,"[▁, <UNK>, 시, 에서, ▁가장, ▁높은, ▁건물, 은, ▁무엇인가, ?]",78.489330,What's the tallest building in the city?
5,bigram,세상에서 가장 큰 대학교는 무엇인가?,"[▁세상, 에서, ▁가장, ▁큰, ▁, 대학교, 는, ▁무엇인가, ?]",5.939880,What is the largest university in the world?
6,bigram,KKK의 지도자는 누구인가?,"[<UNK>, <UNK>, 의, ▁지도, 자는, ▁누구, 인가, ?]",6.835423,Who is the leader of the KKK?
7,bigram,세상에서 가장 오래된 대학교는 무엇인가?,"[▁세상, 에서, ▁가장, ▁오래, 된, ▁, 대학교, 는, ▁무엇인가, ?]",6.891953,What is the oldest university in the world?
8,bigram,세상에서 가장 오래된 대학교는 무엇인가?,"[▁세상, 에서, ▁가장, ▁오래, 된, ▁, 대학교, 는, ▁무엇인가, ?]",6.891953,What is the oldest university in the world?
9,bigram,세상에서 가장 오래된 대학교는 무엇인가?,"[▁세상, 에서, ▁가장, ▁오래, 된, ▁, 대학교, 는, ▁무엇인가, ?]",6.891953,What is the oldest university in the world?
10,4-gram add-k,중국에서 가장 인구밀도가 높은 도시는 어디인가?,"[▁중국, 에서, ▁가장, ▁인구, 밀, 도가, ▁높은, ▁도시, 는, ▁어디, 인...",13.029646,What is the most densely populated city in China?
11,4-gram add-k,세상에서 가장 큰 대학교는 무엇인가?,"[▁세상, 에서, ▁가장, ▁큰, ▁, 대학교, 는, ▁무엇인가, ?]",16.724450,What is the largest university in the world?
12,4-gram add-k,중국에서 가장 작은 도시는 어디인가?,"[▁중국, 에서, ▁가장, ▁작은, ▁도시, 는, ▁어디, 인가, ?]",22.905718,Where is the smallest city in China?
13,4-gram add-k,스웨덴에서 가장 인구밀도가 높은 도시는 어디인가?,"[▁스, 웨, 덴, 에서, ▁가장, ▁인구, 밀, 도가, ▁높은, ▁도시, 는, ▁...",26.682906,What is the most densely populated city in Swe...
14,4-gram add-k,인간의 몸에서 가장 큰 뼈는 무엇인가?,"[▁, 인간의, ▁몸, 에서, ▁가장, ▁큰, ▁, 뼈, 는, ▁무엇인가, ?]",28.068641,What is the largest bone in the human body?
15,4-gram laplace,세상에서 가장 큰 대학교는 무엇인가?,"[▁세상, 에서, ▁가장, ▁큰, ▁, 대학교, 는, ▁무엇인가, ?]",84.626409,What is the largest university in the world?
16,4-gram laplace,중국에서 가장 인구밀도가 높은 도시는 어디인가?,"[▁중국, 에서, ▁가장, ▁인구, 밀, 도가, ▁높은, ▁도시, 는, ▁어디, 인...",86.931851,What is the most densely populated city in China?
17,4-gram laplace,중국에서 가장 작은 도시는 어디인가?,"[▁중국, 에서, ▁가장, ▁작은, ▁도시, 는, ▁어디, 인가, ?]",114.835922,Where is the smallest city in China?
18,4-gram laplace,세상에서 가장 오래된 대학교는 무엇인가?,"[▁세상, 에서, ▁가장, ▁오래, 된, ▁, 대학교, 는, ▁무엇인가, ?]",126.881493,What is the oldest university in the world?
19,4-gram laplace,세상에서 가장 오래된 대학교는 무엇인가?,"[▁세상, 에서, ▁가장, ▁오래, 된, ▁, 대학교, 는, ▁무엇인가, ?]",126.881493,What is the oldest university in the world?
20,6-gram,중국에서 가장 인구밀도가 높은 도시는 어디인가?,"[▁중국, 에서, ▁가장, ▁인구, 밀, 도가, ▁높은, ▁도시, 는, ▁어디, 인...",25.681725,What is the most densely populated city in China?
21,6-gram,세상에서 가장 큰 대학교는 무엇인가?,"[▁세상, 에서, ▁가장, ▁큰, ▁, 대학교, 는, ▁무엇인가, ?]",36.083826,What is the largest university in the world?
22,6-gram,세상에서 가장 먼저 시작된 교통수단은 무엇인가?,"[▁세상, 에서, ▁가장, ▁먼저, ▁시작, 된, ▁, 교통, 수, 단, 은, ▁무...",41.343078,What was the first transportation system in th...
23,6-gram,인간의 몸에서 가장 큰 뼈는 무엇인가?,"[▁, 인간의, ▁몸, 에서, ▁가장, ▁큰, ▁, 뼈, 는, ▁무엇인가, ?]",44.878923,What is the largest bone in the human body?
24,6-gram,에피쿠로스는 언제 태어났나요?,"[▁에, 피, 쿠, 로, 스는, ▁언제, ▁태, 어, 났, 나요, ?]",53.710862,When was Epicurus born?

In [ ]:
combined_highest

,model,question,question_tokenized,perplexity,translation_en
0,unigram,더글러스 맥아더 배우자는 누군가요?,"[▁더, 글, 러, 스, ▁맥, 아, 더, ▁배우, 자는, ▁누군가, 요, ?]",928.479072,Who is Douglas MacArthur's wife?
1,unigram,인도네시아에서는 동성결혼이 합법적인가?,"[▁인도, 네, 시아, 에서는, ▁동, 성, 결, 혼, 이, ▁합, 법, 적인, 가...",882.507545,Is same-sex marriage legal in Indonesia?
2,unigram,인도네시아에서는 동성결혼이 합법적인가?,"[▁인도, 네, 시아, 에서는, ▁동, 성, 결, 혼, 이, ▁합, 법, 적인, 가...",882.507545,Is same-sex marriage legal in Indonesia?
3,unigram,말레이시아에서는 핵무기가 합법적인가?,"[▁말, 레이, 시아, 에서는, ▁, 핵, 무, 기가, ▁합, 법, 적인, 가, ?]",795.780166,Is nuclear weapons legal in Malaysia?
4,unigram,신화에는 그리스 신들이 몇 명이나 있을까?,"[▁신, 화, 에는, ▁그리, 스, ▁신, 들이, ▁몇, ▁명, 이나, ▁있을까, ?]",650.994599,How many Greek gods do myths have?
5,bigram,"임시정부는 종전의 정부가 무너진 후, 무정부 상태를 해소하기 위해 임시로 구성된 정...","[▁임, 시, 정부, 는, ▁종, 전, 의, <UNK>, ▁무, 너, 진, ▁후, ...",390.112906,Does the interim government say that it is a t...
6,bigram,불고기는 소의 어느부위를 사용하는가?,"[▁불, 고, 기는, ▁소, 의, ▁어느, 부, 위를, ▁사용하는, 가, ?]",384.058199,What part of the cow does the fisherman use?
7,bigram,더글러스 맥아더 배우자는 누군가요?,"[▁더, 글, 러, 스, ▁맥, 아, 더, ▁배우, 자는, ▁누군가, 요, ?]",330.763269,Who is Douglas MacArthur's wife?
8,bigram,클라미디아 발병원인은 무엇인가?,"[▁클, 라, 미, 디아, ▁발, <UNK>, 인은, ▁무엇인가, ?]",305.688873,What is the Chlamydia launcher?
9,bigram,제1대 휘트워스 준남작 조지프 휘트워스 경의 소속은 어디인가요?,"[▁제, 1, 대, ▁, 휘, 트, 워, 스, <UNK>, 남, 작, ▁조, 지, ...",293.670602,"Where is the first Whitworth deputy earl, Sir ..."
10,4-gram add-k,불고기는 소의 어느부위를 사용하는가?,"[▁불, 고, 기는, ▁소, 의, ▁어느, 부, 위를, ▁사용하는, 가, ?]",1933.488974,What part of the cow does the fisherman use?
11,4-gram add-k,육파철학의 이름들은 무엇인가?,"[▁육, 파, 철, 학, 의, ▁이름, 들은, ▁무엇인가, ?]",1595.619733,What are the names of the philosophy of the fl...
12,4-gram add-k,클라미디아 발병원인은 무엇인가?,"[▁클, 라, 미, 디아, ▁발, <UNK>, 인은, ▁무엇인가, ?]",1595.619733,What is the Chlamydia launcher?
13,4-gram add-k,신화에는 그리스 신들이 몇 명이나 있을까?,"[▁신, 화, 에는, ▁그리, 스, ▁신, 들이, ▁몇, ▁명, 이나, ▁있을까, ?]",1389.530975,How many Greek gods do myths have?
14,4-gram add-k,신화에는 그리스 신들이 몇 명이나 있을까?,"[▁신, 화, 에는, ▁그리, 스, ▁신, 들이, ▁몇, ▁명, 이나, ▁있을까, ?]",1389.530975,How many Greek gods do myths have?
15,4-gram laplace,불고기는 소의 어느부위를 사용하는가?,"[▁불, 고, 기는, ▁소, 의, ▁어느, 부, 위를, ▁사용하는, 가, ?]",1653.850184,What part of the cow does the fisherman use?
16,4-gram laplace,클라미디아 발병원인은 무엇인가?,"[▁클, 라, 미, 디아, ▁발, <UNK>, 인은, ▁무엇인가, ?]",1567.819789,What is the Chlamydia launcher?
17,4-gram laplace,육파철학의 이름들은 무엇인가?,"[▁육, 파, 철, 학, 의, ▁이름, 들은, ▁무엇인가, ?]",1567.819789,What are the names of the philosophy of the fl...
18,4-gram laplace,신화에는 그리스 신들이 몇 명이나 있을까?,"[▁신, 화, 에는, ▁그리, 스, ▁신, 들이, ▁몇, ▁명, 이나, ▁있을까, ?]",1415.856367,How many Greek gods do myths have?
19,4-gram laplace,신화에는 그리스 신들이 몇 명이나 있을까?,"[▁신, 화, 에는, ▁그리, 스, ▁신, 들이, ▁몇, ▁명, 이나, ▁있을까, ?]",1415.856367,How many Greek gods do myths have?
20,6-gram,클라미디아 발병원인은 무엇인가?,"[▁클, 라, 미, 디아, ▁발, <UNK>, 인은, ▁무엇인가, ?]",2026.680873,What is the Chlamydia launcher?
21,6-gram,7년 전쟁이 발발한 이유는 무엇인가?,"[▁7, 년, ▁전쟁, 이, ▁발, 발, 한, ▁이유는, ▁무엇인가, ?]",1975.305517,What caused the Seven Years' War?
22,6-gram,불고기는 소의 어느부위를 사용하는가?,"[▁불, 고, 기는, ▁소, 의, ▁어느, 부, 위를, ▁사용하는, 가, ?]",1933.488974,What part of the cow does the fisherman use?
23,6-gram,걸프전은 몇 년도에 끝났나?,"[▁걸, 프, 전, 은, ▁몇, ▁, 년도, 에, ▁끝, 났, 나, ?]",1917.700503,How many years did the Gulf War end?
24,6-gram,승려는 어느 종교에 종사하고 있는가?,"[▁승, <UNK>, 는, ▁어느, ▁종교, 에, ▁종, 사, 하고, ▁있는, 가, ?]",1898.797932,What religion is the quest for glory?

In [ ]:
pd.DataFrame([unigram_metrics, bigram_metrics, fourgram_add_k_metrics, fourgram_laplace_metrics, sixgram_metrics])

,model,average_perplexity,median_perplexity,min_perplexity,max_perplexity
0,unigram,251.578953,227.856656,43.569209,928.479072
1,bigram,62.486682,40.044834,5.939880,390.112906
2,fourgram add-k,292.565474,175.763041,13.029646,1933.488974
3,fourgram laplace,530.494652,441.619560,84.626409,1653.850184
4,sixgram,611.426693,468.070143,25.681725,2026.680873

## Neural Language Model

In [ ]:
!pip install gensim

Collecting gensim
  Downloading gensim-4.4.0-cp313-cp313-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (8.4 kB)
Requirement already satisfied: numpy>=1.18.5 in /usr/local/lib/python3.13/dist-packages (from gensim) (2.1.3)
Requirement already satisfied: scipy>=1.7.0 in /usr/local/lib/python3.13/dist-packages (from gensim) (1.16.3)
Requirement already satisfied: smart_open>=1.8.1 in /usr/local/lib/python3.13/dist-packages (from gensim) (8.0.1)
Requirement already satisfied: wrapt in /usr/local/lib/python3.13/dist-packages (from smart_open>=1.8.1->gensim) (2.4.1)
Downloading gensim-4.4.0-cp313-cp313-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (27.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.8/27.8 MB 21.3 MB/s eta 0:00:00
Installing collected packages: gensim
Successfully installed gensim-4.4.0

In [ ]:
import torch
import torch.nn as nn
from gensim.models import Word2Vec

### Add BOS and EOS to sequences

In [ ]:
# Add BOS and EOS for rnn training
def add_bos_eos_tokens(tokens):
    return ["<BOS>"] + tokens + ["<EOS>"]

train_sequences_rnn = [
    add_bos_eos_tokens(tokens)
    for tokens in train_sequences
]

val_sequences_rnn = [
    add_bos_eos_tokens(tokens)
    for tokens in val_sequences
]

In [ ]:
train_sequences_rnn[0]

['<BOS>', '▁30', '년', '▁전쟁', '의', '▁승', '자는', '▁누구', '인가', '?', '<EOS>']

### Create Vectors/Vocab

In [ ]:
INPUT_VECTOR_SIZE = 300
WINDOW = 5
MIN_COUNT = 2
w2v_model = Word2Vec(train_sequences_rnn, min_count=MIN_COUNT, vector_size=INPUT_VECTOR_SIZE, window=WINDOW)

In [ ]:
# Same number of keys as prediction vocabulary (+ 1 for BOS added already)
vocab_size = len(w2v_model.wv)
print(vocab_size == len(prediction_vocabulary) + 1)

True

In [ ]:
# vectorized sequences (encoding)
def encode(sequences):
  sequences_encoded = []
  for seq in sequences:
      words = []
      for word in seq:
          words.append(w2v_model.wv[word])
      sequences_encoded.append(words)
  return sequences_encoded

train_sequences_encoded = encode(train_sequences_rnn)

val_sequences_encoded = encode(val_sequences_rnn)

In [ ]:
len(train_sequences_encoded[0][0])

300

In [ ]:
word_to_idx = w2v_model.wv.key_to_index

# Indices of next word that should be predicted
def get_target_indices(sequences):
  target_indices = [
    [word_to_idx[w] for w in seq[1:]]
    for seq in sequences
  ]
  return target_indices

train_target_indices = get_target_indices(train_sequences_rnn)

val_target_indices = get_target_indices(val_sequences_rnn)

### RNN

In [ ]:
class SimpleRNN(nn.Module):
  def __init__(self, input_size, hidden_size, output_size):
    super(SimpleRNN, self).__init__()
    self.hidden_size = hidden_size
    self.input_size = input_size

    # Weight matrices
    self.W_ih = nn.Linear(input_size, hidden_size)
    self.W_hh = nn.Linear(hidden_size, hidden_size)
    self.W_hy = nn.Linear(hidden_size, output_size)

  def forward(self, x, h_prev):
    # x: input of shape (batch_size, input_size)
    # h_prev: previous hidden state of shape (batch_size, hidden_size)

    # Compute new hidden state
    h_t = torch.tanh(self.W_ih(x) + self.W_hh(h_prev))

    # Compute output
    y_t = self.W_hy(h_t)

    return y_t, h_t

  def init_hidden(self, batch_size):
    # Initialize hidden state (vector of zeros)
    return torch.zeros(batch_size, self.hidden_size)

class MultiLayerRNN(nn.Module):
  def __init__(self, input_size, hidden_size, output_size, num_layers):
    super(MultiLayerRNN, self).__init__()
    self.hidden_size = hidden_size
    self.num_layers = num_layers

    # One independent SimpleRNN per layer
    # First one takes input_size others hidden_size as thats their input
    self.layers = nn.ModuleList([
      SimpleRNN(
        input_size=input_size if i == 0 else hidden_size,
        hidden_size=hidden_size,
        output_size=output_size   # only actually used for the TOP layer's output
      )
      for i in range(num_layers)
    ])

  def forward(self, x_t, h_prev_list):
    h_new_list = []
    layer_input = x_t

    for i, layer in enumerate(self.layers):
      y_t, h_t = layer(layer_input, h_prev_list[i])
      h_new_list.append(h_t)
      layer_input = h_t

    return y_t, h_new_list

  def init_hidden(self, batch_size):
    # Initialize hidden states (vector of zeros)
    return [
        torch.zeros(batch_size, self.hidden_size)
        for _ in range(self.num_layers)
    ]

In [ ]:
# Initialize model, loss and optimizer
INPUT_SIZE = INPUT_VECTOR_SIZE
HIDDEN_SIZE = 64
OUTPUT_SIZE = vocab_size
NUM_LAYERS = 2
# BATCH_SIZE: how many independet examples get processed together?
# Higher -> Faster (parallel) + less noise (gradient averaged)
BATCH_SIZE = 1
LEARNING_RATE = 0.001

multi_layer_rnn_model = MultiLayerRNN(
    input_size=INPUT_SIZE,
    hidden_size=HIDDEN_SIZE,
    output_size=OUTPUT_SIZE,
    num_layers=NUM_LAYERS
)

criterion = nn.CrossEntropyLoss() # for softmax and calc of loss/grad
optimizer = torch.optim.Adam(multi_layer_rnn_model.parameters(), lr=0.001)  # adjust weights

In [ ]:
def train_rnn(
    model,
    criterion,
    optimizer,
    target_indices,
    sequences_encoded,
    batch_size,
    num_epochs
):
  for epoch in range(num_epochs):
    epoch_loss = 0.0

    for seq_idx, seq in enumerate(sequences_encoded):
      h_list = model.init_hidden(batch_size)
      optimizer.zero_grad()

      seq_loss = 0.0
      for t in range(len(seq) - 1):
        x_t = torch.tensor(seq[t], dtype=torch.float32).unsqueeze(0)
        target_t = torch.tensor([target_indices[seq_idx][t]])  # index of next word

        y_t, h_list = model(x_t, h_list)

        # softmaxes y_t and then looks up probability of target index (next word)
        # lower probability -> higher loss (only calculates)
        loss = criterion(y_t, target_t)
        seq_loss += loss

      # backprop through this sequence (computes gradients for each matrix, stored in .grad)
      seq_loss.backward()
      # update weights based on the calculated gradients for each Matrix
      optimizer.step()

      epoch_loss += seq_loss.item()

    print(f"Epoch {epoch+1}, Total Loss: {epoch_loss:.4f}")

In [ ]:
NUM_EPOCHS = 10
train_rnn(
  model=multi_layer_rnn_model,
  criterion=criterion,
  optimizer=optimizer,
  target_indices=train_target_indices,
  sequences_encoded=train_sequences_encoded,
  batch_size=BATCH_SIZE,
  num_epochs=NUM_EPOCHS
)

Epoch 1, Total Loss: 156993.8973
Epoch 2, Total Loss: 138515.6843
Epoch 3, Total Loss: 131673.3170
Epoch 4, Total Loss: 126967.6183
Epoch 5, Total Loss: 123393.9316
Epoch 6, Total Loss: 120619.7399
Epoch 7, Total Loss: 118277.4900
Epoch 8, Total Loss: 116323.5139
Epoch 9, Total Loss: 114578.1674
Epoch 10, Total Loss: 112959.6254

### Perplexity

In [ ]:
def calc_perplexity_rnn_token(
    model,
    criterion,
    target_indices,
    questions,
    sequences,
    adjusted_sequences,
    sequences_encoded,
    batch_size
):
    model.eval()
    question_scores = []
    token_scores = []

    with torch.no_grad():
        for seq_idx, seq in enumerate(sequences_encoded):
            seq_loss = 0.0
            h_list = model.init_hidden(batch_size)

            token_seq_scores = []

            # get sequences to same length as encoded_sequences (has no BOS)
            padded_sequence = ["-"] + sequences[seq_idx] + ["-"]

            for t in range(len(seq) - 1):
                x_t = torch.tensor(seq[t], dtype=torch.float32).unsqueeze(0)
                target_t = torch.tensor([target_indices[seq_idx][t]])

                y_t, h_list = model(x_t, h_list)
                loss = criterion(y_t, target_t)
                seq_loss += loss

                token_perplexity = torch.exp(loss)

                token_score = {
                    "token": padded_sequence[t + 1],
                    "adjusted_token": adjusted_sequences[seq_idx][t + 1],
                    "perplexity": token_perplexity.item(),
                }
                token_seq_scores.append(token_score)

            token_scores.append(token_seq_scores)

            seq_avg_loss = seq_loss / (len(seq) - 1)
            seq_perplexity = torch.exp(seq_avg_loss)

            seq_score = {
                "question": questions[seq_idx],
                "perplexity": seq_perplexity.item(),
            }
            question_scores.append(seq_score)

    return question_scores, token_scores

In [ ]:
rnn_perplexity, rnn_token_perplexity = calc_perplexity_rnn_token(
  model=multi_layer_rnn_model,
  criterion=criterion,
  target_indices=val_target_indices,
  questions=ko_val_questions,
  sequences=val_questions_tokenized,
  adjusted_sequences=val_sequences_rnn,
  sequences_encoded=val_sequences_encoded,
  batch_size=BATCH_SIZE
)

In [ ]:
df_rnn_perplexity = pd.DataFrame(rnn_perplexity)
lowest_rnn = df_rnn_perplexity.nsmallest(5, 'perplexity').copy()
highest_rnn = df_rnn_perplexity.nlargest(5, 'perplexity').copy()

for table in (lowest_rnn, highest_rnn):
    table["translation_en"] = table["question"].apply(
        lambda question: translate(question, KO, EN)
    )

### RNN Results

In [ ]:
df_lowest_rnn = lowest_rnn[["question", "translation_en", "perplexity"]].copy()
df_highest_rnn = highest_rnn[["question", "translation_en", "perplexity"]].copy()

In [ ]:
def calc_mean_token_count(idx, token_perplexity):
  df_token_perplexity = pd.DataFrame(token_perplexity[idx])
  sum_count_tokens = 0
  for i, token in enumerate(df_token_perplexity['adjusted_token']):
    if token != '?' and token != '<EOS>':
      sum_count_tokens += token_counts[token]
  return sum_count_tokens / (len(df_token_perplexity['adjusted_token']))

In [ ]:
df_lowest_rnn['mean_token_count'] = [calc_mean_token_count(idx, rnn_token_perplexity) for idx in df_lowest_rnn.index]
df_highest_rnn['mean_token_count'] = [calc_mean_token_count(idx, rnn_token_perplexity) for idx in df_highest_rnn.index]

In [ ]:
print(df_lowest_rnn['mean_token_count'].mean())
print(df_highest_rnn['mean_token_count'].mean())

355.43202797202804
80.65029137529137

In [ ]:
display(df_lowest_rnn)
display(df_highest_rnn)

,question,translation_en,perplexity,mean_token_count
301,중국에서 가장 인구밀도가 높은 도시는 어디인가?,What is the most densely populated city in China?,4.214709,259.769231
239,세상에서 가장 큰 대학교는 무엇인가?,What is the largest university in the world?,4.222419,412.300000
83,세상에서 가장 오래된 대학교는 무엇인가?,What is the oldest university in the world?,5.099924,368.363636
161,세상에서 가장 오래된 대학교는 무엇인가?,What is the oldest university in the world?,5.099924,368.363636
167,세상에서 가장 오래된 대학교는 무엇인가?,What is the oldest university in the world?,5.099924,368.363636

,question,translation_en,perplexity,mean_token_count
198,불고기는 소의 어느부위를 사용하는가?,What part of the cow does the fisherman use?,709.477600,121.583333
232,신화에는 그리스 신들이 몇 명이나 있을까?,How many Greek gods do myths have?,672.643616,48.923077
314,신화에는 그리스 신들이 몇 명이나 있을까?,How many Greek gods do myths have?,672.643616,48.923077
254,기업법을 어겼을때 어느부서에서 관리를 하는가?,What department do you run when you break the ...,615.607910,100.125000
280,"임시정부는 종전의 정부가 무너진 후, 무정부 상태를 해소하기 위해 임시로 구성된 정...",Does the interim government say that it is a t...,452.778778,83.696970

In [ ]:
df_rnn_token_perplexity = pd.DataFrame(rnn_token_perplexity[198])
df_rnn_token_perplexity

    token adjusted_token    perplexity
0      ▁불             ▁불  21734.210938
1       고              고    679.803528
2      기는             기는    661.919800
3      ▁소             ▁소  19096.744141
4       의              의     31.452448
5     ▁어느            ▁어느   3544.187500
6       부              부  11244.847656
7      위를             위를  37134.957031
8   ▁사용하는          ▁사용하는   8052.287109
9       가              가    138.531265
10      ?              ?      1.670436
11      -          <EOS>      1.004065

In [ ]:
calc_mean_token_count(301, rnn_token_perplexity)

259.7692307692308

In [ ]:
rnn_mean_perplexity = df_rnn_perplexity['perplexity'].mean()
rnn_median_perplexity = df_rnn_perplexity['perplexity'].median()
rnn_min_perplexity = df_rnn_perplexity['perplexity'].min()
rnn_max_perplexity = df_rnn_perplexity['perplexity'].max()

print(f"RNN mean perplexity:    {rnn_mean_perplexity}")
print(f"RNN median perplexity:  {rnn_median_perplexity}")

RNN mean perplexity:    85.57710720581954
RNN median perplexity:  47.159542083740234

In [ ]:
rnn_metrics = {
    "model": "Multilayer RNN",
    "average_perplexity": rnn_mean_perplexity,
    "median_perplexity": rnn_median_perplexity,
    "min_perplexity": rnn_min_perplexity,
    "max_perplexity": rnn_max_perplexity
}

## Overall Results

In [ ]:
pd.DataFrame([unigram_metrics, bigram_metrics, fourgram_add_k_metrics, fourgram_laplace_metrics, sixgram_metrics, rnn_metrics])

,model,average_perplexity,median_perplexity,min_perplexity,max_perplexity
0,unigram,251.578953,227.856656,43.569209,928.479072
1,bigram,62.486682,40.044834,5.939880,390.112906
2,fourgram add-k,292.565474,175.763041,13.029646,1933.488974
3,fourgram laplace,530.494652,441.619560,84.626409,1653.850184
4,sixgram,611.426693,468.070143,25.681725,2026.680873
5,Multilayer RNN,85.052405,49.375526,4.254868,750.986328

# Week 39

## Interpretable learned baseline

## RNN classifier

### Embedding

In [ ]:
!pip install bpemb sentencepiece
from bpemb import BPEmb

Requirement already satisfied: bpemb in /usr/local/lib/python3.13/dist-packages (0.3.6)
Requirement already satisfied: sentencepiece in /usr/local/lib/python3.13/dist-packages (0.2.2)
Requirement already satisfied: gensim in /usr/local/lib/python3.13/dist-packages (from bpemb) (4.4.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.13/dist-packages (from bpemb) (2.1.3)
Requirement already satisfied: requests in /usr/local/lib/python3.13/dist-packages (from bpemb) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.13/dist-packages (from bpemb) (4.67.3)
Requirement already satisfied: scipy>=1.7.0 in /usr/local/lib/python3.13/dist-packages (from gensim->bpemb) (1.16.3)
Requirement already satisfied: smart_open>=1.8.1 in /usr/local/lib/python3.13/dist-packages (from gensim->bpemb) (8.0.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests->bpemb) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests->bpemb) (3.19)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests->bpemb) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests->bpemb) (2026.7.22)
Requirement already satisfied: wrapt in /usr/local/lib/python3.13/dist-packages (from smart_open>=1.8.1->gensim->bpemb) (2.4.1)

In [ ]:
NUM_WORDS = 100000
INPUT_DIMENSIONS = 300
multilingual_bpemb = BPEmb(lang="multi", vs=NUM_WORDS, dim=INPUT_DIMENSIONS)

# Week 40-41

## Tokenizer and Model

In [14]:
MODEL_NAME = "google-bert/bert-base-multilingual-cased"

bert_tokenizer = AutoTokenizer.from_pretrained(
    MODEL_NAME,
    use_fast=True,
)

bert_model = AutoModelForQuestionAnswering.from_pretrained(
    MODEL_NAME
)

config.json:   0%|          | 0.00/625 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/49.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/996k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.96M [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  714MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] BertForQuestionAnswering LOAD REPORT from: google-bert/bert-base-multilingual-cased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.weight     | UNEXPECTED |
bert.pooler.dense.bias                     | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
bert.pooler.dense.weight                   | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
qa_outputs.bias                            | MISSING    |
qa_outputs.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

## Data processing

In [52]:
import torch
import pandas as pd


def make_training_data(row):

    encoding = bert_tokenizer(
        row["question"],
        row["context"],
        max_length=512,
        truncation="only_second",
        padding="max_length",
        return_offsets_mapping=True,
        return_tensors="pt",
    )
    answer = row["answer"]
    answer_start = row["answer_start"]

    input_ids = encoding["input_ids"][0]
    offsets = encoding["offset_mapping"][0].tolist()
    sequence_ids = encoding.sequence_ids(0)

    start_position = 0
    end_position = 0

    if answer_start != -1:
        answer_end = answer_start + len(answer)

        answer_token_indices = []

        for token_index, (offset, sequence_id) in enumerate(
            zip(offsets, sequence_ids)
        ):
            token_start, token_end = offset

            if (
                sequence_id == 1
                and token_end > answer_start
                and token_start < answer_end
            ):
                answer_token_indices.append(token_index)

        if answer_token_indices:
            start_position = answer_token_indices[0]
            end_position = answer_token_indices[-1]

    return {
        "input_ids": input_ids,
        "attention_mask": encoding["attention_mask"][0],
        "token_type_ids": encoding["token_type_ids"][0],
        "start_positions": torch.tensor(start_position),
        "end_positions": torch.tensor(end_position),
    }

In [16]:
result = make_training_data(df_train.iloc[3])


result

{'input_ids': tensor([   101,  46085,  19910,    118,    939,  98410,  29484,  42620,  12235,
         107531,  11199,  46085, 100047,  96134,    100,    978, 111238,  11737,
          50263,    972,  45908,  15215,  16166,    100,    136,    102,  10117,
          45809,  11487,  10108,  17365,  69297,  10124,  27306,    119,  11340,
          78059,  19261,  10105,  17365,  12557,  81754,  10160,    128,    117,
          10259,    117,  11198,    124,    117,  10259,  56119,  10107,    117,
            123,    117,  10259,  34624,  10107,    117,    122,    117,  10259,
          16366,  34615,    117,  10111,    122,    117,  10259,  44152,  10107,
            119,  10167,  10947,    117,  56119,  27914,  13491,  10575,  10164,
            118,  13491,  10575,  87382,  10189,  10105,  17365,  84773,    112,
          25302,  45353,  24074,  10336,  10114,    124,    117,  12367,    117,
          10169,  20440,  27817,  72488,  15670,  10111,  10777,  55143,  23324,
          10111,  16366,  27817,  37257,  15670,  10107,  10111,  10777,  55143,
          10107,    119,  14156,  10114,  11601,  41712,  10107,    117,  10105,
          56119,  10107,  26090,  15790,  10105,  17119,  45353,    117,  10169,
          10249,    117,  10259,  23457,    117,    122,    117,  35112,  10108,
          18104,  10301,  11053,  10114,  10529,  12482,  10106,  18159,  52844,
            119,  12610,  10105,  50308,    117,    125,    117,  44827,  25430,
          11324,  14985,  10473,  10105,  11192,    117,  36243,  10157,  10111,
          13664,  10108,  10455,  12557,  10124,  11053,    117,  10111,    169,
          14586,    128,    117, 104367,    117,  10142,  18104,  10893,  10105,
          11192,  10108,  12557,  10124,  11053,    117,  10472,  10455,  38938,
          12752,  14197,  31515,  10105,  13664,  10108,  10455,  12557,    119,
          14156,  10114,  41712,  10107,    117,  10105,  15363,  10668,  10108,
          56119,  69297,  31465,  10108,  10446,    118,  18159,  22595,  10111,
          42996,  10107,  10114,  10105,  17330,  18356,  10108,  10105,  28446,
          10107,    119,    102,      0,      0,      0,      0,      0,      0,
              0,      0,      0,      0,      0,      0,      0,      0,      0,
              0,      0,      0,      0,      0,      0,      0,      0,      0,
              0,      0,      0,      0,      0,      0,      0,      0,      0,
              0,      0,      0,      0,      0,      0,      0,      0,      0,
              0,      0,      0,      0,      0,      0,      0,      0,      0,
              0,      0,      0,      0,      0,      0,      0,      0,      0,
              0,      0,      0,      0,      0,      0,      0,      0,      0,
              0,      0,      0,      0,      0,      0,      0,      0,      0,
              0,      0,      0,      0,      0,      0,      0,      0,      0,
              0,      0,      0,      0,      0,      0,      0,      0,      0,
              0,      0,      0,      0,      0,      0,      0,      0,      0,
              0,      0,      0,      0,      0,      0,      0,      0,      0,
              0,      0,      0,      0,      0,      0,      0,      0,      0,
              0,      0,      0,      0,      0,      0,      0,      0,      0,
              0,      0,      0,      0,      0,      0,      0,      0,      0,
              0,      0,      0,      0,      0,      0,      0,      0,      0,
              0,      0,      0,      0,      0,      0,      0,      0,      0,
              0,      0,      0,      0,      0,      0,      0,      0,      0,
              0,      0,      0,      0,      0,      0,      0,      0,      0,
              0,      0,      0,      0,      0,      0,      0,      0,      0,
              0,      0,      0,      0,      0,      0,      0,      0,      0,
              0,      0,      0,      0,      0,      0,      0,      0,      0,
              0,      0,      0,      0,      0,      0,      0,      0,      0,
              0,      0,      0,      0,      0,      0,      0,      0,      0,
              0,      0,      0,      0,      0,      0,      0,      0,      0,
              0,      0,      0,      0,      0,      0,      0,      0,      0,
              0,      0,      0,      0,      0,      0,      0,      0,      0,
              0,      0,      0,      0,      0,      0,      0,      0,      0,
              0,      0,      0,      0,      0,      0,      0,      0,      0,
              0,      0,      0,      0,      0,      0,      0,      0]),
 'attention_mask': tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0]),
 'token_type_ids': tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0]),
 'start_positions': tensor(33),
 'end_positions': tensor(33)}

In [53]:
df_train = df_train[
    df_train["lang"].isin(["ar", "ko", "te"])
].copy()

df_val = df_val[
    df_val["lang"].isin(["ar", "ko", "te"])
].copy()

df_train["training_data"] = df_train.apply(
    make_training_data,
    axis=1,
)

In [21]:
train_data = df_train["training_data"].tolist()

train_loader = DataLoader(
    train_data,
    batch_size=4,
    shuffle=True,
)

## Train

In [37]:
import torch

device = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)

bert_model = bert_model.to(device)

print(device)

cuda

In [38]:
optimizer = torch.optim.AdamW(
    bert_model.parameters(),
    lr=2e-5,
    weight_decay=0.01,
)

In [39]:
BERT_MODEL_PATH = "./models/week40_berts"

def bert_train():
  NUM_EPOCHS = 3

  for epoch in range(NUM_EPOCHS):
      bert_model.train()
      total_train_loss = 0

      progress_bar = tqdm(
          train_loader,
          desc=f"Epoch {epoch + 1}",
      )

      for batch in progress_bar:
          batch = {
              name: value.to(device)
              for name, value in batch.items()
          }

          optimizer.zero_grad()

          outputs = bert_model(**batch)
          loss = outputs.loss

          loss.backward()

          torch.nn.utils.clip_grad_norm_(
              bert_model.parameters(),
              max_norm=1.0,
          )

          optimizer.step()

          total_train_loss += loss.item()

          progress_bar.set_postfix(
              loss=loss.item()
          )

      average_train_loss = (
          total_train_loss / len(train_loader)
      )

      print(
          f"Epoch {epoch + 1}: "
          f"training loss = {average_train_loss:.4f}"
      )

  bert_model.save_pretrained(BERT_MODEL_PATH)
  bert_tokenizer.save_pretrained(BERT_MODEL_PATH)

  return bert_model, bert_tokenizer

In [42]:
if os.path.exists(BERT_MODEL_PATH):
  bert_tokenizer = AutoTokenizer.from_pretrained(
      BERT_MODEL_PATH
  )

  bert_model = AutoModelForQuestionAnswering.from_pretrained(
      BERT_MODEL_PATH
  )
else:
  bert_model, bert_tokenizer = bert_train()

Epoch 1:   0%|          | 0/1584 [00:00<?, ?it/s]

Epoch 1: training loss = 0.5305

Epoch 2:   0%|          | 0/1584 [00:00<?, ?it/s]

Epoch 2: training loss = 0.3608

Epoch 3:   0%|          | 0/1584 [00:00<?, ?it/s]

Epoch 3: training loss = 0.2862

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

## Evaluation Scores

In [43]:
bert_model.eval()

BertForQuestionAnswering(
  (bert): BertModel(
    (embeddings): BertEmbeddings(
      (word_embeddings): Embedding(119547, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (token_type_embeddings): Embedding(2, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0-11): 12 x BertLayer(
          (attention): BertAttention(
            (self): BertSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
          )
          (intermediate): BertIntermediate(
            (dense): Linear(in_features=768, out_features=3072, bias=True)
            (intermediate_act_fn): GELUActivation()
          )
          (output): BertOutput(
            (dense): Linear(in_features=3072, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
    )
  )
  (qa_outputs): Linear(in_features=768, out_features=2, bias=True)
)

In [74]:
def get_validation_scores(row):
    encoding = bert_tokenizer(
        row["question"],
        row["context"],
        max_length=512,
        truncation="only_second",
        padding="max_length",
        return_offsets_mapping=True,
        return_tensors="pt",
    )

    model_inputs = {
        key: encoding[key].to(device)
        for key in [
            "input_ids",
            "attention_mask",
            "token_type_ids",
        ]
        if key in encoding
    }

    bert_model.eval()

    with torch.no_grad():
        outputs = bert_model(**model_inputs)

    start_logits = outputs.start_logits[0].cpu()
    end_logits = outputs.end_logits[0].cpu()

    input_ids = encoding["input_ids"][0]
    offsets = encoding["offset_mapping"][0].tolist()
    sequence_ids = encoding.sequence_ids(0)

    cls_span_score = (
        start_logits[0].item()
        + end_logits[0].item()
    )

    context_indices = [
        index
        for index, sequence_id in enumerate(sequence_ids)
        if sequence_id == 1
    ]

    best_span_score = float("-inf")
    best_start = None
    best_end = None

    for start_index in context_indices:
        for end_index in context_indices:
            if end_index < start_index:
                continue
            if end_index - start_index + 1 > 30:
                continue

            span_length = end_index - start_index + 1

            span_score = (
                start_logits[start_index].item()
                + end_logits[end_index].item()
            )

            if span_score > best_span_score:
                best_span_score = span_score
                best_start = start_index
                best_end = end_index

    char_start = offsets[best_start][0]
    char_end = offsets[best_end][1]

    best_span = row["context"][char_start:char_end]

    no_answer_score = cls_span_score - best_span_score

    return pd.Series({
        "cls_span_score": cls_span_score,
        "best_span_score": best_span_score,
        "no_answer_score": no_answer_score,
        "best_start_token": best_start,
        "best_end_token": best_end,
        "best_span": best_span,
    })

In [76]:
validation_scores = df_val.apply(
    get_validation_scores,
    axis=1,
)

df_val = pd.concat(
    [df_val, validation_scores],
    axis=1,
)

In [78]:
df_val.head()

,question,context,lang,answerable,answer_start,answer,answer_inlang,validation_scores,cls_span_score,best_span_score,no_answer_score,best_start_token,best_end_token,best_span
0,ఒరెగాన్ రాష్ట్రంలోని అతిపెద్ద నగరం ఏది ?,Portland is the largest city in the U.S. state...,te,True,0,Portland,NaN,"{'cls_span_score': -4.478857398033142, 'best_s...",-4.478857,21.318310,-25.797167,114,114,Seattle
1,కలరా వ్యాధిని మొదటగా ఏ దేశంలో కనుగొన్నారు ?,"The word cholera is from ""kholera"" from χολή ""...",te,True,99,Indian subcontinent,NaN,"{'cls_span_score': -14.019891262054443, 'best_...",-14.019891,9.051684,-23.071576,58,61,Indian subcontinent
2,కలరా వ్యాధిని మొదటగా ఏ దేశంలో కనుగొన్నారు ?,Since it became widespread in the 19th century...,te,True,451,England,NaN,"{'cls_span_score': -10.133697032928467, 'best_...",-10.133697,22.289547,-32.423244,105,106,United States
3,మొదటి ప్రపంచ యుద్ధం ఎప్పుడు మొదలయింది ?,World War I occurred from 1914 to 1918. In ter...,te,True,26,1914,NaN,"{'cls_span_score': -13.134979248046875, 'best_...",-13.134979,20.782411,-33.917390,20,22,1914 to 1918
4,మొదటి ప్రపంచ యుద్ధం ఎప్పుడు మొదలయింది ?,"World War I (often abbreviated as WWI or WW1),...",te,True,155,28 July 1914,NaN,"{'cls_span_score': -18.504823684692383, 'best_...",-18.504824,19.275352,-37.780175,58,58,1914

## Threshold Selection

In [81]:
import string

def squad_v2_normalize(text):
    text = text.lower()

    text = "".join(
        character
        for character in text
        if character not in string.punctuation
    )

    text = re.sub(r"\b(a|an|the)\b", " ", text)

    return " ".join(text.split())

def exact_match(prediction, gold):
    return float(squad_v2_normalize(prediction) == squad_v2_normalize(gold))

def token_f1(prediction, gold):
    prediction_tokens = squad_v2_normalize(prediction).split()
    gold_tokens = squad_v2_normalize(gold).split()

    if not prediction_tokens or not gold_tokens:
      return float(prediction_tokens == gold_tokens)

    overlap_number = sum((Counter(prediction_tokens) & Counter(gold_tokens)).values())

    if overlap_number == 0:
      return 0.0

    precision = overlap_number / len(prediction_tokens)
    recall = overlap_number / len(gold_tokens)

    return 2 * precision * recall / (precision + recall)

In [82]:
threshold_results = []

for threshold in range(-50, 50, 1):
    predictions = np.where(
        df_val["no_answer_score"] > threshold,
        "",
        df_val["best_span"],
    )

    f1_scores = [
        token_f1(prediction, gold)
        for prediction, gold in zip(
            predictions,
            df_val["answer"],
        )
    ]

    exact_scores = [
        exact_match(prediction, gold)
        for prediction, gold in zip(
            predictions,
            df_val["answer"],
        )
    ]

    threshold_results.append({
        "threshold": threshold,
        "token_f1": np.mean(f1_scores),
        "exact_match": np.mean(exact_scores),
    })

In [83]:
best_result = max(
    threshold_results,
    key=lambda result: (
        result["token_f1"],
        result["exact_match"],
    ),
)

best_threshold = best_result["threshold"]

print("Best threshold:", best_threshold)
print("Validation token F1:", best_result["token_f1"])
print("Validation exact match:", best_result["exact_match"])

Best threshold: 31
Validation token F1: 0.5677008609398524
Validation exact match: 0.4753246753246753